# Generated by Django 3.2.6 on 2021-08-23 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_item', models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='检查项目')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '血液检查',
                'verbose_name_plural': '血液检查',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Classification_survey_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surver_items', models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='调查项目')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '调查分类清单',
                'verbose_name_plural': '调查分类清单',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Routine_physical_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='性别')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('height', models.CharField(blank=True, max_length=60, null=True, verbose_name='身高')),
                ('weight', models.CharField(blank=True, max_length=60, null=True, verbose_name='体重')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体质指数')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('test_comments', models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='评估意见')),
            ],
            options={
                'verbose_name': '常规体格检查表',
                'verbose_name_plural': '常规体格检查表',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Metadata_follow_up_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('serial_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='编号')),
                ('classification', models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='随访分类')),
                ('opinion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='随访意见')),
                ('agency', models.CharField(blank=True, max_length=60, null=True, verbose_name='随访机构')),
                ('doctor_signature', models.CharField(blank=True, max_length=60, null=True, verbose_name='随访医生签名')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='随访日期')),
                ('next_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='下次随访日期')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('method', models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc2_reservation_investigations', verbose_name='随访方式')),
            ],
            options={
                'verbose_name': '通用随访表',
                'verbose_name_plural': '通用随访表',
                'ordering': [],
            },
        ),
    ]
