# Generated by Django 3.2.6 on 2021-08-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification_checklist',
        ),
        migrations.DeleteModel(
            name='Classification_survey_list',
        ),
        migrations.RemoveField(
            model_name='routine_physical_examination',
            name='test_comments',
        ),
        migrations.DeleteModel(
            name='Metadata_follow_up_form',
        ),
        migrations.DeleteModel(
            name='Routine_physical_examination',
        ),
    ]
