# Generated by Django 3.2.6 on 2022-01-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha',
            name='relatedfield_symptom_list',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan',
            name='relatedfield_disease_name',
        ),
        migrations.RemoveField(
            model_name='tang_hua_xue_hong_dan_bai_jian_cha',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tang_hua_xue_hong_dan_bai_jian_cha',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='tang_hua_xue_hong_dan_bai_jian_cha',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='yong_yao_chu_fang',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='yong_yao_chu_fang',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='yong_yao_chu_fang',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='yong_yao_chu_fang',
            name='relatedfield_drug_name',
        ),
        migrations.AddField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_can_you_get_encouragement_and_support_from_family_and_friends',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_for_relatedfield_can_you_get_encouragement_and_support_from_family_and_friends_personal_adaptability_assessment', to='dictionaries.frequency', verbose_name='是否能得到家人朋友的鼓励和支持'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Kong_fu_xue_tang_jian_cha',
        ),
        migrations.DeleteModel(
            name='Men_zhen_wen_zhen_diao_cha',
        ),
        migrations.DeleteModel(
            name='Men_zhen_zhen_duan',
        ),
        migrations.DeleteModel(
            name='Tang_hua_xue_hong_dan_bai_jian_cha',
        ),
        migrations.DeleteModel(
            name='Yong_yao_chu_fang',
        ),
    ]
