# Generated by Django 3.2.6 on 2022-01-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_can_you_get_encouragement_and_support_from_family_and_friends',
        ),
    ]
