# Generated by Django 3.2.6 on 2022-04-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('icpc', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T9001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_operator', to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_di_yi_zhen_duan', models.ManyToManyField(related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_di_yi_zhen_duan_T9001', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='第一诊断')),
                ('relatedfield_disease_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_disease_name_T9001', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称')),
                ('relatedfield_pai_chu_zhen_duan', models.ManyToManyField(related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_pai_chu_zhen_duan_T9001', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='排除诊断')),
                ('relatedfield_yi_lou_zhen_duan', models.ManyToManyField(related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_yi_lou_zhen_duan_T9001', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='可能诊断')),
            ],
            options={
                'verbose_name': '非胰岛素依赖性糖尿病',
                'verbose_name_plural': '非胰岛素依赖性糖尿病',
            },
        ),
        migrations.CreateModel(
            name='TestSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(default='Test Admin Area', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='relatedfield_di_yi_zhen_duan',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='relatedfield_disease_name',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='relatedfield_pai_chu_zhen_duan',
        ),
        migrations.RemoveField(
            model_name='tang_niao_bing_zhen_duan_biao',
            name='relatedfield_yi_lou_zhen_duan',
        ),
        migrations.AlterModelOptions(
            name='a3001',
            options={'verbose_name': '辅助检查表', 'verbose_name_plural': '辅助检查表'},
        ),
        migrations.RemoveField(
            model_name='a3001',
            name='characterfield_left_eye_vision',
        ),
        migrations.RemoveField(
            model_name='a3001',
            name='characterfield_right_eye_vision',
        ),
        migrations.RemoveField(
            model_name='a6203',
            name='relatedfield_family_id',
        ),
        migrations.RemoveField(
            model_name='a6501',
            name='characterfield_service_role',
        ),
        migrations.RemoveField(
            model_name='t6301',
            name='relatedfield_family_id',
        ),
        migrations.AddField(
            model_name='a6219',
            name='boolfield_tang_niao_bing_zheng_zhuang',
            field=models.ManyToManyField(related_name='tang_niao_bing_zheng_zhuang_for_boolfield_tang_niao_bing_zheng_zhuang_A6219', to='dictionaries.Tang_niao_bing_zheng_zhuang', verbose_name='糖尿病症状'),
        ),
        migrations.AddField(
            model_name='a6501',
            name='boolfield_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_boolfield_ze_ren_ren_A6501', to='core.staff', verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='a3502',
            name='boolfield_tong_ti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tong_ti_for_boolfield_tong_ti_A3502', to='dictionaries.tong_ti', verbose_name='尿酮体'),
        ),
        migrations.DeleteModel(
            name='Tang_niao_bing_cha_ti_biao',
        ),
        migrations.DeleteModel(
            name='Tang_niao_bing_zhen_duan_biao',
        ),
    ]
