# Generated by Django 3.2.6 on 2022-01-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('forms', '0002_auto_20220110_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergies_history',
            name='relatedfield_drug_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_list_for_relatedfield_drug_name_allergies_history', to='dictionaries.drug_list', verbose_name='药品名称'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_type_for_relatedfield_blood_type_basic_personal_information', to='dictionaries.blood_type', verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_for_relatedfield_education_basic_personal_information', to='dictionaries.education', verbose_name='文化程度'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc1_register_logins_for_relatedfield_family_id_basic_personal_information', to='icpc.icpc1_register_logins', verbose_name='家庭编号'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_family_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_relationship_for_relatedfield_family_relationship_basic_personal_information', to='dictionaries.family_relationship', verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_for_relatedfield_gender_basic_personal_information', to='dictionaries.gender', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marital_status_for_relatedfield_marital_status_basic_personal_information', to='dictionaries.marital_status', verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_medical_expenses_burden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_expenses_burden_for_relatedfield_medical_expenses_burden_basic_personal_information', to='dictionaries.medical_expenses_burden', verbose_name='医疗费用负担'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality_for_relatedfield_nationality_basic_personal_information', to='dictionaries.nationality', verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_occupational_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupational_status_for_relatedfield_occupational_status_basic_personal_information', to='dictionaries.occupational_status', verbose_name='职业状况'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_signed_family_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_list_for_relatedfield_signed_family_doctor_basic_personal_information', to='dictionaries.employee_list', verbose_name='签约家庭医生'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_type_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_residence_for_relatedfield_type_of_residence_basic_personal_information', to='dictionaries.type_of_residence', verbose_name='居住类型'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='relatedfield_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions_list_for_relatedfield_affiliation_doctor_registry', to='dictionaries.institutions_list', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='relatedfield_service_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_role_for_relatedfield_service_role_doctor_registry', to='dictionaries.service_role', verbose_name='服务角色'),
        ),
        migrations.AlterField(
            model_name='dorsal_artery_pulsation_examination',
            name='relatedfield_left_foot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dorsal_artery_pulsation_for_relatedfield_left_foot_dorsal_artery_pulsation_examination', to='dictionaries.dorsal_artery_pulsation', verbose_name='左脚'),
        ),
        migrations.AlterField(
            model_name='dorsal_artery_pulsation_examination',
            name='relatedfield_right_foot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dorsal_artery_pulsation_for_relatedfield_right_foot_dorsal_artery_pulsation_examination', to='dictionaries.dorsal_artery_pulsation', verbose_name='右脚'),
        ),
        migrations.AlterField(
            model_name='family_history_of_illness',
            name='relatedfield_diseases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_diseases_family_history_of_illness', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='病名'),
        ),
        migrations.AlterField(
            model_name='family_history_of_illness',
            name='relatedfield_family_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_relationship_for_relatedfield_family_relationship_family_history_of_illness', to='dictionaries.family_relationship', verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='fundus_examination',
            name='relatedfield_fundus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normality_for_relatedfield_fundus_fundus_examination', to='dictionaries.normality', verbose_name='眼底'),
        ),
        migrations.AlterField(
            model_name='history_of_infectious_diseases',
            name='relatedfield_diseases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_diseases_history_of_infectious_diseases', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='病名'),
        ),
        migrations.AlterField(
            model_name='history_of_infectious_diseases',
            name='relatedfield_family_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_relationship_for_relatedfield_family_relationship_history_of_infectious_diseases', to='dictionaries.family_relationship', verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='history_of_surgery',
            name='relatedfield_name_of_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc7_treatments_for_relatedfield_name_of_operation_history_of_surgery', to='icpc.icpc7_treatments', verbose_name='手术名称'),
        ),
        migrations.AlterField(
            model_name='history_of_trauma',
            name='relatedfield_diseases_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_diseases_name_history_of_trauma', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='病名'),
        ),
        migrations.AlterField(
            model_name='lower_extremity_edema_examination',
            name='relatedfield_lower_extremity_edema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edema_for_relatedfield_lower_extremity_edema_lower_extremity_edema_examination', to='dictionaries.edema', verbose_name='下肢水肿'),
        ),
        migrations.AlterField(
            model_name='major_life_events',
            name='relatedfield_major_life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_event_for_relatedfield_major_life_major_life_events', to='dictionaries.life_event', verbose_name='生活事件'),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='relatedfield_disease_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_disease_name_medical_history', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称'),
        ),
        migrations.AlterField(
            model_name='out_of_hospital_self_report_survey',
            name='relatedfield_symptom_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_out_of_hospital_self_report_survey', to='icpc.icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_are_you_satisfied_with_the_job_and_life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_for_relatedfield_are_you_satisfied_with_the_job_and_life_personal_adaptability_assessment', to='dictionaries.satisfaction', verbose_name='对目前生活和工作满意吗'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_are_you_satisfied_with_your_adaptability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_for_relatedfield_are_you_satisfied_with_your_adaptability_personal_adaptability_assessment', to='dictionaries.satisfaction', verbose_name='对自己的适应能力满意吗'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_can_you_get_encouragement_and_support_from_family_and_friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_for_relatedfield_can_you_get_encouragement_and_support_from_family_and_friends_personal_adaptability_assessment', to='dictionaries.frequency', verbose_name='是否能得到家人朋友的鼓励和支持'),
        ),
        migrations.AlterField(
            model_name='personal_comprehensive_psychological_quality_survey',
            name='relatedfield_personality_tendency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_for_relatedfield_personality_tendency_personal_comprehensive_psychological_quality_survey', to='dictionaries.character', verbose_name='性格倾向'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='relatedfield_compared_to_last_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_expression_for_relatedfield_compared_to_last_year_personal_health_assessment', to='dictionaries.comparative_expression', verbose_name='较之过去一年状态如何'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='relatedfield_exercise_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_time_for_relatedfield_exercise_time_personal_health_assessment', to='dictionaries.exercise_time', verbose_name='运动时长'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='relatedfield_have_any_recent_symptoms_of_physical_discomfort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc3_symptoms_and_problems_for_relatedfield_have_any_recent_symptoms_of_physical_discomfort_personal_health_assessment', to='icpc.icpc3_symptoms_and_problems', verbose_name='近来有无身体不适症状'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='relatedfield_own_health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_degree_for_relatedfield_own_health_personal_health_assessment', to='dictionaries.state_degree', verbose_name='觉得自身健康状况如何'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='relatedfield_sports_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_preference_for_relatedfield_sports_preference_personal_health_assessment', to='dictionaries.sports_preference', verbose_name='运动偏好'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='relatedfield_drinking_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_for_relatedfield_drinking_frequency_personal_health_behavior_survey', to='dictionaries.frequency', verbose_name='饮酒频次'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='relatedfield_smoking_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_for_relatedfield_smoking_frequency_personal_health_behavior_survey', to='dictionaries.frequency', verbose_name='吸烟频次'),
        ),
        migrations.AlterField(
            model_name='physical_examination_athletic_ability',
            name='relatedfield_athletic_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_time_for_relatedfield_athletic_ability_physical_examination_athletic_ability', to='dictionaries.exercise_time', verbose_name='运动能力'),
        ),
        migrations.AlterField(
            model_name='physical_examination_hearing',
            name='relatedfield_left_ear_hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearing_for_relatedfield_left_ear_hearing_physical_examination_hearing', to='dictionaries.hearing', verbose_name='左耳听力'),
        ),
        migrations.AlterField(
            model_name='physical_examination_hearing',
            name='relatedfield_right_ear_hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearing_for_relatedfield_right_ear_hearing_physical_examination_hearing', to='dictionaries.hearing', verbose_name='右耳听力'),
        ),
        migrations.AlterField(
            model_name='physical_examination_oral_cavity',
            name='relatedfield_dentition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dentition_for_relatedfield_dentition_physical_examination_oral_cavity', to='dictionaries.dentition', verbose_name='齿列'),
        ),
        migrations.AlterField(
            model_name='physical_examination_oral_cavity',
            name='relatedfield_lips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lips_for_relatedfield_lips_physical_examination_oral_cavity', to='dictionaries.lips', verbose_name='口唇'),
        ),
        migrations.AlterField(
            model_name='physical_examination_oral_cavity',
            name='relatedfield_pharynx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharynx_for_relatedfield_pharynx_physical_examination_oral_cavity', to='dictionaries.pharynx', verbose_name='咽部'),
        ),
        migrations.AlterField(
            model_name='social_environment_assessment',
            name='relatedfield_is_the_living_environment_satisfactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_for_relatedfield_is_the_living_environment_satisfactory_social_environment_assessment', to='dictionaries.satisfaction', verbose_name='您对居住环境满意吗'),
        ),
        migrations.AlterField(
            model_name='social_environment_assessment',
            name='relatedfield_is_the_transportation_convenient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenience_for_relatedfield_is_the_transportation_convenient_social_environment_assessment', to='dictionaries.convenience', verbose_name='您所在的社区交通方便吗'),
        ),
    ]
