# Generated by Django 3.2.6 on 2021-08-30 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_auto_20210830_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_personal_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='家庭编号')),
                ('resident_file_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='居民档案号')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='出生日期')),
                ('nationality', models.CharField(blank=True, max_length=60, null=True, verbose_name='民族')),
                ('education', models.CharField(blank=True, max_length=60, null=True, verbose_name='文化程度')),
                ('occupational_status', models.CharField(blank=True, max_length=60, null=True, verbose_name='职业状况')),
                ('identification_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='身份证号码')),
                ('family_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='家庭地址')),
                ('contact_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话')),
                ('medical_ic_card_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='医疗ic卡号')),
                ('medical_expenses_burden', models.CharField(blank=True, max_length=60, null=True, verbose_name='医疗费用负担')),
                ('type_of_residence', models.CharField(blank=True, max_length=60, null=True, verbose_name='居住类型')),
                ('contract_signatory', models.CharField(blank=True, max_length=60, null=True, verbose_name='合同签约户')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '个人基本情况',
                'verbose_name_plural': '个人基本情况',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Doctor_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_role', models.CharField(blank=True, max_length=60, null=True, verbose_name='服务角色')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '医生登陆',
                'verbose_name_plural': '医生登陆',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Doctor_registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=60, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=60, null=True, verbose_name='年龄')),
                ('identification_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='身份证号码')),
                ('contact_information', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话')),
                ('contact_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系地址')),
                ('service_role', models.CharField(blank=True, max_length=60, null=True, verbose_name='服务角色')),
                ('practice_qualification', models.CharField(blank=True, max_length=60, null=True, verbose_name='执业资质')),
                ('password_setting', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码设置')),
                ('confirm_password', models.CharField(blank=True, max_length=60, null=True, verbose_name='确认密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '医生注册',
                'verbose_name_plural': '医生注册',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '用户登录',
                'verbose_name_plural': '用户登录',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='User_registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=60, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=60, null=True, verbose_name='年龄')),
                ('identification_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='身份证号码')),
                ('contact_information', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系方式')),
                ('contact_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系地址')),
                ('password_setting', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码设置')),
                ('confirm_password', models.CharField(blank=True, max_length=60, null=True, verbose_name='确认密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '用户注册表',
                'verbose_name_plural': '用户注册表',
                'ordering': [],
            },
        ),
    ]
