# Generated by Django 3.2.6 on 2022-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0002_auto_20220410_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsite',
            name='testicpc',
            field=models.ManyToManyField(to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
    ]
