# Generated by Django 3.2.6 on 2022-01-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('core', '0001_initial'),
        ('forms', '0002_remove_personal_adaptability_assessment_relatedfield_can_you_get_encouragement_and_support_from_fami'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_of_trauma',
            name='relatedfield_diseases_name',
        ),
        migrations.AddField(
            model_name='history_of_trauma',
            name='relatedfield_disease_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_disease_name_history_of_trauma', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称'),
        ),
        migrations.AddField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_can_you_get_encouragement_and_support_from_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_for_relatedfield_can_you_get_encouragement_and_support_from_family_personal_adaptability_assessment', to='dictionaries.frequency', verbose_name='是否能得到家人朋友的鼓励和支持'),
        ),
        migrations.CreateModel(
            name='Tang_hua_xue_hong_dan_bai_jian_cha_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberfield_tang_hua_xue_hong_dan_bai', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='糖化血红蛋白')),
                ('numberfield_tang_hua_xue_hong_dan_bai_standard_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='糖化血红蛋白标准值')),
                ('numberfield_tang_hua_xue_hong_dan_bai_up_limit', models.DecimalField(blank=True, decimal_places=2, default=6.0, max_digits=10, null=True, verbose_name='糖化血红蛋白上限')),
                ('numberfield_tang_hua_xue_hong_dan_bai_down_limit', models.DecimalField(blank=True, decimal_places=2, default=4.0, max_digits=10, null=True, verbose_name='糖化血红蛋白下限')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '糖化血红蛋白检查表',
                'verbose_name_plural': '糖化血红蛋白检查表',
            },
        ),
        migrations.CreateModel(
            name='Men_zhen_zhen_duan_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_disease_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_disease_name_men_zhen_zhen_duan_biao', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称')),
            ],
            options={
                'verbose_name': '门诊诊断表',
                'verbose_name_plural': '门诊诊断表',
            },
        ),
        migrations.CreateModel(
            name='Men_zhen_wen_zhen_diao_cha_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_men_zhen_wen_zhen_diao_cha_biao', to='icpc.icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '门诊问诊调查表',
                'verbose_name_plural': '门诊问诊调查表',
            },
        ),
        migrations.CreateModel(
            name='Kong_fu_xue_tang_jian_cha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberfield_kong_fu_xue_tang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='空腹血糖')),
                ('numberfield_kong_fu_xue_tang_standard_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='空腹血糖标准值')),
                ('numberfield_kong_fu_xue_tang_up_limit', models.DecimalField(blank=True, decimal_places=2, default=7.0, max_digits=10, null=True, verbose_name='空腹血糖上限')),
                ('numberfield_kong_fu_xue_tang_down_limit', models.DecimalField(blank=True, decimal_places=2, default=3.9, max_digits=10, null=True, verbose_name='空腹血糖下限')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '空腹血糖检查',
                'verbose_name_plural': '空腹血糖检查',
            },
        ),
    ]
