# Generated by Django 3.2.6 on 2022-01-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20220114_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_adaptability_assessment',
            name='relatedfield_can_you_get_encouragement_and_support_from_family',
        ),
    ]
