# Generated by Django 3.2.6 on 2021-11-30 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_ge_ren_ji_ben_xin_xi_diao_cha_1638065370_jiu_zhen_shi_jian_1638064039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ge_ren_ji_ben_xin_xi_diao_cha_1638065370',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 30, 9, 47, 1, 611254, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
    ]
