# Generated by Django 3.2.6 on 2022-04-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_testsite_testicpc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsite',
            old_name='testicpc',
            new_name='test_icpc',
        ),
    ]
