# Generated by Django 3.2.6 on 2021-11-30 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0004_alter_ge_ren_ji_ben_xin_xi_diao_cha_1638065370_jiu_zhen_shi_jian_1638064039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xing_ming_1638063956', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('dian_hua_1638063972', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('di_zhi_1638063979', models.CharField(blank=True, default='碧瑶', max_length=255, null=True, verbose_name='地址')),
                ('jiu_zhen_shi_jian_1638064039', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 30, 14, 43, 9, 254021, tzinfo=utc), null=True, verbose_name='就诊时间')),
                ('chu_sheng_ri_qi_1638064057', models.DateField(blank=True, default=datetime.date(2021, 11, 30), null=True, verbose_name='出生日期')),
                ('shen_gao_1638064084', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('shen_gao_1638064084_standard_value', models.IntegerField(blank=True, null=True, verbose_name='身高标准值')),
                ('shen_gao_1638064084_up_limit', models.IntegerField(blank=True, null=True, verbose_name='身高上限')),
                ('shen_gao_1638064084_down_limit', models.IntegerField(blank=True, null=True, verbose_name='身高下限')),
                ('ti_zhong_1638064102', models.IntegerField(default=60.0, verbose_name='体重')),
                ('ti_zhong_1638064102_standard_value', models.IntegerField(default=50.0, verbose_name='体重标准值')),
                ('ti_zhong_1638064102_up_limit', models.IntegerField(default=100.0, verbose_name='体重上限')),
                ('ti_zhong_1638064102_down_limit', models.IntegerField(default=30.0, verbose_name='体重下限')),
                ('xing_bie_1638064165', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('xue_xing_1638064329', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, 'A型'), (2, 'B型'), (3, 'O型'), (4, 'AB型')], default=0, verbose_name='血型')),
                ('ri_qi_1638065523', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('icpc_jian_cha_jie_guo_he_tong_ji_1638189070', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc10_test_results_and_statistics', verbose_name='ICPC检查结果和统计')),
                ('icpc_ping_gu_he_zhen_duan_1638282846', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='ICPC评估和诊断')),
            ],
            options={
                'verbose_name': '个人基本情况调查',
                'verbose_name_plural': '个人基本情况调查',
            },
        ),
        migrations.CreateModel(
            name='Ge_ren_ji_bing_shi_1638282939',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xing_ming_1638063956', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('ri_qi_1638065523', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('icpc_ping_gu_he_zhen_duan_1638282846', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='ICPC评估和诊断')),
            ],
            options={
                'verbose_name': '个人疾病史',
                'verbose_name_plural': '个人疾病史',
            },
        ),
        migrations.RemoveField(
            model_name='ji_bing_shi_1638065556',
            name='ICPC_zheng_zhuang_he_wen_ti_1638064906',
        ),
        migrations.DeleteModel(
            name='Ge_ren_ji_ben_xin_xi_diao_cha_1638065370',
        ),
        migrations.DeleteModel(
            name='Ji_bing_shi_1638065556',
        ),
    ]
