# Generated by Django 3.2.6 on 2022-04-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_testicpc_testsite_test_icpc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSite',
        ),
    ]
