# Generated by Django 3.2.6 on 2022-01-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_operation_checked_fields'),
        ('dictionaries', '0001_initial'),
        ('forms', '0004_remove_personal_adaptability_assessment_relatedfield_can_you_get_encouragement_and_support_from_fami'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yong_yao_chu_fang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_drug_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_list_for_relatedfield_drug_name_yong_yao_chu_fang', to='dictionaries.drug_list', verbose_name='药品名称')),
            ],
            options={
                'verbose_name': '用药处方',
                'verbose_name_plural': '用药处方',
            },
        ),
    ]
