# Generated by Django 3.2.6 on 2022-04-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_service_proc_serviceproc'),
        ('forms', '0005_delete_testsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='a3001',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3101',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3103',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3105',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3108',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3109',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3110',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a3502',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a5001',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a5002',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6201',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6202',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6203',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6204',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6205',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6206',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6207',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6208',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6209',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6210',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6211',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6212',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6213',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6214',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6215',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6216',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6217',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6218',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6219',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6220',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6501',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='a6502',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='ji_gou_qing_dan',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t3002',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t3003',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t3404',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t3405',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t4501',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t4502',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t4504',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t4505',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t6301',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='t9001',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='yao_pin_qing_dan',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='yong_yao_diao_cha_biao',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='z6201',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='z6205',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='z6230',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='z6233',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='z6261',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='zhi_yuan_biao',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3001',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3001_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3001',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3001_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3101',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3101_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3101',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3101_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3103',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3103_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3103',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3103_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3105',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3105_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3105',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3105_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3108',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3108_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3108',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3108_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3109',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3109_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3109',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3109_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3110',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3110_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3110',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3110_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a3502',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3502_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a3502',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3502_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a5001',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5001_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a5001',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5001_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a5002',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5002_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a5002',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5002_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6201',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6201_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6201',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6201_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6202',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6202_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6202',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6202_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6203',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6203_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6203',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6203_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6204',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6204_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6204',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6204_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6205',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6205_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6205',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6205_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6206',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6206_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6206',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6206_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6207',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6207_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6207',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6207_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6208',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6208_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6208',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6208_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6209',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6209_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6209',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6209_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6210',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6210_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6210',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6210_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6211',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6211_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6211',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6211_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6212',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6212_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6212',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6212_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6213',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6213_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6213',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6213_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6214',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6214_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6214',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6214_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6215',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6215_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6215',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6215_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6216',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6216_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6216',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6216_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6217',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6217_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6217',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6217_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6218',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6218_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6218',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6218_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6219',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6219_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6219',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6219_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6220',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6220_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6220',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6220_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6501',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6501_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6501',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6501_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6502_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6502_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='ji_gou_qing_dan',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ji_gou_qing_dan_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='ji_gou_qing_dan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ji_gou_qing_dan_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='physical_examination_athletic_ability',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_athletic_ability_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='physical_examination_athletic_ability',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_athletic_ability_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t3002',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3002_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t3002',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3002_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t3003',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3003_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t3003',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3003_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t3404',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3404_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t3404',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3404_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t3405',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3405_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t3405',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3405_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t4501',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4501_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t4501',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4501_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t4502',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4502_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t4502',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4502_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t4504',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4504_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t4504',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4504_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t4505',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4505_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t4505',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4505_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t6301_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t6301_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='yao_pin_qing_dan',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yao_pin_qing_dan_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='yao_pin_qing_dan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yao_pin_qing_dan_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='yong_yao_diao_cha_biao',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yong_yao_diao_cha_biao_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='yong_yao_diao_cha_biao',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yong_yao_diao_cha_biao_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='z6201',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6201_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='z6201',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6201_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='z6205',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6205_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='z6205',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6205_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='z6230',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6230_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='z6230',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6230_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='z6233',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6233_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='z6233',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6233_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='z6261',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6261_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='z6261',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6261_operator', to='core.customer', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='zhi_yuan_biao',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zhi_yuan_biao_creater', to='core.customer', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='zhi_yuan_biao',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zhi_yuan_biao_operator', to='core.customer', verbose_name='作业人员'),
        ),
    ]
