# Generated by Django 3.2.6 on 2021-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20211130_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ge_ren_ji_bing_shi_1638282939',
            name='icpc_ping_gu_he_zhen_duan_1638282846',
        ),
        migrations.DeleteModel(
            name='Ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
        ),
        migrations.DeleteModel(
            name='Ge_ren_ji_bing_shi_1638282939',
        ),
    ]
