# Generated by Django 3.2.6 on 2022-01-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0005_yong_yao_chu_fang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_of_hospital_self_report_survey',
            name='relatedfield_symptom_list',
        ),
        migrations.AddField(
            model_name='out_of_hospital_self_report_survey',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_out_of_hospital_self_report_survey', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
    ]
