# Generated by Django 3.2.6 on 2022-04-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220420_1133'),
        ('forms', '0006_auto_20220417_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a3001',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3001',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3001',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3001',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3001',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3101',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3101',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3101',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3101',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3101',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3103',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3103',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3103',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3103',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3103',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3105',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3105',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3105',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3105',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3105',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3108',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3108',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3108',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3108',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3108',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3109',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3109',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3109',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3109',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3109',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3110',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3110',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3110',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3110',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3110',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a3502',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a3502',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a3502',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a3502',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a3502',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a5001',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a5001',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a5001',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a5001',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a5001',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a5002',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a5002',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a5002',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a5002',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a5002',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6201',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6201',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6201',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6201',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6201',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6202',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6202',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6202',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6202',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6202',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6203',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6203',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6203',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6203',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6203',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6204',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6204',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6204',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6204',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6204',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6205',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6205',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6205',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6205',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6205',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6206',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6206',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6206',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6206',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6206',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6207',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6207',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6207',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6207',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6207',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6208',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6208',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6208',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6208',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6208',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6209',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6209',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6209',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6209',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6209',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6210',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6210',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6210',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6210',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6210',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6211',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6211',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6211',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6211',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6211',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6212',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6212',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6212',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6212',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6212',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6213',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6213',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6213',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6213',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6213',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6214',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6214',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6214',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6214',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6214',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6215',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6215',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6215',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6215',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6215',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6216',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6216',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6216',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6216',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6216',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6217',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6217',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6217',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6217',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6217',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6218',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6218',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6218',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6218',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6218',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6219',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6219',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6219',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6219',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6219',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6220',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6220',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6220',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6220',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6220',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6501',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6501',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6501',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6501',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6501',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='a6502',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='a6502',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='a6502',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='a6502',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='a6502',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='ji_gou_qing_dan',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='ji_gou_qing_dan',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='ji_gou_qing_dan',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ji_gou_qing_dan',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='ji_gou_qing_dan',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='physical_examination_athletic_ability',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='physical_examination_athletic_ability',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='physical_examination_athletic_ability',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='physical_examination_athletic_ability',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='physical_examination_athletic_ability',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t3002',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t3002',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t3002',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t3002',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t3002',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t3003',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t3003',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t3003',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t3003',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t3003',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t3404',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t3404',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t3404',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t3404',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t3404',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t3405',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t3405',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t3405',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t3405',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t3405',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t4501',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t4501',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t4501',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t4501',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t4501',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t4502',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t4502',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t4502',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t4502',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t4502',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t4504',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t4504',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t4504',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t4504',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t4504',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t4505',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t4505',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t4505',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t4505',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t4505',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t6301',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t6301',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t6301',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t6301',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t6301',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='t9001',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='t9001',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='t9001',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='t9001',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='t9001',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='yao_pin_qing_dan',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='yao_pin_qing_dan',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='yao_pin_qing_dan',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='yao_pin_qing_dan',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='yao_pin_qing_dan',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='yong_yao_diao_cha_biao',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='yong_yao_diao_cha_biao',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='yong_yao_diao_cha_biao',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='yong_yao_diao_cha_biao',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='yong_yao_diao_cha_biao',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='z6201',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='z6201',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='z6201',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='z6201',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='z6201',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='z6205',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='z6205',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='z6205',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='z6205',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='z6205',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='z6230',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='z6230',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='z6230',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='z6230',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='z6230',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='z6233',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='z6233',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='z6233',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='z6233',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='z6233',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='z6261',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='z6261',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='z6261',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='z6261',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='z6261',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='zhi_yuan_biao',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='zhi_yuan_biao',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='zhi_yuan_biao',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='zhi_yuan_biao',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='zhi_yuan_biao',
            name='update_time',
        ),
        migrations.AddField(
            model_name='a3001',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3001',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3001',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3001',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3101',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3101',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3101',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3101',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3103',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3103',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3103',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3103',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3105',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3105',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3105',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3105',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3108',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3108',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3108',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3108',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3109',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3109',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3109',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3109',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3110',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3110',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3110',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3110',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a3502',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a3502',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a3502',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a3502',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a5001',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a5001',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a5001',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a5001',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a5002',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a5002',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a5002',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a5002',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6201',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6201',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6201',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6201',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6202',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6202',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6202',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6202',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6203',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6203',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6203',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6203',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6204',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6204',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6204',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6204',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6205',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6205',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6205',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6205',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6206',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6206',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6206',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6206',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6207',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6207',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6207',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6207',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6208',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6208',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6208',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6208',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6209',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6209',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6209',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6209',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6210',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6210',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6210',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6210',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6211',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6211',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6211',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6211',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6212',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6212',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6212',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6212',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6213',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6213',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6213',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6213',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6214',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6214',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6214',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6214',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6215',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6215',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6215',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6215',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6216',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6216',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6216',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6216',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6217',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6217',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6217',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6217',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6218',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6218',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6218',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6218',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6219',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6219',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6219',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6219',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6220',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6220',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6220',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6220',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6501',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6501',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6501',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6501',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='a6502',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='a6502',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='a6502',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='a6502',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ji_gou_qing_dan',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='ji_gou_qing_dan',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='ji_gou_qing_dan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='ji_gou_qing_dan',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t3002',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t3002',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t3002',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t3002',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t3003',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t3003',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t3003',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t3003',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t3404',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t3404',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t3404',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t3404',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t3405',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t3405',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t3405',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t3405',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t4501',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t4501',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t4501',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t4501',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t4502',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t4502',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t4502',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t4502',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t4504',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t4504',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t4504',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t4504',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t4505',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t4505',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t4505',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t4505',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t6301',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t6301',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t6301',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t6301',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='t9001',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='t9001',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='t9001',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='t9001',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='yao_pin_qing_dan',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='yao_pin_qing_dan',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='yao_pin_qing_dan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='yao_pin_qing_dan',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='yong_yao_diao_cha_biao',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='yong_yao_diao_cha_biao',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='yong_yao_diao_cha_biao',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='yong_yao_diao_cha_biao',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='z6201',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='z6201',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='z6201',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='z6201',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='z6205',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='z6205',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='z6205',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='z6205',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='z6230',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='z6230',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='z6230',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='z6230',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='z6233',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='z6233',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='z6233',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='z6233',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='z6261',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='z6261',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='z6261',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='z6261',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='zhi_yuan_biao',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='zhi_yuan_biao',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='zhi_yuan_biao',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='zhi_yuan_biao',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='a3001',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3001_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3001',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3001_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3101',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3101_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3101',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3101_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3103',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3103_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3103',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3103_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3105',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3105_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3105',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3105_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3108',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3108_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3108',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3108_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3109',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3109_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3109',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3109_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3110',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3110_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3110',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3110_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a3502',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3502_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3502',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3502_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a5001',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5001_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a5001',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5001_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a5002',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5002_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a5002',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a5002_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6201',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6201_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6201',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6201_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6202',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6202_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6202',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6202_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6203',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6203_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6203',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6203_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6204',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6204_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6204',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6204_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6205',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6205_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6205',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6205_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6206',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6206_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6206',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6206_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6207',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6207_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6207',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6207_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6208',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6208_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6208',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6208_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6209',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6209_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6209',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6209_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6210',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6210_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6210',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6210_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6211',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6211_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6211',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6211_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6212',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6212_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6212',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6212_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6213',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6213_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6213',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6213_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6214',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6214_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6214',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6214_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6215',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6215_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6215',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6215_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6216',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6216_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6216',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6216_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6217',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6217_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6217',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6217_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6218',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6218_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6218',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6218_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6219',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6219_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6219',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6219_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6220',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6220_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6220',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6220_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6501',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6501_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6501',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6501_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6502_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6502_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='ji_gou_qing_dan',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ji_gou_qing_dan_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='ji_gou_qing_dan',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ji_gou_qing_dan_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='physical_examination_athletic_ability',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_athletic_ability_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='physical_examination_athletic_ability',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_athletic_ability_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t3002',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3002_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t3002',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3002_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t3003',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3003_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t3003',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3003_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t3404',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3404_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t3404',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3404_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t3405',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3405_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t3405',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3405_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t4501',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4501_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t4501',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4501_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t4502',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4502_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t4502',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4502_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t4504',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4504_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t4504',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4504_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t4505',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4505_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t4505',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4505_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t6301_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t6301_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='yao_pin_qing_dan',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yao_pin_qing_dan_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='yao_pin_qing_dan',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yao_pin_qing_dan_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='yong_yao_diao_cha_biao',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yong_yao_diao_cha_biao_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='yong_yao_diao_cha_biao',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yong_yao_diao_cha_biao_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='z6201',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6201_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='z6201',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6201_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='z6205',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6205_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='z6205',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6205_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='z6230',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6230_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='z6230',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6230_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='z6233',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6233_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='z6233',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6233_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='z6261',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6261_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='z6261',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z6261_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='zhi_yuan_biao',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zhi_yuan_biao_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='zhi_yuan_biao',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zhi_yuan_biao_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
    ]
