# Generated by Django 3.2.6 on 2022-01-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('forms', '0006_auto_20220119_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergies_history',
            name='relatedfield_drug_name',
        ),
        migrations.AddField(
            model_name='allergies_history',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(related_name='drug_list_for_relatedfield_drug_name_allergies_history', to='dictionaries.Drug_list', verbose_name='药品名称'),
        ),
        migrations.RemoveField(
            model_name='basic_personal_information',
            name='relatedfield_medical_expenses_burden',
        ),
        migrations.AddField(
            model_name='basic_personal_information',
            name='relatedfield_medical_expenses_burden',
            field=models.ManyToManyField(related_name='medical_expenses_burden_for_relatedfield_medical_expenses_burden_basic_personal_information', to='dictionaries.Medical_expenses_burden', verbose_name='医疗费用负担'),
        ),
        migrations.RemoveField(
            model_name='doctor_registry',
            name='relatedfield_service_role',
        ),
        migrations.AddField(
            model_name='doctor_registry',
            name='relatedfield_service_role',
            field=models.ManyToManyField(related_name='service_role_for_relatedfield_service_role_doctor_registry', to='dictionaries.Service_role', verbose_name='服务角色'),
        ),
        migrations.RemoveField(
            model_name='major_life_events',
            name='relatedfield_major_life',
        ),
        migrations.AddField(
            model_name='major_life_events',
            name='relatedfield_major_life',
            field=models.ManyToManyField(related_name='life_event_for_relatedfield_major_life_major_life_events', to='dictionaries.Life_event', verbose_name='生活事件'),
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha_biao',
            name='relatedfield_symptom_list',
        ),
        migrations.AddField(
            model_name='men_zhen_wen_zhen_diao_cha_biao',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_men_zhen_wen_zhen_diao_cha_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.RemoveField(
            model_name='personal_health_assessment',
            name='relatedfield_have_any_recent_symptoms_of_physical_discomfort',
        ),
        migrations.AddField(
            model_name='personal_health_assessment',
            name='relatedfield_have_any_recent_symptoms_of_physical_discomfort',
            field=models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_have_any_recent_symptoms_of_physical_discomfort_personal_health_assessment', to='icpc.Icpc3_symptoms_and_problems', verbose_name='近来有无身体不适症状'),
        ),
        migrations.RemoveField(
            model_name='yong_yao_chu_fang',
            name='relatedfield_drug_name',
        ),
        migrations.AddField(
            model_name='yong_yao_chu_fang',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(related_name='drug_list_for_relatedfield_drug_name_yong_yao_chu_fang', to='dictionaries.Drug_list', verbose_name='药品名称'),
        ),
    ]
