# Generated by Django 3.2.6 on 2021-09-05 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0006_auto_20210831_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_role', models.CharField(blank=True, max_length=60, null=True, verbose_name='服务角色')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '医生登陆',
                'verbose_name_plural': '医生登陆',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Doctor_registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=60, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=60, null=True, verbose_name='年龄')),
                ('identification_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='身份证号码')),
                ('contact_information', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话')),
                ('contact_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系地址')),
                ('service_role', models.CharField(blank=True, choices=[(0, '中医师'), (1, '护士'), (2, '医生'), (3, '质量管理'), (4, '医生助理'), (5, '健康管理师'), (6, '化验'), (7, '影像医师'), (8, '康复理疗师'), (9, '公卫'), (10, '药士'), (11, '药剂师'), (12, '管理者')], max_length=60, null=True, verbose_name='服务角色')),
                ('practice_qualification', models.CharField(blank=True, max_length=60, null=True, verbose_name='执业资质')),
                ('password_setting', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码设置')),
                ('confirm_password', models.CharField(blank=True, max_length=60, null=True, verbose_name='确认密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '医生注册',
                'verbose_name_plural': '医生注册',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '用户登录',
                'verbose_name_plural': '用户登录',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='User_registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=60, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=60, null=True, verbose_name='年龄')),
                ('identification_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='身份证号码')),
                ('contact_information', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系方式')),
                ('contact_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系地址')),
                ('password_setting', models.CharField(blank=True, max_length=60, null=True, verbose_name='密码设置')),
                ('confirm_password', models.CharField(blank=True, max_length=60, null=True, verbose_name='确认密码')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '用户注册表',
                'verbose_name_plural': '用户注册表',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='History_of_infectious_diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('diseases', models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='病名')),
            ],
            options={
                'verbose_name': '遗传病史',
                'verbose_name_plural': '遗传病史',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Family_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_relationship', models.CharField(blank=True, choices=[(0, '户主'), (1, '配偶'), (2, '父母'), (3, '孙子女'), (4, '祖父母'), (5, '其他成员'), (6, '兄弟姐妹'), (7, '子女')], max_length=60, null=True, verbose_name='家庭成员关系')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('diseases', models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='病名')),
            ],
            options={
                'verbose_name': '家族病史',
                'verbose_name_plural': '家族病史',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Basic_personal_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_relationship', models.CharField(blank=True, choices=[(0, '户主'), (1, '配偶'), (2, '父母'), (3, '孙子女'), (4, '祖父母'), (5, '其他成员'), (6, '兄弟姐妹'), (7, '子女')], max_length=60, null=True, verbose_name='家庭成员关系')),
                ('resident_file_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='居民档案号')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[(0, '男'), (1, '女')], max_length=60, null=True, verbose_name='性别')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='出生日期')),
                ('nationality', models.CharField(blank=True, choices=[(0, '少数民族'), (1, '汉族')], max_length=60, null=True, verbose_name='民族')),
                ('marital_status', models.CharField(blank=True, choices=[(0, '已婚'), (1, '未婚'), (2, '丧偶'), (3, '离异')], max_length=60, null=True, verbose_name='婚姻状况')),
                ('education', models.CharField(blank=True, choices=[(0, '硕士'), (1, '文盲或半文盲'), (2, '中专技校'), (3, '小学'), (4, '本科'), (5, '高中'), (6, '初中'), (7, '博士'), (8, '大专')], max_length=60, null=True, verbose_name='文化程度')),
                ('occupational_status', models.CharField(blank=True, choices=[(0, '退休'), (1, '失业'), (2, '在职')], max_length=60, null=True, verbose_name='职业状况')),
                ('identification_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='身份证号码')),
                ('family_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='家庭地址')),
                ('contact_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话')),
                ('medical_ic_card_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='医疗ic卡号')),
                ('medical_expenses_burden', models.CharField(blank=True, choices=[(0, '公费'), (1, '城镇居民医疗保险'), (2, '自费'), (3, '商业保险'), (4, '贫困救助'), (5, '职工医疗保险')], max_length=60, null=True, verbose_name='医疗费用负担')),
                ('type_of_residence', models.CharField(blank=True, choices=[(0, '非常住'), (1, '常住')], max_length=60, null=True, verbose_name='居住类型')),
                ('blood_type', models.CharField(blank=True, choices=[(0, 'AB+型'), (1, 'O+型'), (2, 'B+型'), (3, 'O型'), (4, 'A型'), (5, 'B-型'), (6, 'A-型'), (7, 'AB-型'), (8, 'B型'), (9, 'AB型'), (10, 'A+型'), (11, 'O-型'), (12, '不详')], max_length=60, null=True, verbose_name='血型')),
                ('contract_signatory', models.CharField(blank=True, choices=[(0, '是'), (1, '否')], max_length=60, null=True, verbose_name='合同签约户')),
                ('signed_family_doctor', models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='签约家庭医生')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('family_id', models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc1_register_logins', verbose_name='家庭编号')),
            ],
            options={
                'verbose_name': '个人基本情况',
                'verbose_name_plural': '个人基本情况',
                'ordering': [],
            },
        ),
    ]
