# Generated by Django 3.2.6 on 2021-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_basic_personal_information_doctor_login_doctor_registry_family_history_history_of_infectious_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_personal_information',
            name='blood_type',
            field=models.CharField(blank=True, choices=[(0, 'AB+型'), (1, 'B+型'), (2, 'O型'), (3, 'A型'), (4, 'A-型'), (5, 'AB-型'), (6, 'B型'), (7, 'AB型'), (8, 'O-型'), (9, 'O+型'), (10, 'B-型'), (11, 'A+型'), (12, '不详')], max_length=60, null=True, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='education',
            field=models.CharField(blank=True, choices=[(0, '中专技校'), (1, '小学'), (2, '初中'), (3, '硕士'), (4, '文盲或半文盲'), (5, '本科'), (6, '高中'), (7, '博士'), (8, '大专')], max_length=60, null=True, verbose_name='文化程度'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[(0, '户主'), (1, '配偶'), (2, '父母'), (3, '孙子女'), (4, '兄弟姐妹'), (5, '子女'), (6, '祖父母'), (7, '其他成员')], max_length=60, null=True, verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, '女'), (1, '男')], max_length=60, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(0, '未婚'), (1, '丧偶'), (2, '离异'), (3, '已婚')], max_length=60, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='medical_expenses_burden',
            field=models.CharField(blank=True, choices=[(0, '公费'), (1, '城镇居民医疗保险'), (2, '职工医疗保险'), (3, '自费'), (4, '商业保险'), (5, '贫困救助')], max_length=60, null=True, verbose_name='医疗费用负担'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='type_of_residence',
            field=models.CharField(blank=True, choices=[(0, '常住'), (1, '非常住')], max_length=60, null=True, verbose_name='居住类型'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='service_role',
            field=models.CharField(blank=True, choices=[(0, '护士'), (1, '医生助理'), (2, '化验'), (3, '康复理疗师'), (4, '药士'), (5, '中医师'), (6, '医生'), (7, '质量管理'), (8, '健康管理师'), (9, '影像医师'), (10, '公卫'), (11, '药剂师'), (12, '管理者')], max_length=60, null=True, verbose_name='服务角色'),
        ),
        migrations.AlterField(
            model_name='family_history',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[(0, '户主'), (1, '配偶'), (2, '父母'), (3, '孙子女'), (4, '兄弟姐妹'), (5, '子女'), (6, '祖父母'), (7, '其他成员')], max_length=60, null=True, verbose_name='家庭成员关系'),
        ),
    ]
