# Generated by Django 3.2.6 on 2022-02-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0003_auto_20220212_2340'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entities', '0001_initial'),
        ('core', '0011_auto_20220212_2320'),
        ('forms', '0007_auto_20220119_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diao_cha_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_chang_yong_zheng_zhuang', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_chang_yong_zheng_zhuang_diao_cha_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='常用症状')),
                ('relatedfield_symptom_list', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_diao_cha_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '常用调查表',
                'verbose_name_plural': '常用调查表',
            },
        ),
        migrations.CreateModel(
            name='Men_zhen_yi_sheng_wen_zhen_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_men_zhen_yi_sheng_wen_zhen_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '门诊医生问诊表',
                'verbose_name_plural': '门诊医生问诊表',
            },
        ),
        migrations.CreateModel(
            name='Que_ren_dan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolfield_yu_yue_que_ren', models.BooleanField(blank=True, default=True, null=True, verbose_name='签到确认')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '确认单',
                'verbose_name_plural': '确认单',
            },
        ),
        migrations.CreateModel(
            name='Tang_niao_bing_zhen_duan_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_disease_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_disease_name_tang_niao_bing_zhen_duan_biao', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称')),
            ],
            options={
                'verbose_name': '糖尿病诊断表',
                'verbose_name_plural': '糖尿病诊断表',
            },
        ),
        migrations.CreateModel(
            name='Tang_niao_bing_zhuan_yong_wen_zhen_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_tang_niao_bing_zhuan_yong_wen_zhen_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '糖尿病专用问诊表',
                'verbose_name_plural': '糖尿病专用问诊表',
            },
        ),
        migrations.CreateModel(
            name='Xue_ya_jian_ce_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberfield_systolic_blood_pressure', models.IntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('numberfield_systolic_blood_pressure_standard_value', models.IntegerField(blank=True, null=True, verbose_name='收缩压标准值')),
                ('numberfield_systolic_blood_pressure_up_limit', models.IntegerField(blank=True, default=139.0, null=True, verbose_name='收缩压上限')),
                ('numberfield_systolic_blood_pressure_down_limit', models.IntegerField(blank=True, default=90.0, null=True, verbose_name='收缩压下限')),
                ('numberfield_diastolic_blood_pressure', models.IntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('numberfield_diastolic_blood_pressure_standard_value', models.IntegerField(blank=True, null=True, verbose_name='舒张压标准值')),
                ('numberfield_diastolic_blood_pressure_up_limit', models.IntegerField(blank=True, default=89.0, null=True, verbose_name='舒张压上限')),
                ('numberfield_diastolic_blood_pressure_down_limit', models.IntegerField(blank=True, default=60.0, null=True, verbose_name='舒张压下限')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '血压监测表',
                'verbose_name_plural': '血压监测表',
            },
        ),
        migrations.CreateModel(
            name='Yong_yao_diao_cha_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_yong_yao_ji_liang', models.CharField(blank=True, max_length=255, null=True, verbose_name='用药剂量')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_drug_name', models.ManyToManyField(related_name='medicine_for_relatedfield_drug_name_yong_yao_diao_cha_biao', to='entities.Medicine', verbose_name='药品名称')),
            ],
            options={
                'verbose_name': '用药调查表',
                'verbose_name_plural': '用药调查表',
            },
        ),
        migrations.CreateModel(
            name='Yong_yao_ti_xing_dan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolfield_shi_fou_ji_xu_shi_yong', models.BooleanField(blank=True, null=True, verbose_name='是否继续使用')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '用药提醒单',
                'verbose_name_plural': '用药提醒单',
            },
        ),
        migrations.CreateModel(
            name='Yu_yue_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_service_role', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务角色')),
                ('datetimefield_ri_qi_shi_jian', models.DateTimeField(blank=True, null=True, verbose_name='日期时间')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '预约单',
                'verbose_name_plural': '预约单',
            },
        ),
        migrations.CreateModel(
            name='Yuan_nei_fu_zhu_wen_zhen_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_yuan_nei_fu_zhu_wen_zhen_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '院内辅助问诊表',
                'verbose_name_plural': '院内辅助问诊表',
            },
        ),
        migrations.CreateModel(
            name='Yuan_qian_fu_zhu_wen_zhen_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_yuan_qian_fu_zhu_wen_zhen_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '院前辅助问诊表',
                'verbose_name_plural': '院前辅助问诊表',
            },
        ),
        migrations.CreateModel(
            name='Yuan_wai_zi_xun_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ManyToManyField(related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_yuan_wai_zi_xun_biao', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '院外咨询表',
                'verbose_name_plural': '院外咨询表',
            },
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha_biao',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha_biao',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha_biao',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='men_zhen_wen_zhen_diao_cha_biao',
            name='relatedfield_symptom_list',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan_biao',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan_biao',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan_biao',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='men_zhen_zhen_duan_biao',
            name='relatedfield_disease_name',
        ),
        migrations.RemoveField(
            model_name='out_of_hospital_self_report_survey',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='out_of_hospital_self_report_survey',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='out_of_hospital_self_report_survey',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='out_of_hospital_self_report_survey',
            name='relatedfield_symptom_list',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='boolfield_shi_fou_you_man_xing_ji_bing',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否有慢性疾病'),
        ),
        migrations.AlterField(
            model_name='allergies_history',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(related_name='medicine_for_relatedfield_drug_name_allergies_history', to='entities.Medicine', verbose_name='药品名称'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='relatedfield_signed_family_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_relatedfield_signed_family_doctor_basic_personal_information', to='core.staff', verbose_name='签约家庭医生'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='relatedfield_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_for_relatedfield_affiliation_doctor_registry', to='entities.institution', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='relatedfield_service_role',
            field=models.ManyToManyField(related_name='group_for_relatedfield_service_role_doctor_registry', to='auth.Group', verbose_name='服务角色'),
        ),
        migrations.AlterField(
            model_name='yong_yao_chu_fang',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(related_name='medicine_for_relatedfield_drug_name_yong_yao_chu_fang', to='entities.Medicine', verbose_name='药品名称'),
        ),
        migrations.DeleteModel(
            name='Blood_pressure_monitoring',
        ),
        migrations.DeleteModel(
            name='Men_zhen_wen_zhen_diao_cha_biao',
        ),
        migrations.DeleteModel(
            name='Men_zhen_zhen_duan_biao',
        ),
        migrations.DeleteModel(
            name='Out_of_hospital_self_report_survey',
        ),
    ]
