# Generated by Django 3.2.6 on 2022-04-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220420_1133'),
        ('forms', '0007_auto_20220420_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z6205',
            name='relatedfield_service_role',
            field=models.ManyToManyField(related_name='role_for_relatedfield_service_role_Z6205', to='core.Role', verbose_name='服务角色'),
        ),
    ]
