# Generated by Django 3.2.6 on 2021-12-01 02:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0007_ge_ren_ji_ben_qing_kuang_diao_cha_1638282909_ge_ren_ji_bing_shi_1638282939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
            name='chu_sheng_ri_qi_1638064057',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 1), null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 2, 58, 43, 739144, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
        migrations.CreateModel(
            name='Test_1638327253',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xing_ming_1638063956', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('dian_hua_1638063972', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('di_zhi_1638063979', models.CharField(blank=True, default='碧瑶', max_length=255, null=True, verbose_name='地址')),
                ('jiu_zhen_shi_jian_1638064039', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 2, 58, 43, 740144, tzinfo=utc), null=True, verbose_name='就诊时间')),
                ('chu_sheng_ri_qi_1638064057', models.DateField(blank=True, default=datetime.date(2021, 12, 1), null=True, verbose_name='出生日期')),
                ('shen_gao_1638064084', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('shen_gao_1638064084_standard_value', models.IntegerField(blank=True, null=True, verbose_name='身高标准值')),
                ('shen_gao_1638064084_up_limit', models.IntegerField(blank=True, null=True, verbose_name='身高上限')),
                ('shen_gao_1638064084_down_limit', models.IntegerField(blank=True, null=True, verbose_name='身高下限')),
                ('ti_zhong_1638064102', models.IntegerField(default=60.0, verbose_name='体重')),
                ('ti_zhong_1638064102_standard_value', models.IntegerField(default=50.0, verbose_name='体重标准值')),
                ('ti_zhong_1638064102_up_limit', models.IntegerField(default=100.0, verbose_name='体重上限')),
                ('ti_zhong_1638064102_down_limit', models.IntegerField(default=30.0, verbose_name='体重下限')),
                ('xing_bie_1638064165', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('xue_xing_1638064329', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, 'A型'), (2, 'B型'), (3, 'O型'), (4, 'AB型')], default=0, verbose_name='血型')),
                ('ri_qi_1638065523', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('ICPC_zheng_zhuang_he_wen_ti_1638064906', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc3_symptoms_and_problems', verbose_name='ICPC症状和问题')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'test',
            },
        ),
    ]
