# Generated by Django 3.2.6 on 2021-10-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20211003_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_personal_information',
            name='family_id',
        ),
        migrations.DeleteModel(
            name='Doctor_login',
        ),
        migrations.DeleteModel(
            name='Doctor_registry',
        ),
        migrations.RemoveField(
            model_name='family_history',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='history_of_infectious_diseases',
            name='diseases',
        ),
        migrations.DeleteModel(
            name='User_login',
        ),
        migrations.DeleteModel(
            name='User_registry',
        ),
        migrations.DeleteModel(
            name='Basic_personal_information',
        ),
        migrations.DeleteModel(
            name='Family_history',
        ),
        migrations.DeleteModel(
            name='History_of_infectious_diseases',
        ),
    ]
