# Generated by Django 3.2.6 on 2021-12-01 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20211201_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_auto_migrate_1638328554',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xing_ming_1638063956', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('dian_hua_1638063972', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('di_zhi_1638063979', models.CharField(blank=True, default='碧瑶', max_length=255, null=True, verbose_name='地址')),
                ('jiu_zhen_shi_jian_1638064039', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 3, 16, 10, 833976, tzinfo=utc), null=True, verbose_name='就诊时间')),
                ('chu_sheng_ri_qi_1638064057', models.DateField(blank=True, default=datetime.date(2021, 12, 1), null=True, verbose_name='出生日期')),
                ('shen_gao_1638064084', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('shen_gao_1638064084_standard_value', models.IntegerField(blank=True, null=True, verbose_name='身高标准值')),
                ('shen_gao_1638064084_up_limit', models.IntegerField(blank=True, null=True, verbose_name='身高上限')),
                ('shen_gao_1638064084_down_limit', models.IntegerField(blank=True, null=True, verbose_name='身高下限')),
            ],
            options={
                'verbose_name': 'test_auto_migrate',
                'verbose_name_plural': 'test_auto_migrate',
            },
        ),
        migrations.AlterField(
            model_name='ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 3, 16, 10, 831977, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
        migrations.AlterField(
            model_name='test_1638327253',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 3, 16, 10, 832974, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
    ]
