# Generated by Django 3.2.6 on 2021-10-09 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0010_allergies_history_basic_personal_information_doctor_login_doctor_registry_family_survey_history_of_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_personal_information',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='basic_personal_information',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uid', to=settings.AUTH_USER_MODEL, verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='family_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_survey_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='family_survey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_survey_uid', to=settings.AUTH_USER_MODEL, verbose_name='作业人员'),
        ),
    ]
