# Generated by Django 3.2.6 on 2021-12-01 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20211201_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 3, 17, 20, 309271, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
        migrations.AlterField(
            model_name='test_1638327253',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 3, 17, 20, 311277, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
        migrations.AlterField(
            model_name='test_auto_migrate_1638328554',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 3, 17, 20, 312556, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
    ]
