# Generated by Django 3.2.6 on 2021-10-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20211009_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergies_history',
        ),
        migrations.RemoveField(
            model_name='basic_personal_information',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='basic_personal_information',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='basic_personal_information',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor_login',
        ),
        migrations.DeleteModel(
            name='Doctor_registry',
        ),
        migrations.RemoveField(
            model_name='family_survey',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='family_survey',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='family_survey',
            name='user',
        ),
        migrations.DeleteModel(
            name='History_of_blood_transfusion',
        ),
        migrations.RemoveField(
            model_name='history_of_infectious_diseases',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='history_of_surgery',
            name='name_of_operation',
        ),
        migrations.RemoveField(
            model_name='history_of_trauma',
            name='diseases_name',
        ),
        migrations.DeleteModel(
            name='Major_life_events',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='disease_name',
        ),
        migrations.DeleteModel(
            name='Out_of_hospital_self_report_survey',
        ),
        migrations.DeleteModel(
            name='Personal_adaptability_assessment',
        ),
        migrations.DeleteModel(
            name='Personal_comprehensive_psychological_quality_survey',
        ),
        migrations.DeleteModel(
            name='Personal_health_assessment',
        ),
        migrations.DeleteModel(
            name='Personal_health_behavior_survey',
        ),
        migrations.DeleteModel(
            name='Social_environment_assessment',
        ),
        migrations.DeleteModel(
            name='User_login',
        ),
        migrations.DeleteModel(
            name='User_registry',
        ),
        migrations.DeleteModel(
            name='Basic_personal_information',
        ),
        migrations.DeleteModel(
            name='Family_survey',
        ),
        migrations.DeleteModel(
            name='History_of_infectious_diseases',
        ),
        migrations.DeleteModel(
            name='History_of_surgery',
        ),
        migrations.DeleteModel(
            name='History_of_trauma',
        ),
        migrations.DeleteModel(
            name='Medical_history',
        ),
    ]
