# Generated by Django 3.2.6 on 2021-10-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_allergies_history_basic_personal_information_doctor_login_doctor_registry_family_survey_history_of_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_personal_information',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('0', 'AB+型'), ('1', 'B+型'), ('2', 'O型'), ('3', 'A型'), ('4', 'A-型'), ('5', 'AB-型'), ('6', 'B型'), ('7', 'AB型'), ('8', 'O-型'), ('9', 'O+型'), ('10', 'B-型'), ('11', 'A+型'), ('12', '不详')], max_length=60, null=True, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='contract_signatory',
            field=models.CharField(blank=True, choices=[('0', '是'), ('1', '否')], max_length=60, null=True, verbose_name='合同签约户'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='education',
            field=models.CharField(blank=True, choices=[('0', '中专技校'), ('1', '小学'), ('2', '初中'), ('3', '硕士'), ('4', '文盲或半文盲'), ('5', '本科'), ('6', '高中'), ('7', '博士'), ('8', '大专')], max_length=60, null=True, verbose_name='文化程度'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[('0', '户主'), ('1', '配偶'), ('2', '父母'), ('3', '孙子女'), ('4', '兄弟姐妹'), ('5', '子女'), ('6', '祖父母'), ('7', '其他成员')], max_length=60, null=True, verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=60, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('0', '未婚'), ('1', '丧偶'), ('2', '离异'), ('3', '已婚')], max_length=60, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='medical_expenses_burden',
            field=models.CharField(blank=True, choices=[('0', '公费'), ('1', '城镇居民医疗保险'), ('2', '职工医疗保险'), ('3', '自费'), ('4', '商业保险'), ('5', '贫困救助')], max_length=60, null=True, verbose_name='医疗费用负担'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='nationality',
            field=models.CharField(blank=True, choices=[('0', '少数民族'), ('1', '汉族')], max_length=60, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='occupational_status',
            field=models.CharField(blank=True, choices=[('0', '退休'), ('1', '失业'), ('2', '在职')], max_length=60, null=True, verbose_name='职业状况'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='type_of_residence',
            field=models.CharField(blank=True, choices=[('0', '常住'), ('1', '非常住')], max_length=60, null=True, verbose_name='居住类型'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='service_role',
            field=models.CharField(blank=True, choices=[('0', '护士'), ('1', '医生助理'), ('2', '化验'), ('3', '康复理疗师'), ('4', '药士'), ('5', '中医师'), ('6', '医生'), ('7', '质量管理'), ('8', '健康管理师'), ('9', '影像医师'), ('10', '公卫'), ('11', '药剂师'), ('12', '管理者')], max_length=60, null=True, verbose_name='服务角色'),
        ),
        migrations.AlterField(
            model_name='family_survey',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[('0', '户主'), ('1', '配偶'), ('2', '父母'), ('3', '孙子女'), ('4', '兄弟姐妹'), ('5', '子女'), ('6', '祖父母'), ('7', '其他成员')], max_length=60, null=True, verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='history_of_infectious_diseases',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[('0', '户主'), ('1', '配偶'), ('2', '父母'), ('3', '孙子女'), ('4', '兄弟姐妹'), ('5', '子女'), ('6', '祖父母'), ('7', '其他成员')], max_length=60, null=True, verbose_name='家庭成员关系'),
        ),
        migrations.AlterField(
            model_name='history_of_trauma',
            name='choose',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='选择'),
        ),
        migrations.AlterField(
            model_name='major_life_events',
            name='major_life',
            field=models.CharField(blank=True, choices=[('0', '子女死亡'), ('1', '离婚'), ('2', '结婚'), ('3', '父母死亡'), ('4', '失业'), ('5', '恋爱'), ('6', '生子'), ('7', '丧偶'), ('8', '家属病重')], max_length=60, null=True, verbose_name='生活事件'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='are_you_satisfied_with_the_job',
            field=models.CharField(blank=True, choices=[('0', '既非满意也非不满意'), ('1', '不满意'), ('2', '很不满意'), ('3', '很满意'), ('4', '满意')], max_length=60, null=True, verbose_name='对目前生活和工作满意吗'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='do_you_feel_pressured_at_work',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='是否感觉到工作压力大'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='do_you_often_work_overtime',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='是否经常加班'),
        ),
        migrations.AlterField(
            model_name='personal_comprehensive_psychological_quality_survey',
            name='is_life_fun',
            field=models.CharField(blank=True, choices=[('0', '从不'), ('1', '偶尔'), ('2', '经常')], max_length=60, null=True, verbose_name='您觉得生活有乐趣吗'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='do_you_feel_healthy',
            field=models.CharField(blank=True, choices=[('0', '不困难'), ('1', '非常糟'), ('2', '一般'), ('3', '非常好'), ('4', '很难'), ('5', '有一定影响'), ('6', '不太好'), ('7', '不适合'), ('8', '很少有'), ('9', '还不错'), ('10', '比较容易'), ('11', '非常不方便'), ('12', '很适合'), ('13', '很不合适'), ('14', '非常方便'), ('15', '无影响'), ('16', '根本没有'), ('17', '比较有'), ('18', '不方便'), ('19', '有点难'), ('20', '适合'), ('21', '很容易'), ('22', '不太影响'), ('23', '轻'), ('24', '极有'), ('25', '中'), ('26', '比较方便'), ('27', '有极大影响'), ('28', '重')], max_length=60, null=True, verbose_name='觉得自己身体健康吗'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='do_you_smoke',
            field=models.CharField(blank=True, choices=[('0', '从不'), ('1', '偶尔'), ('2', '经常')], max_length=60, null=True, verbose_name='是否吸烟'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='drinking_frequency',
            field=models.CharField(blank=True, choices=[('0', '从不'), ('1', '偶尔'), ('2', '经常')], max_length=60, null=True, verbose_name='饮酒频次'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='insomnia',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='有无失眠情况'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='is_the_diet_proportion_healthy',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='饮食比例是否健康'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='is_the_diet_regular',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='饮食是否规律'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='smoking_frequency',
            field=models.CharField(blank=True, choices=[('0', '从不'), ('1', '偶尔'), ('2', '经常')], max_length=60, null=True, verbose_name='吸烟频次'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='whether_the_bowel_movements_are_regular',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='大便是否规律'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='whether_to_drink_alcohol',
            field=models.CharField(blank=True, choices=[('0', '不确定'), ('1', '是'), ('2', '否'), ('3', '无'), ('4', '有')], max_length=60, null=True, verbose_name='是否饮酒'),
        ),
        migrations.AlterField(
            model_name='social_environment_assessment',
            name='is_the_living_environment_satisfactory',
            field=models.CharField(blank=True, choices=[('0', '既非满意也非不满意'), ('1', '不满意'), ('2', '很不满意'), ('3', '很满意'), ('4', '满意')], max_length=60, null=True, verbose_name='您对居住环境满意吗'),
        ),
        migrations.AlterField(
            model_name='social_environment_assessment',
            name='is_the_transportation_convenient',
            field=models.CharField(blank=True, choices=[('0', '不困难'), ('1', '非常糟'), ('2', '一般'), ('3', '非常好'), ('4', '很难'), ('5', '有一定影响'), ('6', '不太好'), ('7', '不适合'), ('8', '很少有'), ('9', '还不错'), ('10', '比较容易'), ('11', '非常不方便'), ('12', '很适合'), ('13', '很不合适'), ('14', '非常方便'), ('15', '无影响'), ('16', '根本没有'), ('17', '比较有'), ('18', '不方便'), ('19', '有点难'), ('20', '适合'), ('21', '很容易'), ('22', '不太影响'), ('23', '轻'), ('24', '极有'), ('25', '中'), ('26', '比较方便'), ('27', '有极大影响'), ('28', '重')], max_length=60, null=True, verbose_name='您所在的社区交通方便吗'),
        ),
    ]
