# Generated by Django 3.2.6 on 2021-10-14 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0015_blood_pressure_monitoring_physical_examination_physical_examination_abdomen_physical_examination_ath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergies_history',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergies_history_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_personal_information_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='blood_pressure_monitoring',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_pressure_monitoring_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='doctor_login',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_login_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='doctor_registry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_registry_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='family_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_survey_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='history_of_blood_transfusion',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_of_blood_transfusion_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='history_of_infectious_diseases',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_of_infectious_diseases_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='history_of_surgery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_of_surgery_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='history_of_trauma',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_of_trauma_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='major_life_events',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_life_events_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_history_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='out_of_hospital_self_report_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_of_hospital_self_report_survey_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personal_adaptability_assessment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_adaptability_assessment_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personal_comprehensive_psychological_quality_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_comprehensive_psychological_quality_survey_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personal_health_assessment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_health_assessment_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personal_health_behavior_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_health_behavior_survey_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_abdomen',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_abdomen_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_athletic_ability',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_athletic_ability_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_diabetes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_diabetes_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_hearing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_hearing_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_limbs',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_limbs_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_lungs',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_lungs_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_lymph_nodes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_lymph_nodes_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_oral_cavity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_oral_cavity_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_sclera',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_sclera_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_skin',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_skin_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_spine',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_spine_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='physical_examination_vision',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examination_vision_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='social_environment_assessment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_environment_assessment_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_login_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='user_registry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_registry_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='vital_signs_check',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs_check_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
    ]
