# Generated by Django 3.2.6 on 2021-12-01 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_auto_20211201_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_1638327253',
            name='ICPC_zheng_zhuang_he_wen_ti_1638064906',
        ),
        migrations.DeleteModel(
            name='Test_auto_migrate_1638328554',
        ),
        migrations.AlterField(
            model_name='ge_ren_ji_ben_qing_kuang_diao_cha_1638282909',
            name='jiu_zhen_shi_jian_1638064039',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 4, 17, 50, 218419, tzinfo=utc), null=True, verbose_name='就诊时间'),
        ),
        migrations.DeleteModel(
            name='Test_1638327253',
        ),
    ]
