# Generated by Django 3.2.6 on 2021-12-01 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0017_auto_20211201_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ji_bing_shi_1638359530',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xing_ming_1638358955', models.CharField(max_length=255, verbose_name='姓名')),
                ('ri_qi_1638359153', models.DateField(blank=True, default=datetime.date(2021, 12, 1), null=True, verbose_name='日期')),
                ('zhen_duan_1638359350', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='诊断')),
            ],
            options={
                'verbose_name': '疾病史',
                'verbose_name_plural': '疾病史',
            },
        ),
        migrations.CreateModel(
            name='Ge_ren_ji_ben_xin_xi_1638359483',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xing_ming_1638358955', models.CharField(max_length=255, verbose_name='姓名')),
                ('di_zhi_1638358983', models.TextField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('dian_hua_1638358998', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('shen_gao_1638359066', models.FloatField(blank=True, null=True, verbose_name='身高')),
                ('shen_gao_1638359066_standard_value', models.FloatField(blank=True, default=-3.0, null=True, verbose_name='身高标准值')),
                ('shen_gao_1638359066_up_limit', models.FloatField(blank=True, null=True, verbose_name='身高上限')),
                ('shen_gao_1638359066_down_limit', models.FloatField(blank=True, null=True, verbose_name='身高下限')),
                ('ti_zhong_1638359087', models.FloatField(blank=True, null=True, verbose_name='体重')),
                ('ti_zhong_1638359087_standard_value', models.FloatField(blank=True, null=True, verbose_name='体重标准值')),
                ('ti_zhong_1638359087_up_limit', models.FloatField(blank=True, null=True, verbose_name='体重上限')),
                ('ti_zhong_1638359087_down_limit', models.FloatField(blank=True, null=True, verbose_name='体重下限')),
                ('ri_qi_1638359153', models.DateField(blank=True, default=datetime.date(2021, 12, 1), null=True, verbose_name='日期')),
                ('chu_sheng_ri_qi_1638359167', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('xing_bie_1638359238', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '其他')], default=0, null=True, verbose_name='性别')),
                ('xue_xing_1638359282', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未知'), (1, 'A型'), (2, 'B型'), (3, 'AB型'), (4, 'O型')], null=True, verbose_name='血型')),
                ('zheng_zhuang_1638359376', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '个人基本信息',
                'verbose_name_plural': '个人基本信息',
            },
        ),
    ]
