# Generated by Django 3.2.6 on 2021-10-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0018_auto_20211017_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='disease_name',
            field=models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称'),
        ),
    ]
