# Generated by Django 3.2.6 on 2021-10-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0019_alter_medical_history_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_examination_lymph_nodes',
            name='lymph_nodes',
            field=models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc4_physical_examination_and_tests', verbose_name='淋巴结'),
        ),
        migrations.AlterField(
            model_name='physical_examination_sclera',
            name='sclera',
            field=models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc4_physical_examination_and_tests', verbose_name='巩膜'),
        ),
        migrations.AlterField(
            model_name='physical_examination_skin',
            name='skin',
            field=models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc4_physical_examination_and_tests', verbose_name='皮肤'),
        ),
    ]
