# Generated by Django 3.2.6 on 2021-12-20 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20211206_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ge_ren_ji_ben_xin_xi_1638359483',
            name='ri_qi_1638359153',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 20), null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='ji_bing_shi_1638359530',
            name='ri_qi_1638359153',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 20), null=True, verbose_name='日期'),
        ),
    ]
