# Generated by Django 3.2.6 on 2021-10-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('forms', '0021_auto_20211017_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_of_trauma',
            name='diseases_name',
            field=models.ForeignKey(db_column='icpc_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='病名'),
        ),
    ]
