# Generated by Django 3.2.6 on 2021-12-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20211222_1150'),
        ('icpc', '0001_initial'),
        ('forms', '0021_auto_20211222_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_personal_information',
            name='characterfield_age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='basic_personal_information',
            name='characterfield_gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Men_zhen_wen_zhen_diao_cha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('relatedfield_symptom_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_men_zhen_wen_zhen_diao_cha', to='icpc.icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '门诊问诊调查',
                'verbose_name_plural': '门诊问诊调查',
            },
        ),
        migrations.CreateModel(
            name='Ce_shi_biao_dan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterfield_supplementary_description_of_the_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='病情补充描述')),
                ('boolfield_is_life_fun', models.BooleanField(verbose_name='您觉得生活是否有乐趣吗')),
                ('boolfield_do_you_often_work_overtime', models.BooleanField(verbose_name='是否经常加班')),
                ('characterfield_working_hours_per_day', models.TextField(blank=True, max_length=255, null=True, verbose_name='每天工作及工作往返总时长')),
                ('relatedfield_are_you_satisfied_with_the_job_and_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_for_relatedfield_are_you_satisfied_with_the_job_and_life_ce_shi_biao_dan', to='dictionaries.satisfaction', verbose_name='对目前生活和工作满意吗')),
                ('relatedfield_personality_tendency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_for_relatedfield_personality_tendency_ce_shi_biao_dan', to='dictionaries.character', verbose_name='性格倾向')),
            ],
            options={
                'verbose_name': '测试表单',
                'verbose_name_plural': '测试表单',
            },
        ),
    ]
