# Generated by Django 3.2.6 on 2021-12-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_auto_20211223_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_environment_assessment',
            name='boolfield_is_drinking_water_healthy',
        ),
        migrations.AddField(
            model_name='social_environment_assessment',
            name='boolfield_yin_shui_shi_fou_jian_kang',
            field=models.BooleanField(blank=True, null=True, verbose_name='饮水是否健康'),
        ),
    ]
