# Generated by Django 3.2.6 on 2021-12-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('forms', '0023_auto_20211223_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies_history',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='allergies_history',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='basic_personal_information',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='basic_personal_information',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='blood_pressure_monitoring',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='blood_pressure_monitoring',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='ce_shi_biao_dan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='ce_shi_biao_dan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='doctor_login',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='doctor_login',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='doctor_registry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='doctor_registry',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='dorsal_artery_pulsation_examination',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='dorsal_artery_pulsation_examination',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='family_history_of_illness',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='family_history_of_illness',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='fundus_examination',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='fundus_examination',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='history_of_blood_transfusion',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='history_of_blood_transfusion',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='history_of_infectious_diseases',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='history_of_infectious_diseases',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='history_of_surgery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='history_of_surgery',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='history_of_trauma',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='history_of_trauma',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='lower_extremity_edema_examination',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='lower_extremity_edema_examination',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='major_life_events',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='major_life_events',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='men_zhen_wen_zhen_diao_cha',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='men_zhen_wen_zhen_diao_cha',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='out_of_hospital_self_report_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='out_of_hospital_self_report_survey',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='personal_adaptability_assessment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='personal_adaptability_assessment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='personal_comprehensive_psychological_quality_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='personal_comprehensive_psychological_quality_survey',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='personal_health_assessment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='personal_health_assessment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='personal_health_behavior_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='personal_health_behavior_survey',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='physical_examination',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='physical_examination',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='physical_examination_athletic_ability',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='physical_examination_hearing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='physical_examination_hearing',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='physical_examination_oral_cavity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='physical_examination_oral_cavity',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='physical_examination_vision',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='physical_examination_vision',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='social_environment_assessment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='social_environment_assessment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='user_login',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='user_login',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='user_registry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='user_registry',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.AddField(
            model_name='vital_signs_check',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='vital_signs_check',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员'),
        ),
        migrations.CreateModel(
            name='Tang_hua_xue_hong_dan_bai_jian_cha_biao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberfield_tang_hua_xue_hong_dan_bai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='糖化血红蛋白')),
                ('numberfield_tang_hua_xue_hong_dan_bai_standard_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='糖化血红蛋白标准值')),
                ('numberfield_tang_hua_xue_hong_dan_bai_up_limit', models.DecimalField(blank=True, decimal_places=2, default=6.0, max_digits=5, null=True, verbose_name='糖化血红蛋白上限')),
                ('numberfield_tang_hua_xue_hong_dan_bai_down_limit', models.DecimalField(blank=True, decimal_places=2, default=4.0, max_digits=5, null=True, verbose_name='糖化血红蛋白下限')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
            ],
            options={
                'verbose_name': '糖化血红蛋白检查',
                'verbose_name_plural': '糖化血红蛋白检查',
            },
        ),
        migrations.CreateModel(
            name='Kong_fu_xue_tang_jian_cha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberfield_kong_fu_xue_tang', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='空腹血糖')),
                ('numberfield_kong_fu_xue_tang_standard_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='空腹血糖标准值')),
                ('numberfield_kong_fu_xue_tang_up_limit', models.DecimalField(blank=True, decimal_places=2, default=6.16, max_digits=5, null=True, verbose_name='空腹血糖上限')),
                ('numberfield_kong_fu_xue_tang_down_limit', models.DecimalField(blank=True, decimal_places=2, default=3.92, max_digits=5, null=True, verbose_name='空腹血糖下限')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='作业人员')),
            ],
            options={
                'verbose_name': '空腹血糖检查',
                'verbose_name_plural': '空腹血糖检查',
            },
        ),
    ]
