# Generated by Django 3.2.6 on 2021-11-08 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0026_alter_history_of_trauma_diseases_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_personal_information',
            name='customer',
        ),
        migrations.AlterField(
            model_name='basic_personal_information',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='auth.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='history_of_trauma',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.basic_personal_information', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='out_of_hospital_self_report_survey',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.basic_personal_information', verbose_name='客户'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('role', models.ManyToManyField(related_name='staff_role', to='auth.Group', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '员工基本情况',
                'verbose_name_plural': '员工基本情况',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='history_of_trauma',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.staff', verbose_name='作业人员'),
        ),
        migrations.AlterField(
            model_name='out_of_hospital_self_report_survey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.staff', verbose_name='作业人员'),
        ),
    ]
