# Generated by Django 3.2.6 on 2021-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_auto_20211108_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_of_trauma',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
