version: '3'

volumes:
  dental-pgdata: # postgres数据文件目录

networks: # 自定义网络(默认桥接), 不使用links通信
  dental_network:
    driver: bridge
  nginx_network:
    external: true

services:
  dental:
    image: jinniudashu/dental_app:v1
    container_name: dental
    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py migrate
        python manage.py loaddata initial_data.json
        python manage.py init_core_data
        daphne --port 8000 --bind 0.0.0.0 hssc.asgi:application
    env_file:
      - ./dental/.env
    networks:
      - dental_network
      - nginx_network # <== Connect to the web network
    depends_on:
      - dental_db

  dental_db:
    image: postgres:14-alpine
    container_name: dental_db
    env_file:
      - ./dental/.env
    volumes: 
      -  dental-pgdata:/var/lib/postgresql/data
    networks:
      - dental_network

  dental_redis:
    image: redis:alpine
    container_name: dental_redis
    networks:
      - dental_network
    
  dental_celery:
    restart: always
    image: jinniudashu/dental_app:v1
    container_name: dental_celery
    command: celery -A hssc worker -l info
    env_file:
      - ./dental/.env
    networks:
      - dental_network
    depends_on:
      - dental_db
      - dental_redis
      - dental

  dental_celerybeat:
    restart: always
    image: jinniudashu/dental_app:v1
    container_name: dental_celerybeat
    command: celery -A hssc beat -l INFO
    env_file:
      - ./dental/.env
    networks:
      - dental_network
    depends_on:
      - dental_db
      - dental_redis
      - dental
      - dental_celery
