version: '3'

volumes:
  pgdata: # postgres数据文件目录

networks: # 自定义网络(默认桥接), 不使用links通信
  web:
    external: true
  dental_network:
    driver: bridge

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
    networks:
      - web # <== Connect to the web network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
    command:
    #### These are the CLI commands that will configure Traefik and tell it how to work! ####
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      - --api.insecure=true # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
      ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=INFO # <== Setting the level of the logs from traefik
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.docker.network=web # <== Operate on the docker network named web
      ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
      - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
      - --entrypoints.websecured.address=:443 # <== Defining an entrypoint for https on port :443 named web-secured
      # - --entrypoints.http.redirection.entryPoint.to=websecured # <== Redirect http to https on port :443 named web-secured
      # - --entrypoints.http.redirection.entryPoint.scheme=https # <== Redirect http to https on port :443 named web-secured
      ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - --certificatesresolvers.letsencrypt.acme.email=jinniudashu@gmail.com # <== Setting email for certs
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
    labels:
    #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.api.rule=Host(`monitor.tpacn.com`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access

  app:
    image: jinniudashu/dental_app:v1
    # ports:
    #   - "80:8000"
    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py migrate
        python manage.py loaddata initial_data.json
        python manage.py init_core_data
        daphne --port 8000 --bind 0.0.0.0 hssc.asgi:application
    env_file:
      - ./.env
    networks:
      - dental_network
      - web # <== Connect to the web network
    depends_on:
      - db
    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.dental-http.rule=Host(`dental.tpacn.com`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.dental-http.entrypoints=web" # <== Enabling the entrypoint for the whoami service
      - "traefik.http.services.dental-http.loadbalancer.server.port=8000" # <== Enabling the port for the whoami service

  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - dental_network

  redis:
    image: redis:alpine
    networks:
      - dental_network
    
  celery:
    restart: always
    image: jinniudashu/dental_app:v1
    command: celery -A hssc worker -l info
    env_file:
      - ./.env
    networks:
      - dental_network
    depends_on:
      - db
      - redis
      - app

  celerybeat:
    restart: always
    image: jinniudashu/dental_app:v1
    command: celery -A hssc beat -l INFO
    env_file:
      - ./.env
    networks:
      - dental_network
    depends_on:
      - db
      - redis
      - app
      - celery
