# Generated by Django 3.2.6 on 2021-09-19 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('icpc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='事件名称')),
                ('icpc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icpc.icpc', verbose_name='事件代码')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作业名称')),
                ('entry', models.CharField(blank=True, max_length=250, null=True, verbose_name='作业入口')),
                ('group', models.ManyToManyField(to='auth.Group', verbose_name='作业角色')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='服务类型名称')),
                ('init_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_oid', to='core.operation', verbose_name='初始作业')),
            ],
        ),
        migrations.CreateModel(
            name='Service_proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='服务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_uid', to=settings.AUTH_USER_MODEL, verbose_name='服务专员')),
            ],
            options={
                'verbose_name': '服务进程表',
                'verbose_name_plural': '服务进程表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operation_proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(0, '创建'), (1, '就绪'), (2, '运行'), (3, '挂起'), (4, '结束')], verbose_name='作业状态')),
                ('ppid', models.IntegerField(blank=True, null=True, verbose_name='父进程id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户id')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operation', verbose_name='作业id')),
                ('service_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service_proc', verbose_name='服务id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_uid', to=settings.AUTH_USER_MODEL, verbose_name='操作员id')),
            ],
            options={
                'verbose_name': '作业进程表',
                'verbose_name_plural': '作业进程表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='core.Service', verbose_name='服务类型'),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='事件代码')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operation', verbose_name='下一项作业')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='服务类型')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operation', verbose_name='事件来源'),
        ),
    ]
