# Generated by Django 3.2.6 on 2021-11-23 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('icpc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='事件名')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='事件描述')),
                ('expression', models.TextField(blank=True, help_text='\n\t\t说明：<br>\n\t\t1. 表达式接受的逻辑运算符：or, and, not, in, >=, <=, >, <, ==, +, -, *, /, ^, ()<br>\n\t\t2. 字段名只允许由小写字母a~z，数字0~9和下划线_组成；字段值接受数字和字符，字符需要放在双引号中，如"A0101"\n\t\t', max_length=1024, null=True, verbose_name='表达式')),
                ('parameters', models.CharField(blank=True, max_length=1024, null=True, verbose_name='检查字段')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='表单名称')),
                ('label', models.CharField(max_length=255, verbose_name='显示名称')),
                ('style', models.PositiveSmallIntegerField(choices=[(0, '详情'), (1, '列表')], default=0, verbose_name='风格')),
                ('fields_list', models.TextField(blank=True, max_length=1024, null=True, verbose_name='表单字段')),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='指令名称')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('code', models.CharField(max_length=10, verbose_name='指令代码')),
                ('func', models.CharField(max_length=100, verbose_name='操作函数')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='指令描述')),
            ],
            options={
                'verbose_name': '指令',
                'verbose_name_plural': '指令',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作业名称')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, '0级'), (1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级')),
                ('suppliers', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('not_suitable', models.CharField(blank=True, max_length=255, null=True, verbose_name='不适用对象')),
                ('time_limits', models.DurationField(blank=True, null=True, verbose_name='完成时限')),
                ('working_hours', models.DurationField(blank=True, null=True, verbose_name='工时')),
                ('frequency', models.CharField(blank=True, max_length=255, null=True, verbose_name='频次')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='成本')),
                ('load_feedback', models.BooleanField(default=False, verbose_name='是否反馈负荷数量')),
                ('resource_materials', models.CharField(blank=True, max_length=255, null=True, verbose_name='配套物料')),
                ('resource_devices', models.CharField(blank=True, max_length=255, null=True, verbose_name='配套设备')),
                ('resource_knowledge', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务知识')),
                ('form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.form', verbose_name='表单')),
                ('group', models.ManyToManyField(to='auth.Group', verbose_name='作业角色')),
                ('icpc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='ICPC')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='服务名称')),
                ('first_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation', verbose_name='起始作业')),
                ('icpc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='ICPC')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='组别')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('role', models.ManyToManyField(related_name='staff_role', to='auth.Group', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '员工基本情况',
                'verbose_name_plural': '员工基本情况',
            },
        ),
        migrations.CreateModel(
            name='Service_proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='服务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_uid', to=settings.AUTH_USER_MODEL, verbose_name='服务专员')),
            ],
            options={
                'verbose_name': '服务进程',
                'verbose_name_plural': '服务进程',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operation_proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '创建'), (1, '就绪'), (2, '运行'), (3, '挂起'), (4, '结束')], verbose_name='作业状态')),
                ('entry', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='作业入口')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operation', verbose_name='作业')),
                ('ppid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='父进程')),
                ('service_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service_proc', verbose_name='服务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_uid', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '作业进程',
                'verbose_name_plural': '作业进程',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event_instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='指令序号')),
                ('params', models.PositiveIntegerField(blank=True, null=True, verbose_name='创建作业')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='事件')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instruction', verbose_name='指令')),
            ],
            options={
                'verbose_name': '事件指令集',
                'verbose_name_plural': '事件指令集',
                'ordering': ['event', 'order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='next',
            field=models.ManyToManyField(to='core.Operation', verbose_name='后续作业'),
        ),
        migrations.AddField(
            model_name='event',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_oid', to='core.operation', verbose_name='上道作业'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户登记表',
                'verbose_name_plural': '客户登记表',
            },
        ),
    ]
