# Generated by Django 3.2.6 on 2022-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedservice',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='推荐次数'),
        ),
    ]
