# Generated by Django 3.2.6 on 2022-06-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='awaiting_time_frame',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='duration',
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='begin_time_setting',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '当前系统时间'), (2, '客户出生日期')], default=0, verbose_name='开始时间参考'),
        ),
    ]
