# Generated by Django 3.2.6 on 2022-06-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepackagedetail',
            options={'ordering': ['id'], 'verbose_name': '服务项目模板', 'verbose_name_plural': '服务项目模板'},
        ),
    ]
