# Generated by Django 3.2.6 on 2024-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedservice',
            name='receive_data_from',
            field=models.ManyToManyField(blank=True, related_name='recommendedservice_receive_data_from', to='core.Service', verbose_name='接收数据'),
        ),
    ]
