# Generated by Django 3.2.6 on 2023-10-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCoroutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('ctype', models.CharField(max_length=50, verbose_name='协程类型')),
            ],
            options={
                'verbose_name': '作业协程',
                'verbose_name_plural': '作业协程',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='operationproc',
            name='coroutine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.operationcoroutine', verbose_name='作业协程'),
        ),
    ]
