# Generated by Django 3.2.6 on 2023-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '指定开始时间'), (1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=1, verbose_name='执行时间基准'),
        ),
    ]
