# Generated by Django 3.2.6 on 2022-10-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='services',
        ),
    ]
