# Generated by Django 3.2.6 on 2022-01-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_proc',
            name='form_slugs',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='表单索引'),
        ),
    ]
