# Generated by Django 3.2.6 on 2023-10-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l1service',
            name='include_services',
        ),
    ]
