# Generated by Django 3.2.6 on 2022-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='upload',
        ),
        migrations.AddField(
            model_name='customer',
            name='weixin_openid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='微信openid'),
        ),
    ]
