# Generated by Django 3.2.6 on 2023-08-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffTodo',
        ),
    ]
