# Generated by Django 3.2.6 on 2022-05-16 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customerservicelog',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='buessinessform',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='operationproc',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'service')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='operationproc',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
