# Generated by Django 3.2.6 on 2022-01-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='checked_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='检查字段'),
        ),
    ]
