# Generated by Django 3.2.6 on 2023-10-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('completed_time', models.DateTimeField(editable=False, null=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_proc_customer', to='core.customer', verbose_name='客户')),
                ('l1_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.l1service', verbose_name='任务')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_proc_operator', to='core.customer', verbose_name='操作员')),
                ('parent_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskproc', verbose_name='父进程')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='服务')),
            ],
            options={
                'verbose_name': '任务进程',
                'verbose_name_plural': '任务进程',
                'ordering': ['id'],
            },
        ),
    ]
