# Generated by Django 3.2.6 on 2023-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '系统服务'), (1, '管理调度服务'), (2, '诊疗服务')], default=2, verbose_name='服务类型'),
        ),
    ]
