# Generated by Django 3.2.6 on 2021-11-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户注册信息', 'verbose_name_plural': '客户注册信息'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工基本信息', 'verbose_name_plural': '员工基本信息'},
        ),
    ]
