# Generated by Django 3.2.6 on 2023-06-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservicelog',
            name='category',
        ),
        migrations.AddField(
            model_name='customerservicelog',
            name='form_class',
            field=models.PositiveSmallIntegerField(choices=[(1, '调查类'), (2, '诊断类'), (3, '治疗类')], null=True, verbose_name='表单类型'),
        ),
    ]
