# Generated by Django 3.2.6 on 2022-08-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='wecom_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='企业微信id'),
        ),
    ]
