# Generated by Django 3.2.6 on 2023-08-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedservice',
            name='recommended_batch',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='推荐批次'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='cpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractserviceproc', verbose_name='上层服务进程'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operationproc', verbose_name='推荐进程'),
        ),
    ]
