# Generated by Django 3.2.6 on 2022-04-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_proc',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='operation_proc',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='operation_proc',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '0级'), (1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级'),
        ),
    ]
