# Generated by Django 3.2.6 on 2023-03-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='follow_up_interval',
            field=models.DurationField(blank=True, null=True, verbose_name='随访间隔'),
        ),
        migrations.AddField(
            model_name='service',
            name='follow_up_required',
            field=models.BooleanField(default=False, verbose_name='是否需要随访'),
        ),
        migrations.AddField(
            model_name='service',
            name='follow_up_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_services', to='core.service', verbose_name='随访服务'),
        ),
    ]
