# Generated by Django 3.2.6 on 2022-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '系统基础服务'), (1, '系统业务服务'), (2, '用户业务服务')], default=2, verbose_name='服务类型'),
        ),
    ]
