# Generated by Django 3.2.6 on 2023-03-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230320_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='follow_up_required',
            field=models.BooleanField(default=False, verbose_name='需要随访'),
        ),
        migrations.CreateModel(
            name='VirtualStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_workgroup', models.BooleanField(default=False, verbose_name='是否为工作小组')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='职员')),
                ('workgroup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workgroup', verbose_name='工作小组')),
            ],
        ),
        migrations.AddField(
            model_name='operationproc',
            name='priority_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.virtualstaff', verbose_name='优先操作员'),
        ),
    ]
