# Generated by Django 3.2.6 on 2021-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211123_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
