# Generated by Django 3.2.6 on 2022-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recommendedservice_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
