# Generated by Django 3.2.6 on 2022-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220414_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_proc',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划时间'),
        ),
    ]
