# Generated by Django 3.2.6 on 2022-05-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220516_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicelog',
            name='cpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractserviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='customerservicelog',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_log_creater', to='core.customer', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='customerservicelog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_log_customer', to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='customerservicelog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_log_operator', to='core.customer', verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='customerservicelog',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='cpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractserviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='cpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractserviceproc', verbose_name='服务进程id'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_service_creater', to='core.customer', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_service_customer', to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_service_operator', to='core.customer', verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='recommendedservice',
            name='pid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operationproc', verbose_name='作业进程id'),
        ),
    ]
