# Generated by Django 3.2.6 on 2023-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230512_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrule',
            name='event_type',
            field=models.CharField(choices=[('FORM_EVENT', '表单事件'), ('SCHEDULE_EVENT', '调度事件')], default='SCHEDULE_EVENT', max_length=100, verbose_name='事件类型'),
        ),
    ]
