# Generated by Django 3.2.6 on 2022-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220506_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrule',
            name='detection_scope',
            field=models.CharField(blank=True, choices=[('ALL', '所有历史表单'), ('CURRENT_SERVICE', '本次服务表单'), ('LAST_WEEK_SERVICES', '过去7天表单')], default='CURRENT_SERVICE', max_length=100, null=True, verbose_name='检测范围'),
        ),
    ]
