# Generated by Django 3.2.6 on 2022-01-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operation_checked_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='checked_fields',
        ),
    ]
