# Generated by Django 3.2.6 on 2022-06-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220620_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepackage',
            old_name='begin_time_setting',
            new_name='default_beginning_time',
        ),
    ]
