# Generated by Django 3.2.6 on 2023-10-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskproc'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationproc',
            name='task_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.taskproc', verbose_name='任务进程'),
        ),
    ]
