# Generated by Django 3.2.6 on 2022-10-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_system_service',
        ),
    ]
