# Generated by Django 3.2.6 on 2021-09-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_operation_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': '业务事件', 'verbose_name_plural': '业务事件'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['id'], 'verbose_name': '作业指令', 'verbose_name_plural': '作业指令'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['id'], 'verbose_name': '作业', 'verbose_name_plural': '作业'},
        ),
        migrations.AlterModelOptions(
            name='operation_proc',
            options={'ordering': ['id'], 'verbose_name': '作业进程', 'verbose_name_plural': '作业进程'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
        migrations.AlterModelOptions(
            name='service_proc',
            options={'ordering': ['id'], 'verbose_name': '服务进程', 'verbose_name_plural': '服务进程'},
        ),
    ]
