# Generated by Django 3.2.6 on 2022-11-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicepackage_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerule',
            name='service_spec',
        ),
        migrations.DeleteModel(
            name='ServiceSpec',
        ),
    ]
