# Generated by Django 3.2.6 on 2022-05-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220517_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicelog',
            name='pid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operationproc', verbose_name='作业进程id'),
        ),
    ]
