# Generated by Django 3.2.6 on 2022-06-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_begin_time_setting_servicepackage_default_beginning_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackagedetail',
            name='check_awaiting_timeout',
        ),
    ]
