# Generated by Django 3.2.6 on 2022-01-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220112_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation_proc',
            name='user',
        ),
        migrations.AddField(
            model_name='operation_proc',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_uid', to='core.staff', verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_cid', to='core.customer', verbose_name='客户'),
        ),
    ]
