# Generated by Django 3.2.6 on 2023-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventrule_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemoperand',
            name='operand_type',
            field=models.CharField(choices=[('SCHEDULE_OPERAND', '调度作业'), ('FORM_OPERAND', '表单作业')], default='SCHEDULE_OPERAND', max_length=100, verbose_name='系统作业类型'),
        ),
    ]
