# Generated by Django 3.2.6 on 2022-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_externalservicemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationproc',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, '创建'), (1, '就绪'), (2, '运行'), (3, '挂起'), (4, '结束'), (10, '等待超时')], verbose_name='作业状态'),
        ),
    ]
