# Generated by Django 3.2.6 on 2022-02-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_operation_checked_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='form',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
