# Generated by Django 3.2.6 on 2021-09-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('core', '0003_auto_20210919_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='作业代码'),
        ),
        migrations.AddField(
            model_name='service',
            name='icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='服务代码'),
        ),
        migrations.AlterField(
            model_name='event',
            name='icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='事件代码'),
        ),
    ]
