# Generated by Django 3.2.6 on 2022-04-14 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operation_proc_schedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_proc',
            old_name='schedule_time',
            new_name='scheduled',
        ),
    ]
