# Generated by Django 3.2.6 on 2023-03-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230322_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='workgroup',
        ),
        migrations.AlterField(
            model_name='customer',
            name='charge_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.virtualstaff', verbose_name='负责人'),
        ),
    ]
