# Generated by Django 3.2.6 on 2023-10-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operationproc_task_proc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractserviceproc',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='contractserviceproc',
            name='current_service',
        ),
        migrations.AddField(
            model_name='contractservice',
            name='end_l1_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_l1_service', to='core.l1service', verbose_name='结束任务'),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='start_l1_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_l1_service', to='core.l1service', verbose_name='起始任务'),
        ),
        migrations.AddField(
            model_name='contractserviceproc',
            name='current_l1_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.l1service', verbose_name='任务状态'),
        ),
        migrations.AddField(
            model_name='taskproc',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='contractserviceproc',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='operationproc',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级'),
        ),
    ]
