# Generated by Django 3.2.6 on 2022-10-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_is_system_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsscbaseformmodel',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsscbaseformmodel_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
    ]
