# Generated by Django 3.2.6 on 2022-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220626_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='cycle_times',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='周期数/天数'),
        ),
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='cycle_unit',
            field=models.CharField(blank=True, choices=[('TOTAL', '总共'), ('DAY', '每天'), ('WEEK', '每周'), ('MONTH', '每月'), ('QUARTER', '每季'), ('YEAR', '每年')], default='TOTAL', max_length=10, null=True, verbose_name='周期单位'),
        ),
    ]
