# Generated by Django 3.2.6 on 2022-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventrule_detection_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHealthServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('category', models.CharField(blank=True, choices=[('Subjective', '主观资料'), ('ObjectiveO', '客观资料'), ('Assessment', '诊断与评价'), ('Plan', '治疗方案'), ('Management', '管理活动')], max_length=20, null=True, verbose_name='记录类别')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='服务记录')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
