# Generated by Django 3.2.6 on 2023-10-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231004_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractserviceproc',
            name='current_l1_service',
        ),
        migrations.AddField(
            model_name='contractserviceproc',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.l1service', verbose_name='当前任务'),
        ),
        migrations.AlterField(
            model_name='contractserviceproc',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
    ]
