# Generated by Django 3.2.6 on 2022-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hsscbaseformmodel_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationproc',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
        migrations.AddField(
            model_name='operationproc',
            name='working_hours',
            field=models.DurationField(blank=True, null=True, verbose_name='工时'),
        ),
    ]
