# Generated by Django 3.2.6 on 2021-09-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('core', '0004_auto_20210919_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='ICPC'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='ICPC'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='ICPC'),
        ),
        migrations.AlterField(
            model_name='service',
            name='init_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init_oid', to='core.operation', verbose_name='初始作业'),
        ),
    ]
