# Generated by Django 3.2.6 on 2022-05-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customerhealthservicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('category', models.CharField(blank=True, choices=[('Subjective', '主观资料'), ('ObjectiveO', '客观资料'), ('Assessment', '诊断与评价'), ('Plan', '治疗方案'), ('Management', '管理活动')], max_length=20, null=True, verbose_name='记录类别')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='服务记录')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerservicelog_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerservicelog_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerservicelog_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerservicelog_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerservicelog_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomerHealthServiceLog',
        ),
    ]
