# Generated by Django 3.2.6 on 2022-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedservice',
            name='passing_data',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '接收，不可编辑'), (2, '接收，可以编辑')], default=0, null=True, verbose_name='接收表单'),
        ),
    ]
