# Generated by Django 3.2.6 on 2022-06-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220626_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='cycle_times',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='周期数/天数'),
        ),
    ]
