# Generated by Django 3.2.6 on 2022-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220112_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_proc',
            name='form_slugs',
            field=models.JSONField(blank=True, null=True, verbose_name='表单索引'),
        ),
    ]
