# Generated by Django 3.2.6 on 2022-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220202_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='icpc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icpc',
        ),
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(default='SYSTEM', max_length=255, verbose_name='显示名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='expression',
            field=models.TextField(blank=True, help_text='\n        说明：<br>\n        1. 作业完成事件: completed<br>\n        2. 表达式接受的逻辑运算符：or, and, not, in, >=, <=, >, <, ==, +, -, *, /, ^, ()<br>\n        3. 字段名只允许由小写字母a~z，数字0~9和下划线_组成；字段值接受数字和字符，字符需要放在双引号中，如"A0101"\n        ', max_length=1024, null=True, verbose_name='表达式'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='名称'),
        ),
    ]
