# Generated by Django 3.2.6 on 2022-06-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_servicepackagedetail_check_awaiting_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='default_beginning_time',
        ),
        migrations.RemoveField(
            model_name='servicepackagedetail',
            name='reference_start_tim',
        ),
        migrations.AddField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '当前系统时间'), (2, '客户出生日期'), (3, '上个服务结束时间')], default=0, verbose_name='开始时间参考'),
        ),
    ]
