# Generated by Django 3.2.6 on 2023-03-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230322_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualstaff',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='virtualstaff',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='virtualstaff',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
