# Generated by Django 3.2.6 on 2022-04-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_schedule_time_operation_proc_scheduled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_proc',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='operation_proc',
            old_name='modified',
            new_name='modified_time',
        ),
        migrations.RenameField(
            model_name='operation_proc',
            old_name='scheduled',
            new_name='scheduled_time',
        ),
    ]
