# Generated by Django 3.2.6 on 2022-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220206_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_instructions',
            name='params',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='创建作业'),
        ),
    ]
