# Generated by Django 3.2.6 on 2022-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recommendedservice_passing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='个人照片'),
        ),
    ]
