# Generated by Django 3.2.6 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_operation_proc_form_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='可用字段'),
        ),
    ]
