# Generated by Django 3.2.6 on 2022-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220509_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicelog',
            name='category',
            field=models.CharField(blank=True, choices=[('Subjective', '主观资料'), ('ObjectiveO', '客观资料'), ('Assessment', '诊断与评价'), ('Plan', '治疗方案'), ('Management', '管理活动')], max_length=50, null=True, verbose_name='记录类别'),
        ),
    ]
