# Generated by Django 3.2.6 on 2022-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221024_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['id'], 'verbose_name': '药品基本信息表', 'verbose_name_plural': '药品基本信息表'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='cf_dosage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='常用单次处方用量(处方单位)'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cf_measure',
            field=models.CharField(max_length=30, null=True, verbose_name='处方计量单位'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='current_storage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='当前库存'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=60, null=True, verbose_name='用量'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='gjjbyp',
            field=models.CharField(max_length=100, null=True, verbose_name='国家基本药品目录名称'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_use',
            field=models.BooleanField(default=True, verbose_name='是否使用中'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='measure',
            field=models.CharField(max_length=30, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mz_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊参考单价'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mzcf_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊处方价格'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='not_cfyp',
            field=models.BooleanField(default=False, verbose_name='非处方药标记'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='specification',
            field=models.CharField(max_length=100, null=True, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(max_length=40, null=True, verbose_name='药剂类型'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage',
            field=models.CharField(max_length=60, null=True, verbose_name='用法'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='xs_measure',
            field=models.CharField(max_length=30, null=True, verbose_name='销售计量单位'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ybypbm',
            field=models.CharField(max_length=100, null=True, verbose_name='医保药品目录对应药品编码'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ybyplb',
            field=models.CharField(max_length=2, null=True, verbose_name='药品报销类别（甲类、乙类）'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='yp_code',
            field=models.CharField(max_length=10, null=True, verbose_name='药品编码'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='yp_sort',
            field=models.CharField(max_length=60, null=True, verbose_name='药品分类名称'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ypty_name',
            field=models.CharField(max_length=200, null=True, verbose_name='药品通用名称'),
        ),
    ]
