# Generated by Django 3.2.6 on 2021-09-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210919_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='作业事件'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='服务名称'),
        ),
    ]
