# Generated by Django 3.2.6 on 2022-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220620_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=0, verbose_name='开始时间基准'),
        ),
    ]
