# Generated by Django 3.2.6 on 2022-06-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servicepackagedetail_default_beginning_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackagedetail',
            name='after_base_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='基准时间之后'),
        ),
    ]
