# Generated by Django 3.2.6 on 2022-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customerservicelog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerule',
            name='route_to',
            field=models.CharField(blank=True, choices=[('/clinic/', '任务工作台'), ('/clinic/customer_service/id/', '客户病例首页')], max_length=255, null=True, verbose_name='跳转至'),
        ),
    ]
