# Generated by Django 3.2.6 on 2022-07-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servicepackagedetail_default_beginning_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChengBaoRenYuanQingDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('序号', models.CharField(blank=True, max_length=255, null=True, verbose_name='序号')),
                ('保单号', models.CharField(blank=True, max_length=255, null=True, verbose_name='保单号')),
                ('被保人姓名', models.CharField(blank=True, max_length=255, null=True, verbose_name='被保人姓名')),
                ('证件类型', models.CharField(blank=True, max_length=255, null=True, verbose_name='证件类型')),
                ('身份证号', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号')),
                ('出生日期', models.CharField(blank=True, max_length=255, null=True, verbose_name='出生日期')),
                ('保险责任', models.CharField(blank=True, max_length=255, null=True, verbose_name='保险责任')),
                ('保险有效期', models.CharField(blank=True, max_length=255, null=True, verbose_name='保险有效期')),
                ('联系方式', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
            ],
        ),
    ]
