# Generated by Django 3.2.6 on 2021-09-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210920_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='指令名称'),
        ),
    ]
