# Generated by Django 3.2.6 on 2022-02-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_alter_event_instructions_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_proc',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='角色组'),
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='service_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service_proc', verbose_name='服务进程'),
        ),
    ]
