# Generated by Django 3.2.6 on 2022-04-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220414_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='workgroup',
            field=models.ManyToManyField(blank=True, null=True, to='core.Workgroup', verbose_name='服务小组'),
        ),
    ]
