# Generated by Django 3.2.6 on 2022-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicerule_route_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerule',
            name='route_to',
        ),
        migrations.AddField(
            model_name='service',
            name='route_to',
            field=models.CharField(blank=True, choices=[('INDEX', '任务工作台'), ('CUSTOMER_HOMEPAGE', '客户病例首页')], default='CUSTOMER_HOMEPAGE', max_length=50, null=True, verbose_name='跳转至'),
        ),
    ]
