# Generated by Django 3.2.6 on 2022-08-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chengbaorenyuanqingdan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chengbaorenyuanqingdan',
            options={'ordering': ['id'], 'verbose_name': '导入表-承保人员清单', 'verbose_name_plural': '导入表-承保人员清单'},
        ),
    ]
