# Generated by Django 3.2.6 on 2022-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220210_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='group',
        ),
        migrations.AddField(
            model_name='staff',
            name='assistant_physician',
            field=models.BooleanField(blank=True, null=True, verbose_name='助理医师'),
        ),
        migrations.AddField(
            model_name='staff',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='挂号费'),
        ),
        migrations.AddField(
            model_name='staff',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='staff',
            name='service_lever',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('低', '低'), ('中', '中'), ('高', '高')], null=True, verbose_name='服务级别'),
        ),
        migrations.AddField(
            model_name='staff',
            name='standardized_workload',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='标化工作量'),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('主任医师', '主任医师'), ('副主任医师', '副主任医师'), ('主治医师', '主治医师'), ('住院医师', '住院医师'), ('主任护师', '主任护师'), ('副主任护师', '副主任护师'), ('主管护师', '主管护师'), ('护士长', '护士长'), ('护士', '护士'), ('其他', '其他')], null=True, verbose_name='职称'),
        ),
        migrations.AddField(
            model_name='staff',
            name='workgroup',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='服务小组'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
    ]
