# Generated by Django 3.2.6 on 2022-05-10 14:23

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220510_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerservicelog',
            options={'ordering': ['created_time'], 'verbose_name': '客户服务记录', 'verbose_name_plural': '客户服务记录'},
        ),
        migrations.AlterField(
            model_name='customerservicelog',
            name='data',
            field=models.JSONField(blank=True, encoder=json.encoder.JSONEncoder, null=True, verbose_name='服务记录'),
        ),
        migrations.AlterField(
            model_name='service',
            name='route_to',
            field=models.CharField(blank=True, choices=[('INDEX', '任务工作台'), ('CUSTOMER_HOMEPAGE', '客户病例首页')], default='CUSTOMER_HOMEPAGE', max_length=50, null=True, verbose_name='完成跳转至'),
        ),
    ]
