# Generated by Django 3.2.6 on 2022-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220620_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='base_interval',
            field=models.DurationField(blank=True, default='00:00:00', help_text='例如：3 days, 22:00:00', null=True, verbose_name='基准间隔'),
        ),
    ]
