# Generated by Django 3.2.6 on 2021-09-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('core', '0008_auto_20210920_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='事件名称')),
                ('icpc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icpc.icpc', verbose_name='ICPC')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_oid', to='core.operation', verbose_name='下一项作业')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_oid', to='core.operation', verbose_name='事件来源')),
            ],
            options={
                'verbose_name': '事件指令字典',
                'verbose_name_plural': '事件指令字典',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='next',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='service',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
