# Generated by Django 3.2.6 on 2022-02-11 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20220211_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='workgroup',
        ),
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('label', models.CharField(max_length=255, verbose_name='服务小组名称')),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to=settings.AUTH_USER_MODEL, verbose_name='组长')),
            ],
            options={
                'verbose_name': '服务小组',
                'verbose_name_plural': '服务小组',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='workgroup',
            field=models.ManyToManyField(to='core.Workgroup', verbose_name='服务小组'),
        ),
    ]
