# Generated by Django 3.2.6 on 2022-04-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forms', '0005_delete_testsite'),
        ('core', '0008_eventrule_servicerule_servicespec_systemoperand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operation_proc',
            new_name='OperationProc',
        ),
    ]
