# Generated by Django 3.2.6 on 2022-05-10 14:42

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220510_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicelog',
            name='data',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True, verbose_name='服务记录'),
        ),
    ]
