# Generated by Django 3.2.6 on 2022-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_servicepackagedetail_base_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='base_interval',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='基准间隔'),
        ),
    ]
