# Generated by Django 3.2.6 on 2022-04-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_delete_testsite'),
        ('core', '0009_rename_operation_proc_operationproc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_proc',
            new_name='ServiceProc',
        ),
    ]
