# Generated by Django 3.2.6 on 2021-09-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210920_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_instruction',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_oid', to='core.operation', verbose_name='事件来源'),
        ),
    ]
