# Generated by Django 3.2.6 on 2022-02-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220211_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='group_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to='core.staff', verbose_name='组长'),
        ),
    ]
