# Generated by Django 3.2.6 on 2022-04-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_service_proc_serviceproc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationproc',
            old_name='modified_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='assistant_physician',
            new_name='is_assistant_physician',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='group_leader',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='charge_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='health_record',
            field=models.JSONField(blank=True, null=True, verbose_name='健康记录'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='staff',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='staff',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AddField(
            model_name='staff',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_sid', to='core.serviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='组长'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='operationproc',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_proc_customer', to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='operationproc',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_proc_operator', to='core.customer', verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='serviceproc',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_proc_customer', to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='serviceproc',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_proc_operator', to='core.customer', verbose_name='服务专员'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='workgroup',
            field=models.ManyToManyField(blank=True, to='core.Workgroup', verbose_name='服务小组'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
