# Generated by Django 3.2.6 on 2022-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workgroup_group_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': '业务规则', 'verbose_name_plural': '业务规则'},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规则说明'),
        ),
        migrations.AlterField(
            model_name='event',
            name='expression',
            field=models.TextField(blank=True, help_text='\n        说明：<br>\n        1. 作业完成事件: completed<br>\n        2. 表达式接受的逻辑运算符：or, and, not, in, >=, <=, >, <, ==, +, -, *, /, ^, ()<br>\n        3. 字段名只允许由小写字母a~z，数字0~9和下划线_组成；字段值接受数字和字符，字符需要放在双引号中，如"A0101"\n        ', max_length=1024, null=True, verbose_name='规则表达式'),
        ),
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='名称'),
        ),
    ]
