# Generated by Django 3.2.6 on 2022-06-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_servicepackagedetail_default_beginning_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='execution_time_frame',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='execution_time_frame',
        ),
        migrations.AddField(
            model_name='service',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
    ]
