# Generated by Django 3.2.6 on 2021-09-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210920_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_instruction',
            options={'ordering': ['id'], 'verbose_name': '事件指令表', 'verbose_name_plural': '事件指令表'},
        ),
    ]
