# Generated by Django 3.2.6 on 2022-06-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220621_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='awaiting_time_frame',
        ),
    ]
