# Generated by Django 3.2.6 on 2022-06-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_service_awaiting_time_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationproc',
            name='acceptance_timeout',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='受理超时'),
        ),
        migrations.AddField(
            model_name='operationproc',
            name='completion_timeout',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='完成超时'),
        ),
    ]
