# Generated by Django 3.2.6 on 2022-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220621_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedentity',
            name='header_fields_json',
            field=models.JSONField(blank=True, null=True, verbose_name='表头字段json'),
        ),
    ]
