# Generated by Django 3.2.6 on 2021-09-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210921_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Operation',
        ),
        migrations.AddField(
            model_name='event_instruction',
            name='rule',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规则描述'),
        ),
        migrations.AddField(
            model_name='service',
            name='first_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation', verbose_name='起始作业'),
        ),
        migrations.AlterField(
            model_name='event_instruction',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_oid', to='core.operation', verbose_name='上道作业'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
