# Generated by Django 3.2.6 on 2021-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210921_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_instruction',
            options={'ordering': ['id'], 'verbose_name': '作业事件', 'verbose_name_plural': '作业事件'},
        ),
        migrations.AddField(
            model_name='operation',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '0级'), (1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, '创建'), (1, '就绪'), (2, '运行'), (3, '挂起'), (4, '结束')], verbose_name='作业状态'),
        ),
    ]
