# Generated by Django 3.2.6 on 2021-09-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210921_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='成本'),
        ),
        migrations.AddField(
            model_name='operation',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='频次'),
        ),
        migrations.AddField(
            model_name='operation',
            name='load_feedback',
            field=models.BooleanField(default=False, verbose_name='是否反馈负荷数量'),
        ),
        migrations.AddField(
            model_name='operation',
            name='not_suitable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='不适用对象'),
        ),
        migrations.AddField(
            model_name='operation',
            name='resource_devices',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配套设备'),
        ),
        migrations.AddField(
            model_name='operation',
            name='resource_knowledge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务知识'),
        ),
        migrations.AddField(
            model_name='operation',
            name='resource_materials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配套物料'),
        ),
        migrations.AddField(
            model_name='operation',
            name='suppliers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='operation',
            name='time_limits',
            field=models.DurationField(blank=True, null=True, verbose_name='完成时限'),
        ),
        migrations.AddField(
            model_name='operation',
            name='working_hours',
            field=models.DurationField(blank=True, null=True, verbose_name='工时'),
        ),
    ]
