# Generated by Django 3.2.6 on 2021-10-06 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_auto_20211004_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['id'], 'verbose_name': '指令', 'verbose_name_plural': '指令'},
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_cid', to=settings.AUTH_USER_MODEL, verbose_name='客户id'),
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='ppid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation_proc', verbose_name='父进程id'),
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='service_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service_proc', verbose_name='服务id'),
        ),
        migrations.AlterField(
            model_name='operation_proc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_uid', to=settings.AUTH_USER_MODEL, verbose_name='操作员id'),
        ),
    ]
