# Generated by Django 3.2.6 on 2021-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211006_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': '事件', 'verbose_name_plural': '事件'},
        ),
        migrations.AddField(
            model_name='instruction',
            name='params',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='参数'),
        ),
    ]
