# Generated by Django 3.2.6 on 2021-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_event_instructions_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_instructions',
            name='params',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='创建作业'),
        ),
    ]
