# Generated by Django 3.2.6 on 2021-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='forms',
            field=models.ManyToManyField(to='core.Form', verbose_name='表单'),
        ),
    ]
