# Generated by Django 3.2.6 on 2021-10-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_operation_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='entry',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='入口'),
        ),
        migrations.AddField(
            model_name='form',
            name='style',
            field=models.PositiveSmallIntegerField(choices=[(0, '详情'), (1, '列表')], default=0, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=255, verbose_name='表单名称'),
        ),
    ]
