# Generated by Django 3.2.6 on 2021-10-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211008_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='entry',
        ),
        migrations.AddField(
            model_name='operation_proc',
            name='entry',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='作业入口'),
        ),
    ]
