# Generated by Django 3.2.6 on 2021-10-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211008_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='forms',
        ),
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称'),
        ),
        migrations.AddField(
            model_name='operation',
            name='form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.form', verbose_name='表单'),
        ),
        migrations.AddField(
            model_name='operation',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='事件名'),
        ),
    ]
