# Generated by Django 3.2.6 on 2021-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0029_auto_20211009_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='entry',
        ),
        migrations.AlterField(
            model_name='operation',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='作业角色'),
        ),
    ]
