# Generated by Django 3.2.6 on 2021-10-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20211014_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rule',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='事件描述'),
        ),
        migrations.AlterField(
            model_name='event',
            name='next',
            field=models.ManyToManyField(blank=True, null=True, to='core.Operation', verbose_name='后续作业'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('expr', models.TextField(max_length=1024, verbose_name='表达式')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='规则描述')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='事件名称')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operation', verbose_name='所属作业')),
            ],
        ),
    ]
