# Generated by Django 3.2.6 on 2021-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0034_auto_20211019_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='next',
            field=models.ManyToManyField(to='core.Operation', verbose_name='后续作业'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='group',
            field=models.ManyToManyField(to='auth.Group', verbose_name='作业角色'),
        ),
    ]
