# Generated by Django 3.2.6 on 2021-10-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20211019_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['operation', 'id'], 'verbose_name': '规则', 'verbose_name_plural': '规则'},
        ),
    ]
