# Generated by Django 3.2.6 on 2021-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_rule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='规则描述'),
        ),
    ]
