# Generated by Django 3.2.6 on 2021-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='parameters',
            field=models.JSONField(null=True, verbose_name='检查字段'),
        ),
    ]
