# Generated by Django 3.2.6 on 2021-10-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rule_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='expr',
            new_name='expression',
        ),
    ]
