# Generated by Django 3.2.6 on 2021-10-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_expr_rule_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event', verbose_name='事件名称'),
        ),
    ]
