# Generated by Django 3.2.6 on 2021-10-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_form_fields_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='parameters',
            field=models.CharField(max_length=1024, null=True, verbose_name='检查字段'),
        ),
    ]
