# Generated by Django 3.2.6 on 2021-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_rule_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='expression',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='表达式'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parameters',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='检查字段'),
        ),
    ]
