# Generated by Django 3.2.6 on 2021-10-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20211024_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='expression',
            field=models.TextField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=1024, null=True, verbose_name='表达式'),
        ),
    ]
