# Generated by Django 3.2.6 on 2021-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_rule_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='expression',
            field=models.TextField(blank=True, help_text='\n\t\t表达式接受数字和字符，字符需要放在""中，如"A0101"\n\t\t表达式接受以下逻辑运算符：\n\t\t\'or\', \'and\', \'not\', \'in\', \'>=\', \'<=\', \'>\', \'<\', \'==\', \'+\', \'-\', \'*\', \'/\', \'^\', \'(\', \')\'\n\t\t', max_length=1024, null=True, verbose_name='表达式'),
        ),
    ]
