# Generated by Django 3.2.6 on 2021-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_rule_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='expression',
            field=models.TextField(blank=True, help_text='\n\t\t表达式接受数字和字符，字符需要放在双引号中，如"A0101"<br>\n\t\t表达式接受以下逻辑运算符：\'or\', \'and\', \'not\', \'in\', \'>=\', \'<=\', \'>\', \'<\', \'==\', \'+\', \'-\', \'*\', \'/\', \'^\', \'(\', \')\'<br>\n\t\t字段名只允许由小写字母a~z，数字0~9和下划线_组成\n\t\t', max_length=1024, null=True, verbose_name='表达式'),
        ),
    ]
