# Generated by Django 3.2.6 on 2021-10-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20211026_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_event', to='core.event', verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_rule', to='core.rule', verbose_name='规则'),
        ),
    ]
