# Generated by Django 3.2.6 on 2021-10-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20211026_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rule',
        ),
        migrations.AddField(
            model_name='rule',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event', verbose_name='规则'),
        ),
    ]
