# Generated by Django 3.2.6 on 2021-11-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20211027_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expression',
            field=models.TextField(blank=True, help_text='\n\t\t说明：<br>\n\t\t1. 表达式接受的逻辑运算符：or, and, not, in, >=, <=, >, <, ==, +, -, *, /, ^, ()<br>\n\t\t2. 字段名只允许由小写字母a~z，数字0~9和下划线_组成；字段值接受数字和字符，字符需要放在双引号中，如"A0101"\n\t\t', max_length=1024, null=True, verbose_name='表达式'),
        ),
        migrations.AddField(
            model_name='event',
            name='parameters',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='检查字段'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
