# Generated by Django 3.2.6 on 2021-11-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='视图名称')),
                ('display_fields', models.TextField(blank=True, max_length=1024, null=True, verbose_name='表单字段')),
                ('style', models.CharField(choices=[('detail', '详情'), ('list', '列表')], default='detail', max_length=50, verbose_name='风格')),
            ],
            options={
                'verbose_name': '基础视图',
                'verbose_name_plural': '基础视图',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('CharField', '单行文本'), ('TextField', '多行文本')], default='CharField', max_length=50, verbose_name='类型')),
                ('length', models.PositiveSmallIntegerField(default=255, verbose_name='字符长度')),
            ],
            options={
                'verbose_name': '字符字段',
                'verbose_name_plural': '字符字段',
            },
        ),
        migrations.CreateModel(
            name='ChoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('ChoiceField', '单选'), ('MultipleChoiceField', '多选')], default='ChoiceField', max_length=50, verbose_name='类型')),
                ('Options', models.CharField(blank=True, help_text='选项之间用空格隔开', max_length=255, null=True, verbose_name='选项')),
                ('first_default', models.BooleanField(default=False, verbose_name='默认选中第一个')),
            ],
            options={
                'verbose_name': '选择字段',
                'verbose_name_plural': '选择字段',
            },
        ),
        migrations.CreateModel(
            name='ComputeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DTField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('DateField', '日期'), ('DateTimeField', '日期时间')], default='DateField', max_length=50, verbose_name='类型')),
            ],
            options={
                'verbose_name': '日期字段',
                'verbose_name_plural': '日期字段',
            },
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('FloatField', '浮点数')], default='IntegerField', max_length=50, verbose_name='类型')),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='最大位数')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='小数位数')),
                ('standard_value', models.FloatField(blank=True, null=True, verbose_name='标准值')),
                ('up_limit', models.FloatField(blank=True, null=True, verbose_name='上限')),
                ('down_limit', models.FloatField(blank=True, null=True, verbose_name='下限')),
                ('display_unit', models.BooleanField(default=False, verbose_name='显示单位')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
            ],
            options={
                'verbose_name': '数值字段',
                'verbose_name_plural': '数值字段',
            },
        ),
        migrations.CreateModel(
            name='RelatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('dic', '关联字典'), ('sys', '关联系统表')], default='dic', max_length=50, verbose_name='类型')),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '字典字段',
                'verbose_name_plural': '字典字段',
            },
        ),
        migrations.CreateModel(
            name='OperandView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('axis_field', models.CharField(choices=[('customer', '客户'), ('staff', '员工'), ('medicine', '药品'), ('device', '设备')], default='customer', max_length=255, verbose_name='关联字段')),
                ('inquire_forms', models.ManyToManyField(related_name='inquire_forms', to='customized_forms.BaseForm', verbose_name='用于查询的基本视图')),
                ('mutate_forms', models.ManyToManyField(related_name='mutate_forms', to='customized_forms.BaseForm', verbose_name='用于变更的基本视图')),
            ],
            options={
                'verbose_name': '作业视图',
                'verbose_name_plural': '作业视图',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '组件清单',
                'verbose_name_plural': '组件清单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('components', models.ManyToManyField(to='customized_forms.Component', verbose_name='组件清单')),
            ],
            options={
                'verbose_name': '基础表单',
                'verbose_name_plural': '基础表单',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='baseform',
            name='basemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customized_forms.basemodel', verbose_name='基础表单'),
        ),
    ]
