# Generated by Django 3.2.6 on 2021-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('field_type', models.CharField(choices=[('char_field', {}), ('text_field', {}), ('integer_field', {}), ('float_field', {}), ('select_field', {}), ('datetime_field', {}), ('calculated_field', {})], max_length=100, verbose_name='类型')),
                ('attribute', models.JSONField(verbose_name='属性')),
            ],
            options={
                'verbose_name': '组件',
                'verbose_name_plural': '组件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('label', models.CharField(max_length=100, verbose_name='子表单')),
                ('components', models.CharField(max_length=255, verbose_name='组件清单')),
                ('fields_list', models.TextField(blank=True, max_length=1024, null=True, verbose_name='表单字段')),
                ('style', models.CharField(choices=[('detail', '详情'), ('list', '列表')], default='detail', max_length=50, verbose_name='风格')),
            ],
            options={
                'verbose_name': '子表单',
                'verbose_name_plural': '子表单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operand_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('axis_field', models.CharField(choices=[('customer', '客户'), ('staff', '员工'), ('medicine', '药品'), ('device', '设备')], default='customer', max_length=255, verbose_name='关联字段')),
                ('inquire_forms', models.ManyToManyField(related_name='inquire_forms', to='customized_forms.SubForm', verbose_name='查询子表单')),
                ('mutate_forms', models.ManyToManyField(related_name='mutate_forms', to='customized_forms.SubForm', verbose_name='变更子表单')),
            ],
            options={
                'verbose_name': '作业表单',
                'verbose_name_plural': '作业表单',
                'ordering': ['id'],
            },
        ),
    ]
