# Generated by Django 3.2.6 on 2021-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='type',
            field=models.CharField(choices=[('mutate', '变更'), ('inquiry', '查询')], default='mutate', max_length=50, verbose_name='类型'),
        ),
    ]
