# Generated by Django 3.2.6 on 2021-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0002_baseform_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseform',
            name='type',
        ),
        migrations.AddField(
            model_name='baseform',
            name='is_inquiry',
            field=models.BooleanField(default=False, verbose_name='仅用于查询'),
        ),
        migrations.AlterField(
            model_name='operandview',
            name='inquire_forms',
            field=models.ManyToManyField(limit_choices_to={'is_inquiry': True}, related_name='inquire_forms', to='customized_forms.BaseForm', verbose_name='用于查询的基本视图'),
        ),
        migrations.AlterField(
            model_name='operandview',
            name='mutate_forms',
            field=models.ManyToManyField(limit_choices_to={'is_inquiry': False}, related_name='mutate_forms', to='customized_forms.BaseForm', verbose_name='用于变更的基本视图'),
        ),
    ]
