# Generated by Django 3.2.6 on 2021-11-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customized_forms', '0002_auto_20211123_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='field_type',
        ),
        migrations.AddField(
            model_name='component',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='component',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
