# Generated by Django 3.2.6 on 2021-11-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0002_alter_component_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operand_form',
            name='meta_form',
        ),
        migrations.AddField(
            model_name='operand_form',
            name='axis_field',
            field=models.CharField(default='customer', max_length=255, verbose_name='主轴字段'),
        ),
        migrations.AlterField(
            model_name='operand_form',
            name='layout',
            field=models.CharField(choices=[('monomer', '单体'), ('pagination', '分页'), ('tab', '标签页')], default='monomer', max_length=100, verbose_name='布局'),
        ),
    ]
