# Generated by Django 3.2.6 on 2021-11-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customized_forms', '0003_auto_20211125_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'customized_forms'), models.Q(('model', 'characterfield'), ('model', 'numberfield'), ('model', 'dtextfield'), ('model', 'choicefield'), ('model', 'relatedfield'), ('model', 'computefield'), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
