# Generated by Django 3.2.6 on 2021-11-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0003_auto_20211124_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('FloatField', '浮点数')], default='IntegerField', max_length=50, verbose_name='类型')),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='最大位数')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='小数位数')),
                ('standard_value', models.FloatField(blank=True, null=True, verbose_name='标准值')),
                ('up_limit', models.FloatField(blank=True, null=True, verbose_name='上限')),
                ('down_limit', models.FloatField(blank=True, null=True, verbose_name='下限')),
                ('display_unit', models.BooleanField(default=False, verbose_name='是否显示单位')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
            ],
        ),
        migrations.DeleteModel(
            name='FloatField',
        ),
        migrations.DeleteModel(
            name='IntegerField',
        ),
        migrations.DeleteModel(
            name='TextField',
        ),
        migrations.AddField(
            model_name='charfield',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称'),
        ),
        migrations.AddField(
            model_name='charfield',
            name='length',
            field=models.PositiveSmallIntegerField(default=255, verbose_name='字符长度'),
        ),
        migrations.AddField(
            model_name='charfield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='charfield',
            name='type',
            field=models.CharField(choices=[('CharField', '单行文本'), ('TextField', '多行文本')], default='CharField', max_length=50, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='datetimefield',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称'),
        ),
        migrations.AddField(
            model_name='datetimefield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='datetimefield',
            name='type',
            field=models.CharField(choices=[('DateField', '日期'), ('DateTimeField', '日期时间')], default='DateField', max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='component',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='subform',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='子表单'),
        ),
    ]
