# Generated by Django 3.2.6 on 2021-11-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20211102_2022'),
        ('customized_forms', '0003_auto_20211108_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operand_form',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='operand_form',
            name='subforms',
        ),
        migrations.AddField(
            model_name='operand_form',
            name='inquire_forms',
            field=models.ManyToManyField(related_name='inquire_forms', to='core.Form', verbose_name='查询表单'),
        ),
        migrations.AddField(
            model_name='operand_form',
            name='mutate_forms',
            field=models.ManyToManyField(related_name='mutate_forms', to='core.Form', verbose_name='变更表单'),
        ),
        migrations.AlterField(
            model_name='operand_form',
            name='axis_field',
            field=models.CharField(default='customer', max_length=255, verbose_name='关联字段'),
        ),
    ]
