# Generated by Django 3.2.6 on 2021-11-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0004_auto_20211110_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='subform',
            name='fields_list',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='operand_form',
            name='inquire_forms',
            field=models.ManyToManyField(related_name='inquire_forms', to='customized_forms.SubForm', verbose_name='查询子表单'),
        ),
        migrations.AlterField(
            model_name='operand_form',
            name='mutate_forms',
            field=models.ManyToManyField(related_name='mutate_forms', to='customized_forms.SubForm', verbose_name='变更子表单'),
        ),
        migrations.AlterField(
            model_name='subform',
            name='style',
            field=models.CharField(choices=[('detail', '详情'), ('list', '列表')], default='detail', max_length=50, verbose_name='风格'),
        ),
    ]
