# Generated by Django 3.2.6 on 2021-11-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0005_auto_20211124_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharField',
            new_name='CharacterField',
        ),
        migrations.RenameModel(
            old_name='DateTimeField',
            new_name='DTField',
        ),
    ]
