# Generated by Django 3.2.6 on 2021-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0005_auto_20211126_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedfield',
            options={'verbose_name': '关联字段', 'verbose_name_plural': '关联字段'},
        ),
        migrations.RemoveField(
            model_name='choicefield',
            name='Options',
        ),
        migrations.RemoveField(
            model_name='relatedfield',
            name='type',
        ),
        migrations.AddField(
            model_name='choicefield',
            name='is_dic',
            field=models.BooleanField(default=False, verbose_name='是否字典'),
        ),
        migrations.AddField(
            model_name='choicefield',
            name='options',
            field=models.TextField(blank=True, help_text='每行一个选项, 最多100个', max_length=1024, null=True, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='relatedfield',
            name='related_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段'),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='type',
            field=models.CharField(choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], default='ChoiceField', max_length=50, verbose_name='类型'),
        ),
    ]
