# Generated by Django 3.2.6 on 2021-11-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0006_auto_20211124_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subform',
            options={'ordering': ['id'], 'verbose_name': '子视图', 'verbose_name_plural': '子视图'},
        ),
        migrations.RenameField(
            model_name='subform',
            old_name='fields_list',
            new_name='display_fields',
        ),
        migrations.RemoveField(
            model_name='subform',
            name='components',
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='display_unit',
            field=models.BooleanField(default=False, verbose_name='显示单位'),
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('components', models.ManyToManyField(to='customized_forms.Component', verbose_name='组件清单')),
            ],
            options={
                'verbose_name': '子表单',
                'verbose_name_plural': '子表单',
                'ordering': ['id'],
            },
        ),
    ]
