# Generated by Django 3.2.6 on 2021-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0006_auto_20211127_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='characterfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='characterfield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dtfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='dtfield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='operandview',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relatedfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='relatedfield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
