# Generated by Django 3.2.6 on 2021-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0006_auto_20211110_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operand_form',
            name='inquire_forms',
            field=models.ManyToManyField(related_name='inquire_forms', to='customized_forms.SubForm', verbose_name='查询子表单'),
        ),
        migrations.AlterField(
            model_name='operand_form',
            name='mutate_forms',
            field=models.ManyToManyField(related_name='mutate_forms', to='customized_forms.SubForm', verbose_name='变更子表单'),
        ),
    ]
