# Generated by Django 3.2.6 on 2021-11-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0007_auto_20211110_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operand_form',
            name='axis_field',
            field=models.CharField(choices=[('customer', '客户'), ('staff', '员工'), ('medicine', '药品'), ('device', '设备')], default='customer', max_length=255, verbose_name='作业对象'),
        ),
    ]
