# Generated by Django 3.2.6 on 2021-11-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0007_auto_20211127_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operandview',
            name='inquire_forms',
            field=models.ManyToManyField(limit_choices_to={'is_inquiry': True}, related_name='inquire_forms', to='customized_forms.BaseForm', verbose_name='查询视图'),
        ),
        migrations.AlterField(
            model_name='operandview',
            name='mutate_forms',
            field=models.ManyToManyField(limit_choices_to={'is_inquiry': False}, related_name='mutate_forms', to='customized_forms.BaseForm', verbose_name='变更视图'),
        ),
    ]
