# Generated by Django 3.2.6 on 2021-11-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0007_auto_20211124_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubModel',
            new_name='BaseModel',
        ),
        migrations.AlterModelOptions(
            name='basemodel',
            options={'ordering': ['id'], 'verbose_name': '基础表单', 'verbose_name_plural': '基础表单'},
        ),
        migrations.AlterModelOptions(
            name='operandview',
            options={'ordering': ['id'], 'verbose_name': '作业视图', 'verbose_name_plural': '作业视图'},
        ),
    ]
