# Generated by Django 3.2.6 on 2021-11-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customized_forms', '0008_auto_20211124_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicefield',
            options={'verbose_name': '选择字段', 'verbose_name_plural': '选择字段'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '基础组件', 'verbose_name_plural': '基础组件'},
        ),
        migrations.AlterModelOptions(
            name='subform',
            options={'ordering': ['id'], 'verbose_name': '基础视图', 'verbose_name_plural': '基础视图'},
        ),
        migrations.AddField(
            model_name='choicefield',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称'),
        ),
        migrations.AddField(
            model_name='choicefield',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='choicefield',
            name='type',
            field=models.CharField(choices=[('ChoiceField', '单选'), ('MultipleChoiceField', '多选')], default='ChoiceField', max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='RelatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('dic', '关联字典'), ('sys', '关联系统表')], default='dic', max_length=50, verbose_name='类型')),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '关联字段',
                'verbose_name_plural': '关联字段',
            },
        ),
    ]
