# Generated by Django 3.2.6 on 2021-11-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0008_auto_20211128_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicefield',
            name='is_dic',
        ),
        migrations.AddField(
            model_name='choicefield',
            name='is_dictionary',
            field=models.BooleanField(default=False, verbose_name='存为字典'),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='first_default',
            field=models.BooleanField(default=False, verbose_name='默认选第一个'),
        ),
        migrations.AlterField(
            model_name='dtfield',
            name='type',
            field=models.CharField(choices=[('DateTimeField', '日期时间'), ('DateField', '日期')], default='DateTimeField', max_length=50, verbose_name='类型'),
        ),
    ]
