# Generated by Django 3.2.6 on 2021-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0009_auto_20211128_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterfield',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值'),
        ),
        migrations.AddField(
            model_name='characterfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='必填'),
        ),
        migrations.AlterField(
            model_name='operandview',
            name='inquire_forms',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_inquiry': True}, null=True, related_name='inquire_forms', to='customized_forms.BaseForm', verbose_name='查询视图'),
        ),
    ]
