# Generated by Django 3.2.6 on 2021-11-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0012_alter_numberfield_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberfield',
            name='max_digits',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='最大位数'),
        ),
    ]
