# Generated by Django 3.2.6 on 2021-11-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0013_alter_numberfield_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberfield',
            name='default',
            field=models.FloatField(blank=True, null=True, verbose_name='默认值'),
        ),
    ]
