# Generated by Django 3.2.6 on 2021-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0014_numberfield_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfield',
            name='default_now',
            field=models.BooleanField(default=False, verbose_name='默认当前时间'),
        ),
        migrations.AddField(
            model_name='dtfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='必填'),
        ),
    ]
