# Generated by Django 3.2.6 on 2021-11-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0015_auto_20211129_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtfield',
            name='default_now',
            field=models.BooleanField(default=False, verbose_name='默认为当前时间'),
        ),
    ]
