# Generated by Django 3.2.6 on 2021-11-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0016_alter_dtfield_default_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicefield',
            name='is_dictionary',
        ),
        migrations.AddField(
            model_name='relatedfield',
            name='type',
            field=models.CharField(choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], default='ChoiceField', max_length=50, verbose_name='类型'),
        ),
    ]
