# Generated by Django 3.2.6 on 2021-11-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0017_auto_20211129_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicefield',
            old_name='first_default',
            new_name='default_first',
        ),
        migrations.AddField(
            model_name='choicefield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='必填'),
        ),
    ]
