# Generated by Django 3.2.6 on 2021-12-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized_forms', '0020_alter_operandview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '字段字典', 'verbose_name_plural': '字段字典'},
        ),
    ]
