# Generated by Django 3.2.6 on 2022-08-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_jiu_zhen_ji_gou_fu_ze_ren'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chong_xin_yu_yue_an_pai',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_chong_xin_yu_yue_an_pai', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='fen_zhen_que_ren',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_fen_zhen_que_ren', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='shou_ci_dao_dian_que_ren',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_shou_ci_dao_dian_que_ren', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='yu_yue_an_pai',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_yu_yue_an_pai', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='yu_yue_que_ren',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_yu_yue_que_ren', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='yu_yue_zi_xun',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_yu_yue_zi_xun', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='zhen_suo_yu_yue',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiu_zhen_ji_gou_fu_ze_ren_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_zhen_suo_yu_yue', to='dictionaries.jiu_zhen_ji_gou_fu_ze_ren', verbose_name='就诊机构责任人'),
        ),
    ]
