# Generated by Django 3.2.6 on 2022-09-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220927_1729'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerschedule',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
        migrations.AlterField(
            model_name='customerscheduledraft',
            name='cycle_unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cycleunit', verbose_name='周期单位'),
        ),
    ]
