# Generated by Django 3.2.6 on 2022-10-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerschedule',
            name='cpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedule_sid', to='core.contractserviceproc', verbose_name='服务进程id'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerschedule_creater', to='core.customer', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerschedule_operator', to='core.customer', verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='pid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedule_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='updated_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='schedule_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customerschedulepackage', verbose_name='服务包'),
        ),
    ]
