# Generated by Django 3.2.6 on 2023-06-11 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('core', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_dan_ci_yong_yao_liang',
        ),
        migrations.RemoveField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_yao_pin_ming',
        ),
        migrations.RemoveField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_yong_yao_liao_cheng',
        ),
        migrations.RemoveField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_yong_yao_pin_ci',
        ),
        migrations.RemoveField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_yong_yao_tu_jing',
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 6, 4, 11, 47, 22, 702468)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.CreateModel(
            name='Chu_fang_ming_xi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_yong_yao_liao_cheng', models.CharField(blank=True, max_length=255, null=True, verbose_name='用药疗程')),
                ('boolfield_dan_ci_yong_yao_liang', models.CharField(blank=True, max_length=255, null=True, verbose_name='单次用药量')),
                ('boolfield_yong_yao_pin_ci', models.CharField(blank=True, max_length=255, null=True, verbose_name='用药频次')),
                ('boolfield_yao_pin_ming', models.ManyToManyField(blank=True, related_name='medicine_for_boolfield_yao_pin_ming_chu_fang_ming_xi', to='core.Medicine', verbose_name='药品名')),
                ('boolfield_yong_yao_tu_jing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yong_yao_tu_jing_for_boolfield_yong_yao_tu_jing_chu_fang_ming_xi', to='dictionaries.yong_yao_tu_jing', verbose_name='用药途径')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_fang_ming_xi_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_fang_ming_xi_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_fang_ming_xi_customer', to='core.customer', verbose_name='客户')),
                ('ji_bing_ming_cheng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men_zhen_chu_fang_biao_for_boolfield_ji_bing_ming_cheng_chu_fang_ming_xi', to='service.men_zhen_chu_fang_biao', verbose_name='疾病名称')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chu_fang_ming_xi_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_fang_ming_xi_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '处方明细',
                'verbose_name_plural': '处方明细',
            },
        ),
    ]
