# Generated by Django 3.2.6 on 2022-05-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a6201',
            name='boolfield_chang_yong_zheng_zhuang',
            field=models.ManyToManyField(blank=True, related_name='chang_yong_zheng_zhuang_for_boolfield_chang_yong_zheng_zhuang_A6201', to='dictionaries.Chang_yong_zheng_zhuang', verbose_name='常用症状'),
        ),
        migrations.AlterField(
            model_name='a6201',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_A6201', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='a6202',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_A6202', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='a6217',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_A6217', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='a6218',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_A6218', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='boolfield_jia_zu_bing_shi_cheng_yuan',
            field=models.ManyToManyField(blank=True, related_name='qin_shu_guan_xi_for_boolfield_jia_zu_bing_shi_cheng_yuan_A6299', to='dictionaries.Qin_shu_guan_xi', verbose_name='家族病史成员'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='boolfield_yi_chuan_bing_shi_cheng_yuan',
            field=models.ManyToManyField(blank=True, related_name='qin_shu_guan_xi_for_boolfield_yi_chuan_bing_shi_cheng_yuan_A6299', to='dictionaries.Qin_shu_guan_xi', verbose_name='遗传病史成员'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='relatedfield_compared_to_last_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_expression_for_relatedfield_compared_to_last_year_A6299', to='dictionaries.comparative_expression', verbose_name='较之过去一年状态如何'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(blank=True, related_name='yao_pin_ji_ben_xin_xi_biao_for_relatedfield_drug_name_A6299', to='service.Yao_pin_ji_ben_xin_xi_biao', verbose_name='药品名'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='relatedfield_have_any_recent_symptoms_of_physical_discomfort',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_have_any_recent_symptoms_of_physical_discomfort_A6299', to='icpc.Icpc3_symptoms_and_problems', verbose_name='近来有无身体不适症状'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='relatedfield_own_health',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_degree_for_relatedfield_own_health_A6299', to='dictionaries.state_degree', verbose_name='觉得自身健康状况如何'),
        ),
        migrations.AlterField(
            model_name='a6501',
            name='datetimefield_ri_qi_shi_jian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='ju_min_ji_ben_xin_xi_diao_cha',
            name='relatedfield_medical_expenses_burden',
            field=models.ManyToManyField(blank=True, related_name='medical_expenses_burden_for_relatedfield_medical_expenses_burden_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.Medical_expenses_burden', verbose_name='医疗费用负担'),
        ),
        migrations.AlterField(
            model_name='men_zhen_chu_fang_biao',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(blank=True, related_name='yao_pin_ji_ben_xin_xi_biao_for_relatedfield_drug_name_men_zhen_chu_fang_biao', to='service.Yao_pin_ji_ben_xin_xi_biao', verbose_name='药品名'),
        ),
        migrations.AlterField(
            model_name='shu_ye_zhu_she',
            name='boolfield_zhu_she_ri_qi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='注射日期'),
        ),
        migrations.AlterField(
            model_name='shu_ye_zhu_she',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(blank=True, related_name='yao_pin_ji_ben_xin_xi_biao_for_relatedfield_drug_name_shu_ye_zhu_she', to='service.Yao_pin_ji_ben_xin_xi_biao', verbose_name='药品名'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='boolfield_tang_niao_bing_zheng_zhuang',
            field=models.ManyToManyField(blank=True, related_name='tang_niao_bing_zheng_zhuang_for_boolfield_tang_niao_bing_zheng_zhuang_T6301', to='dictionaries.Tang_niao_bing_zheng_zhuang', verbose_name='糖尿病症状'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(blank=True, related_name='yao_pin_ji_ben_xin_xi_biao_for_relatedfield_drug_name_T6301', to='service.Yao_pin_ji_ben_xin_xi_biao', verbose_name='药品名'),
        ),
        migrations.AlterField(
            model_name='t8901',
            name='relatedfield_pai_chu_zhen_duan',
            field=models.ManyToManyField(blank=True, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_pai_chu_zhen_duan_T8901', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='排除诊断'),
        ),
        migrations.AlterField(
            model_name='t8901',
            name='relatedfield_yi_lou_zhen_duan',
            field=models.ManyToManyField(blank=True, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_yi_lou_zhen_duan_T8901', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='可能诊断'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='relatedfield_pai_chu_zhen_duan',
            field=models.ManyToManyField(blank=True, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_pai_chu_zhen_duan_T9001', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='排除诊断'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='relatedfield_yi_lou_zhen_duan',
            field=models.ManyToManyField(blank=True, related_name='icpc5_evaluation_and_diagnoses_for_relatedfield_yi_lou_zhen_duan_T9001', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='可能诊断'),
        ),
        migrations.AlterField(
            model_name='tang_niao_bing_zhuan_yong_wen_zhen',
            name='boolfield_tang_niao_bing_zheng_zhuang',
            field=models.ManyToManyField(blank=True, related_name='tang_niao_bing_zheng_zhuang_for_boolfield_tang_niao_bing_zheng_zhuang_tang_niao_bing_zhuan_yong_wen_zhen', to='dictionaries.Tang_niao_bing_zheng_zhuang', verbose_name='糖尿病症状'),
        ),
        migrations.AlterField(
            model_name='tang_niao_bing_zhuan_yong_wen_zhen',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_tang_niao_bing_zhuan_yong_wen_zhen', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='yao_shi_fu_wu',
            name='relatedfield_drug_name',
            field=models.ManyToManyField(blank=True, related_name='yao_pin_ji_ben_xin_xi_biao_for_relatedfield_drug_name_yao_shi_fu_wu', to='service.Yao_pin_ji_ben_xin_xi_biao', verbose_name='药品名'),
        ),
        migrations.AlterField(
            model_name='zhi_yuan_ji_ben_xin_xi_biao',
            name='relatedfield_service_role',
            field=models.ManyToManyField(blank=True, related_name='fu_wu_jue_se_for_relatedfield_service_role_zhi_yuan_ji_ben_xin_xi_biao', to='dictionaries.Fu_wu_jue_se', verbose_name='服务角色'),
        ),
    ]
