# Generated by Django 3.2.6 on 2022-06-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yu_yue_zi_xun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('characterfield_name', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('characterfield_gender', models.CharField(max_length=255, null=True, verbose_name='被保人性别')),
                ('datetimefield_date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('boolfield_chang_zhu_di_zhi', models.CharField(max_length=255, null=True, verbose_name='常住地址')),
                ('datetimefield_ri_qi_shi_jian', models.DateTimeField(null=True, verbose_name='预约时间')),
                ('boolfield_jiu_zhen_wen_ti', models.CharField(max_length=255, null=True, verbose_name='就诊问题')),
                ('boolfield_fu_jia_fu_wu_yao_qiu', models.CharField(blank=True, max_length=255, null=True, verbose_name='附加服务要求')),
                ('boolfield_shi_yong_bao_xian_chan_pin', models.ManyToManyField(blank=True, related_name='bao_xian_chan_pin_for_boolfield_shi_yong_bao_xian_chan_pin_yu_yue_zi_xun', to='dictionaries.Bao_xian_chan_pin', verbose_name='使用服务产品')),
                ('boolfield_ze_ren_ren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ji_gou_ji_ben_xin_xi_biao_for_boolfield_ze_ren_ren_yu_yue_zi_xun', to='service.ji_gou_ji_ben_xin_xi_biao', verbose_name='就诊机构')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yu_yue_zi_xun_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_yue_zi_xun_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_yue_zi_xun_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_yue_zi_xun_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yu_yue_zi_xun_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '预约咨询',
                'verbose_name_plural': '预约咨询',
            },
        ),
    ]
