# Generated by Django 3.2.6 on 2022-06-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_fu_jia_fu_wu_yao_qiu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附加服务要求'),
        ),
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_yu_yue_tong_zhi', to='core.staff', verbose_name='就诊机构责任人'),
        ),
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_jiu_zhen_wen_ti',
            field=models.CharField(max_length=255, null=True, verbose_name='就诊问题'),
        ),
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_shi_yong_bao_xian_chan_pin',
            field=models.ManyToManyField(blank=True, related_name='bao_xian_chan_pin_for_boolfield_shi_yong_bao_xian_chan_pin_yu_yue_tong_zhi', to='dictionaries.Bao_xian_chan_pin', verbose_name='使用服务产品'),
        ),
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='datetimefield_ri_qi_shi_jian',
            field=models.DateTimeField(null=True, verbose_name='预约时间'),
        ),
    ]
