# Generated by Django 3.2.6 on 2022-06-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='datetimefield_ri_qi_shi_jian',
        ),
    ]
