# Generated by Django 3.2.6 on 2022-05-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a6299',
            options={'verbose_name': '居民健康信息调查', 'verbose_name_plural': '居民健康信息调查'},
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='characterfield_family_address',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='characterfield_medical_ic_card_number',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='characterfield_resident_file_number',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='characterhssc_identification_number',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='datetimefield_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_blood_type',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_education',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_family_relationship',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_gender',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_marital_status',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_medical_expenses_burden',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_nationality',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_occupational_status',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_signed_family_doctor',
        ),
        migrations.RemoveField(
            model_name='a6299',
            name='relatedfield_type_of_residence',
        ),
        migrations.CreateModel(
            name='Ju_min_ji_ben_xin_xi_diao_cha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('characterfield_gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='性别')),
                ('characterfield_age', models.CharField(blank=True, max_length=255, null=True, verbose_name='年龄')),
                ('characterfield_contact_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系地址')),
                ('characterfield_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('characterhssc_identification_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号码')),
                ('characterfield_resident_file_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='居民档案号')),
                ('characterfield_family_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭地址')),
                ('characterfield_contact_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系电话')),
                ('characterfield_medical_ic_card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='医疗ic卡号')),
                ('datetimefield_date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ju_min_ji_ben_xin_xi_diao_cha_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ju_min_ji_ben_xin_xi_diao_cha_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ju_min_ji_ben_xin_xi_diao_cha_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ju_min_ji_ben_xin_xi_diao_cha_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ju_min_ji_ben_xin_xi_diao_cha_pid', to='core.operationproc', verbose_name='作业进程id')),
                ('relatedfield_blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_type_for_relatedfield_blood_type_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.blood_type', verbose_name='血型')),
                ('relatedfield_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_for_relatedfield_education_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.education', verbose_name='文化程度')),
                ('relatedfield_family_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_relationship_for_relatedfield_family_relationship_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.family_relationship', verbose_name='家庭成员关系')),
                ('relatedfield_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_for_relatedfield_gender_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.gender', verbose_name='性别')),
                ('relatedfield_marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marital_status_for_relatedfield_marital_status_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.marital_status', verbose_name='婚姻状况')),
                ('relatedfield_medical_expenses_burden', models.ManyToManyField(related_name='medical_expenses_burden_for_relatedfield_medical_expenses_burden_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.Medical_expenses_burden', verbose_name='医疗费用负担')),
                ('relatedfield_nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality_for_relatedfield_nationality_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.nationality', verbose_name='民族')),
                ('relatedfield_occupational_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupational_status_for_relatedfield_occupational_status_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.occupational_status', verbose_name='职业状况')),
                ('relatedfield_signed_family_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_relatedfield_signed_family_doctor_ju_min_ji_ben_xin_xi_diao_cha', to='core.staff', verbose_name='签约家庭医生')),
                ('relatedfield_type_of_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_residence_for_relatedfield_type_of_residence_ju_min_ji_ben_xin_xi_diao_cha', to='dictionaries.type_of_residence', verbose_name='居住类型')),
            ],
            options={
                'verbose_name': '居民基本信息调查',
                'verbose_name_plural': '居民基本信息调查',
            },
        ),
    ]
