# Generated by Django 3.2.6 on 2022-10-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerschedulelist',
            name='schedule_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customerschedulepackage', verbose_name='服务包'),
        ),
    ]
