# Generated by Django 3.2.6 on 2022-06-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_xin_xi_que_ren'),
        ('core', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bao_xian_yong_hu_zhu_ce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('characterfield_gender', models.CharField(max_length=255, null=True, verbose_name='被保人性别')),
                ('characterfield_name', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('boolfield_chang_zhu_di_zhi', models.CharField(max_length=255, null=True, verbose_name='常住地址')),
                ('datetimefield_date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('characterfield_password_setting', models.CharField(max_length=255, null=True, verbose_name='密码设置')),
                ('characterfield_confirm_password', models.CharField(max_length=255, null=True, verbose_name='确认密码')),
                ('characterfield_username', models.CharField(max_length=255, null=True, verbose_name='用户名')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bao_xian_yong_hu_zhu_ce_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bao_xian_yong_hu_zhu_ce_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bao_xian_yong_hu_zhu_ce_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bao_xian_yong_hu_zhu_ce_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bao_xian_yong_hu_zhu_ce_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '保险用户注册',
                'verbose_name_plural': '保险用户注册',
            },
        ),
        migrations.CreateModel(
            name='Bei_bao_ren_ji_ben_xin_xi_que_ren',
            fields=[
                ('hsscbaseformmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.hsscbaseformmodel')),
                ('characterfield_gender', models.CharField(max_length=255, null=True, verbose_name='被保人性别')),
                ('characterhssc_identification_number', models.CharField(max_length=255, null=True, verbose_name='证件号码')),
                ('characterfield_name', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('boolfield_xu_hao', models.CharField(max_length=255, null=True, verbose_name='序号')),
                ('boolfield_bao_dan_hao', models.CharField(max_length=255, null=True, verbose_name='保单号')),
                ('boolfield_bao_xian_ze_ren', models.CharField(max_length=255, null=True, verbose_name='保险责任')),
                ('boolfield_chang_zhu_di_zhi', models.CharField(max_length=255, null=True, verbose_name='常住地址')),
                ('boolfield_lian_xi_dian_hua', models.CharField(max_length=255, null=True, verbose_name='联系电话')),
                ('datetimefield_date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('boolfield_bao_xian_you_xiao_qi', models.DateField(null=True, verbose_name='保险有效期')),
                ('boolfield_ju_jue_bang_ding_yuan_yin', models.CharField(blank=True, max_length=255, null=True, verbose_name='拒绝绑定原因')),
                ('boolfield_que_ren_ji_ben_xin_xi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xin_xi_que_ren_for_boolfield_que_ren_ji_ben_xin_xi_bei_bao_ren_ji_ben_xin_xi_que_ren', to='dictionaries.xin_xi_que_ren', verbose_name='是否绑定被保人信息')),
                ('boolfield_zheng_jian_lei_xing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zheng_jian_lei_xing_for_boolfield_zheng_jian_lei_xing_bei_bao_ren_ji_ben_xin_xi_que_ren', to='dictionaries.zheng_jian_lei_xing', verbose_name='证件类型')),
            ],
            options={
                'verbose_name': '被保人基本信息绑定',
                'verbose_name_plural': '被保人基本信息绑定',
            },
            bases=('core.hsscbaseformmodel',),
        ),
        migrations.CreateModel(
            name='Chong_xin_yu_yue_an_pai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('characterfield_gender', models.CharField(max_length=255, null=True, verbose_name='被保人性别')),
                ('characterfield_name', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('boolfield_chang_zhu_di_zhi', models.CharField(max_length=255, null=True, verbose_name='常住地址')),
                ('datetimefield_date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('boolfield_jiu_zhen_wen_ti', models.CharField(max_length=255, null=True, verbose_name='就诊问题')),
                ('boolfield_fu_jia_fu_wu_yao_qiu', models.CharField(blank=True, max_length=255, null=True, verbose_name='附加服务要求')),
                ('datetimefield_ri_qi_shi_jian', models.DateTimeField(null=True, verbose_name='预约时间')),
                ('boolfield_jiu_zhen_ji_gou_ze_ren_ren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_chong_xin_yu_yue_an_pai', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='就诊机构责任人')),
                ('boolfield_qian_dao_que_ren', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jie_dan_que_ren_for_boolfield_qian_dao_que_ren_chong_xin_yu_yue_an_pai', to='dictionaries.jie_dan_que_ren', verbose_name='接单确认')),
                ('boolfield_shi_yong_bao_xian_chan_pin', models.ManyToManyField(blank=True, related_name='bao_xian_chan_pin_for_boolfield_shi_yong_bao_xian_chan_pin_chong_xin_yu_yue_an_pai', to='dictionaries.Bao_xian_chan_pin', verbose_name='使用服务产品')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chong_xin_yu_yue_an_pai_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chong_xin_yu_yue_an_pai_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chong_xin_yu_yue_an_pai_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chong_xin_yu_yue_an_pai_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chong_xin_yu_yue_an_pai_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '重新预约安排',
                'verbose_name_plural': '重新预约安排',
            },
        ),
        migrations.AlterModelOptions(
            name='yu_yue_an_pai',
            options={'verbose_name': '平台安排责任人', 'verbose_name_plural': '平台安排责任人'},
        ),
        migrations.AlterModelOptions(
            name='zhen_suo_yu_yue',
            options={'verbose_name': '诊所安排', 'verbose_name_plural': '诊所安排'},
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='boolfield_bao_dan_hao',
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='boolfield_bao_xian_you_xiao_qi',
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='boolfield_bao_xian_ze_ren',
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='boolfield_lian_xi_dian_hua',
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='boolfield_xu_hao',
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='boolfield_zheng_jian_lei_xing',
        ),
        migrations.RemoveField(
            model_name='yu_yue_an_pai',
            name='characterhssc_identification_number',
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_ze_ren_ren',
        ),
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_ji_gou_ming_cheng',
            field=models.CharField(max_length=255, null=True, verbose_name='机构名称'),
        ),
        migrations.AddField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_yu_yue_tong_zhi', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='就诊机构责任人'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_chang_zhu_di_zhi',
            field=models.CharField(max_length=255, null=True, verbose_name='常住地址'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍/地区'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_hang_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_lian_xi_dian_hua',
            field=models.CharField(max_length=255, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_shen_qing_ren_xing_ming',
            field=models.CharField(max_length=255, null=True, verbose_name='申请人姓名'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_yu_chu_xian_ren_guan_xi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_chu_xian_ren_guan_xi_for_boolfield_yu_chu_xian_ren_guan_xi_li_pei_shen_qing_chong_shen', to='dictionaries.yu_chu_xian_ren_guan_xi', verbose_name='与出险人关系'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_zheng_jian_you_xiao_qi',
            field=models.CharField(max_length=255, null=True, verbose_name='证件有效期'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_zhi_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='characterhssc_identification_number',
            field=models.CharField(max_length=255, null=True, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_chang_zhu_di_zhi',
            field=models.CharField(max_length=255, null=True, verbose_name='常住地址'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍/地区'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_hang_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_lian_xi_dian_hua',
            field=models.CharField(max_length=255, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_shen_qing_ren_xing_ming',
            field=models.CharField(max_length=255, null=True, verbose_name='申请人姓名'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_yu_chu_xian_ren_guan_xi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_chu_xian_ren_guan_xi_for_boolfield_yu_chu_xian_ren_guan_xi_li_pei_shen_qing_fu_wu', to='dictionaries.yu_chu_xian_ren_guan_xi', verbose_name='与出险人关系'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_zheng_jian_you_xiao_qi',
            field=models.CharField(max_length=255, null=True, verbose_name='证件有效期'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_zhi_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='characterhssc_identification_number',
            field=models.CharField(max_length=255, null=True, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chang_zhu_di_zhi',
            field=models.CharField(max_length=255, null=True, verbose_name='常住地址'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍/地区'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_hang_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_lian_xi_dian_hua',
            field=models.CharField(max_length=255, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_shen_qing_ren_xing_ming',
            field=models.CharField(max_length=255, null=True, verbose_name='申请人姓名'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_yu_chu_xian_ren_guan_xi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_chu_xian_ren_guan_xi_for_boolfield_yu_chu_xian_ren_guan_xi_li_pei_shen_qing_shu_shen_he', to='dictionaries.yu_chu_xian_ren_guan_xi', verbose_name='与出险人关系'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_zheng_jian_you_xiao_qi',
            field=models.CharField(max_length=255, null=True, verbose_name='证件有效期'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_zhi_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='characterhssc_identification_number',
            field=models.CharField(max_length=255, null=True, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_chang_zhu_di_zhi',
            field=models.CharField(max_length=255, null=True, verbose_name='常住地址'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍/地区'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_hang_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_lian_xi_dian_hua',
            field=models.CharField(max_length=255, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_shen_qing_ren_xing_ming',
            field=models.CharField(max_length=255, null=True, verbose_name='申请人姓名'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_yu_chu_xian_ren_guan_xi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_chu_xian_ren_guan_xi_for_boolfield_yu_chu_xian_ren_guan_xi_ti_jiao_he_bao_zi_liao', to='dictionaries.yu_chu_xian_ren_guan_xi', verbose_name='与出险人关系'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_zheng_jian_you_xiao_qi',
            field=models.CharField(max_length=255, null=True, verbose_name='证件有效期'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_zhi_ye',
            field=models.CharField(max_length=255, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='characterhssc_identification_number',
            field=models.CharField(max_length=255, null=True, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='zhen_jian_sui_fang',
            name='boolfield_deng_hou_qing_kuang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deng_hou_shi_jian_for_boolfield_deng_hou_qing_kuang_zhen_jian_sui_fang', to='dictionaries.deng_hou_shi_jian', verbose_name='等候情况'),
        ),
        migrations.AlterField(
            model_name='zhen_jian_sui_fang',
            name='boolfield_jie_dai_fu_wu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jie_dai_fu_wu_for_boolfield_jie_dai_fu_wu_zhen_jian_sui_fang', to='dictionaries.jie_dai_fu_wu', verbose_name='接待服务'),
        ),
        migrations.AlterField(
            model_name='zhen_jian_sui_fang',
            name='boolfield_zhi_liao_jian_gou_tong_qing_kuang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gou_tong_qing_kuang_for_boolfield_zhi_liao_jian_gou_tong_qing_kuang_zhen_jian_sui_fang', to='dictionaries.gou_tong_qing_kuang', verbose_name='治疗间沟通情况'),
        ),
        migrations.DeleteModel(
            name='A6401',
        ),
    ]
