# Generated by Django 3.2.6 on 2023-03-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a6501',
            name='boolfield_yu_yue_shi_jian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='boolfield_qian_dao_que_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_dao_que_ren_for_boolfield_qian_dao_que_ren_A6502', to='dictionaries.qian_dao_que_ren', verbose_name='签到确认'),
        ),
    ]
