# Generated by Django 3.2.6 on 2023-08-13 13:15

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('service', '0002_auto_20230813_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 8, 6, 21, 15, 32, 509734)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.AlterField(
            model_name='customerschedulepackage',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='开始时间'),
        ),
    ]
