# Generated by Django 3.2.6 on 2022-10-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('service', '0002_auto_20221019_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerschedule_customer', to='core.customer', verbose_name='客户'),
        ),
    ]
