# Generated by Django 3.2.6 on 2022-06-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_customerschedule_customerscheduledraft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerschedule',
            old_name='schedule_draft',
            new_name='scheduled_draft',
        ),
        migrations.RenameField(
            model_name='customerschedule',
            old_name='service',
            new_name='scheduled_service',
        ),
        migrations.RenameField(
            model_name='customerscheduledraft',
            old_name='service',
            new_name='scheduled_service',
        ),
    ]
