# Generated by Django 3.2.6 on 2023-03-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230322_1627'),
        ('service', '0002_auto_20230316_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerschedule',
            name='priority_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.virtualstaff', verbose_name='优先操作员'),
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='priority_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.virtualstaff', verbose_name='优先操作员'),
        ),
    ]
