# Generated by Django 3.2.6 on 2022-06-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_nin_cong_he_chu_zhi_dao_wo_men_shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu'),
        ('service', '0002_auto_20220608_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_nin_cong_he_chu_zhi_dao_wo_men_de_fu_wu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nin_cong_he_chu_zhi_dao_wo_men_for_boolfield_nin_cong_he_chu_zhi_dao_wo_men_de_fu_wu_zhen_hou_sui_fang', to='dictionaries.nin_cong_he_chu_zhi_dao_wo_men', verbose_name='您从何处知道我们的服务'),
        ),
        migrations.AddField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_nin_shi_fou_yuan_yi_xiang_qin_peng_hao_you_tui_jian_wo_men_de_fu_wu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu_for_boolfield_nin_shi_fou_yuan_yi_xiang_qin_peng_hao_you_tui_jian_wo_men_de_fu_wu_zhen_hou_sui_fang', to='dictionaries.shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu', verbose_name='您是否愿意向亲朋好友推荐我们的服务'),
        ),
    ]
