# Generated by Django 3.2.6 on 2022-06-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_shi_fou_tong_guo'),
        ('core', '0001_initial'),
        ('icpc', '0001_initial'),
        ('service', '0002_yu_yue_zi_xun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Li_pei_shen_qing_chong_shen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('characterfield_name', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('characterfield_gender', models.CharField(max_length=255, null=True, verbose_name='被保人性别')),
                ('characterhssc_identification_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='证件号码')),
                ('boolfield_shen_qing_ren_xing_ming', models.CharField(blank=True, max_length=255, null=True, verbose_name='申请人姓名')),
                ('boolfield_zheng_jian_you_xiao_qi', models.CharField(blank=True, max_length=255, null=True, verbose_name='证件有效期')),
                ('boolfield_guo_ji_di_qu', models.CharField(blank=True, max_length=255, null=True, verbose_name='国籍/地区')),
                ('boolfield_hang_ye', models.CharField(blank=True, max_length=255, null=True, verbose_name='行业')),
                ('boolfield_zhi_ye', models.CharField(blank=True, max_length=255, null=True, verbose_name='职业')),
                ('boolfield_chang_zhu_di_zhi', models.CharField(blank=True, max_length=255, null=True, verbose_name='常住地址')),
                ('boolfield_lian_xi_dian_hua', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系电话')),
                ('boolfield_men_zhen_bing_li_fu_jian', models.ImageField(null=True, upload_to='uploads/', verbose_name='门诊病历附件')),
                ('boolfield_fei_yong_he_ji', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='费用合计')),
                ('boolfield_fei_yong', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='保单内服务费用')),
                ('boolfield_bao_dan_wai_fu_wu_fei_yong', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='保单外服务费用')),
                ('boolfield_fei_yong_qing_dan_fu_jian', models.ImageField(null=True, upload_to='uploads/', verbose_name='费用清单附件')),
                ('characterfield_age', models.CharField(max_length=255, null=True, verbose_name='年龄')),
                ('datetimefield_date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('boolfield_xu_hao', models.CharField(max_length=255, null=True, verbose_name='序号')),
                ('boolfield_bao_dan_hao', models.CharField(max_length=255, null=True, verbose_name='保单号')),
                ('boolfield_bao_an_shi_jian', models.DateTimeField(null=True, verbose_name='报案时间')),
                ('boolfield_chu_xian_shi_jian', models.DateTimeField(null=True, verbose_name='出险时间')),
                ('boolfield_bao_an_ren_lian_xi_dian_hua', models.CharField(max_length=255, null=True, verbose_name='报案人联系电话')),
                ('boolfield_chu_xian_ren_xing_ming', models.CharField(max_length=255, null=True, verbose_name='出险人姓名')),
                ('boolfield_chu_xian_di_dian', models.CharField(max_length=255, null=True, verbose_name='出险地点')),
                ('boolfield_chu_xian_di_dian_sheng_ji_bie', models.CharField(max_length=255, null=True, verbose_name='出险地点_省级别')),
                ('boolfield_chu_xian_di_dian_shi_ji_bie', models.CharField(max_length=255, null=True, verbose_name='出险地点_市级别')),
                ('boolfield_shi_gu_gai_kuo', models.CharField(max_length=255, null=True, verbose_name='事故概括')),
                ('boolfield_bei_bao_xian_ren_zheng_jian_hao_ma', models.CharField(max_length=255, null=True, verbose_name='被保险人证件号码')),
                ('boolfield_gui_shu_cheng_shi', models.CharField(max_length=255, null=True, verbose_name='归属城市')),
                ('boolfield_yi_yuan_xin_xi', models.CharField(max_length=255, null=True, verbose_name='医院信息')),
                ('boolfield_ji_bing_xin_xi', models.CharField(max_length=255, null=True, verbose_name='疾病信息')),
                ('boolfield_li_pei_jin_e_bao_xiao_jian_mian_jin_e', models.CharField(max_length=255, null=True, verbose_name='理赔金额_报销/减免金额')),
                ('boolfield_li_pei_fang_shi', models.CharField(max_length=255, null=True, verbose_name='理赔方式')),
                ('boolfield_bei_zhu', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('boolfield_bao_an_ren', models.CharField(max_length=255, null=True, verbose_name='报案人')),
                ('boolfield_tui_dan_yuan_yin', models.CharField(blank=True, max_length=255, null=True, verbose_name='人身险理赔申请书退单原因')),
                ('boolfield_men_zhen_ji_lu_dan_tui_dan_yuan_yin', models.CharField(blank=True, max_length=255, null=True, verbose_name='门诊记录单退单原因')),
                ('boolfield_li_pei_dui_zhang_dan_tui_dan_yuan_yin', models.CharField(blank=True, max_length=255, null=True, verbose_name='理赔对账单退单原因')),
                ('boolfield_li_pei_fei_yong_hui_zong_dan_tui_dan_yuan_yin', models.CharField(blank=True, max_length=255, null=True, verbose_name='理赔费用汇总单退单原因')),
                ('boolfield_bao_dan_nei_fu_wu_shou_fei_xiang_mu', models.ManyToManyField(related_name='fu_wu_xiang_mu_for_boolfield_bao_dan_nei_fu_wu_shou_fei_xiang_mu_li_pei_shen_qing_chong_shen', to='dictionaries.Fu_wu_xiang_mu', verbose_name='保单内服务收费项目')),
                ('boolfield_bao_dan_wai_fu_wu_shou_fei_xiang_mu', models.ManyToManyField(related_name='fu_wu_xiang_mu_for_boolfield_bao_dan_wai_fu_wu_shou_fei_xiang_mu_li_pei_shen_qing_chong_shen', to='dictionaries.Fu_wu_xiang_mu', verbose_name='保单外服务收费项目')),
                ('boolfield_jian_cha_xiang_mu', models.ManyToManyField(related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_li_pei_shen_qing_chong_shen', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目')),
                ('boolfield_li_pei_fei_yong_hui_zong_dan_qian_shu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_li_pei_fei_yong_hui_zong_dan_qian_shu_li_pei_shen_qing_chong_shen', to='dictionaries.qian_shu_que_ren', verbose_name='理赔费用汇总单签署')),
                ('boolfield_li_pei_men_zhen_ji_lu_qian_shu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_li_pei_men_zhen_ji_lu_qian_shu_li_pei_shen_qing_chong_shen', to='dictionaries.qian_shu_que_ren', verbose_name='理赔门诊记录签署')),
                ('boolfield_qi_ta_fu_wu_xiang_mu', models.ManyToManyField(blank=True, related_name='icpc8_other_health_interventions_for_boolfield_qi_ta_fu_wu_xiang_mu_li_pei_shen_qing_chong_shen', to='icpc.Icpc8_other_health_interventions', verbose_name='其他健康干预服务')),
                ('boolfield_qian_shu_que_ren', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_qian_shu_que_ren_li_pei_shen_qing_chong_shen', to='dictionaries.qian_shu_que_ren', verbose_name='理赔对账单签署')),
                ('boolfield_ren_shen_xian_li_pei_shen_qing_shu_qian_shu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_ren_shen_xian_li_pei_shen_qing_shu_qian_shu_li_pei_shen_qing_chong_shen', to='dictionaries.qian_shu_que_ren', verbose_name='人身险理赔申请书签署')),
                ('boolfield_yu_chu_xian_ren_guan_xi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yu_chu_xian_ren_guan_xi_for_boolfield_yu_chu_xian_ren_guan_xi_li_pei_shen_qing_chong_shen', to='dictionaries.yu_chu_xian_ren_guan_xi', verbose_name='与出险人关系')),
                ('boolfield_zhen_duan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_zhen_duan_li_pei_shen_qing_chong_shen', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='诊断')),
                ('boolfield_zheng_jian_lei_xing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zheng_jian_lei_xing_for_boolfield_zheng_jian_lei_xing_li_pei_shen_qing_chong_shen', to='dictionaries.zheng_jian_lei_xing', verbose_name='证件类型')),
                ('boolfield_zhi_liao_xiang_mu', models.ManyToManyField(related_name='icpc7_treatments_for_boolfield_zhi_liao_xiang_mu_li_pei_shen_qing_chong_shen', to='icpc.Icpc7_treatments', verbose_name='治疗项目')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='li_pei_shen_qing_chong_shen_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='li_pei_shen_qing_chong_shen_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='li_pei_shen_qing_chong_shen_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='li_pei_shen_qing_chong_shen_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='li_pei_shen_qing_chong_shen_pid', to='core.operationproc', verbose_name='作业进程id')),
                ('relatedfield_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_for_relatedfield_gender_li_pei_shen_qing_chong_shen', to='dictionaries.gender', verbose_name='性别')),
                ('relatedfield_symptom_list', models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_li_pei_shen_qing_chong_shen', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '理赔申请重审',
                'verbose_name_plural': '理赔申请重审',
            },
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='boolfield_bao_dan_nei_fu_wu_shou_fei_xiang_mu',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='boolfield_bao_dan_wai_fu_wu_shou_fei_xiang_mu',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='boolfield_qian_shu_que_ren',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='cpid',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='li_pei_fei_yong_hui_zong_dan_shen_he',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='boolfield_jian_cha_xiang_mu',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='boolfield_qi_ta_fu_wu_xiang_mu',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='boolfield_qian_shu_que_ren',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='boolfield_zhen_duan',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='boolfield_zhi_liao_xiang_mu',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='cpid',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='li_pei_men_zhen_ji_lu_shen_he',
            name='relatedfield_symptom_list',
        ),
        migrations.AlterModelOptions(
            name='li_pei_shen_qing_fu_wu',
            options={'verbose_name': '发起理赔申请', 'verbose_name_plural': '发起理赔申请'},
        ),
        migrations.AlterModelOptions(
            name='li_pei_shen_qing_shu_shen_he',
            options={'verbose_name': '理赔申请审核', 'verbose_name_plural': '理赔申请审核'},
        ),
        migrations.RemoveField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_qian_shu_que_ren',
        ),
        migrations.RemoveField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_tui_dan_yuan_yin',
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_an_ren',
            field=models.CharField(max_length=255, null=True, verbose_name='报案人'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_an_ren_lian_xi_dian_hua',
            field=models.CharField(max_length=255, null=True, verbose_name='报案人联系电话'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_an_shi_jian',
            field=models.DateTimeField(null=True, verbose_name='报案时间'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_dan_hao',
            field=models.CharField(max_length=255, null=True, verbose_name='保单号'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_dan_nei_fu_wu_shou_fei_xiang_mu',
            field=models.ManyToManyField(related_name='fu_wu_xiang_mu_for_boolfield_bao_dan_nei_fu_wu_shou_fei_xiang_mu_li_pei_shen_qing_shu_shen_he', to='dictionaries.Fu_wu_xiang_mu', verbose_name='保单内服务收费项目'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_dan_wai_fu_wu_fei_yong',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='保单外服务费用'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bao_dan_wai_fu_wu_shou_fei_xiang_mu',
            field=models.ManyToManyField(related_name='fu_wu_xiang_mu_for_boolfield_bao_dan_wai_fu_wu_shou_fei_xiang_mu_li_pei_shen_qing_shu_shen_he', to='dictionaries.Fu_wu_xiang_mu', verbose_name='保单外服务收费项目'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bei_bao_xian_ren_zheng_jian_hao_ma',
            field=models.CharField(max_length=255, null=True, verbose_name='被保险人证件号码'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bei_zhu',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_di_dian',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_di_dian_sheng_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点_省级别'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_di_dian_shi_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点_市级别'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_ren_xing_ming',
            field=models.CharField(max_length=255, null=True, verbose_name='出险人姓名'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_shi_jian',
            field=models.DateTimeField(null=True, verbose_name='出险时间'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_fei_yong',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='保单内服务费用'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_fei_yong_he_ji',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='费用合计'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_fei_yong_qing_dan_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='费用清单附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_gui_shu_cheng_shi',
            field=models.CharField(max_length=255, null=True, verbose_name='归属城市'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_ji_bing_xin_xi',
            field=models.CharField(max_length=255, null=True, verbose_name='疾病信息'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_jian_cha_xiang_mu',
            field=models.ManyToManyField(related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_li_pei_shen_qing_shu_shen_he', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_dui_zhang_dan_tui_dan_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='理赔对账单退单原因'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_fang_shi',
            field=models.CharField(max_length=255, null=True, verbose_name='理赔方式'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_fei_yong_hui_zong_dan_qian_shu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_li_pei_fei_yong_hui_zong_dan_qian_shu_li_pei_shen_qing_shu_shen_he', to='dictionaries.qian_shu_que_ren', verbose_name='理赔费用汇总单签署'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_fei_yong_hui_zong_dan_tui_dan_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='理赔费用汇总单退单原因'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_jin_e_bao_xiao_jian_mian_jin_e',
            field=models.CharField(max_length=255, null=True, verbose_name='理赔金额_报销/减免金额'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_men_zhen_ji_lu_qian_shu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_li_pei_men_zhen_ji_lu_qian_shu_li_pei_shen_qing_shu_shen_he', to='dictionaries.qian_shu_que_ren', verbose_name='理赔门诊记录签署'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_men_zhen_bing_li_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='门诊病历附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_men_zhen_ji_lu_dan_tui_dan_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='门诊记录单退单原因'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_qi_ta_fu_wu_xiang_mu',
            field=models.ManyToManyField(blank=True, related_name='icpc8_other_health_interventions_for_boolfield_qi_ta_fu_wu_xiang_mu_li_pei_shen_qing_shu_shen_he', to='icpc.Icpc8_other_health_interventions', verbose_name='其他健康干预服务'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_ren_shen_xian_li_pei_shen_qing_shu_qian_shu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_ren_shen_xian_li_pei_shen_qing_shu_qian_shu_li_pei_shen_qing_shu_shen_he', to='dictionaries.qian_shu_que_ren', verbose_name='人身险理赔申请书签署'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_shi_gu_gai_kuo',
            field=models.CharField(max_length=255, null=True, verbose_name='事故概括'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_xu_hao',
            field=models.CharField(max_length=255, null=True, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_yi_yuan_xin_xi',
            field=models.CharField(max_length=255, null=True, verbose_name='医院信息'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_zhen_duan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_zhen_duan_li_pei_shen_qing_shu_shen_he', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='诊断'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_zhi_liao_xiang_mu',
            field=models.ManyToManyField(related_name='icpc7_treatments_for_boolfield_zhi_liao_xiang_mu_li_pei_shen_qing_shu_shen_he', to='icpc.Icpc7_treatments', verbose_name='治疗项目'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='characterfield_age',
            field=models.CharField(max_length=255, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='relatedfield_symptom_list',
            field=models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_li_pei_shen_qing_shu_shen_he', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状'),
        ),
        migrations.AddField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_li_pei_shen_qing_tui_hui_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='理赔申请退回原因'),
        ),
        migrations.AddField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_shi_fou_tong_guo_he_bao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shi_fou_tong_guo_for_boolfield_shi_fou_tong_guo_he_bao_ti_jiao_he_bao_zi_liao', to='dictionaries.shi_fou_tong_guo', verbose_name='是否通过核保'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_qian_shu_que_ren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_qian_shu_que_ren_li_pei_shen_qing_shu_shen_he', to='dictionaries.qian_shu_que_ren', verbose_name='理赔对账单签署'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_tui_dan_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='人身险理赔申请书退单原因'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_zheng_jian_lei_xing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zheng_jian_lei_xing_for_boolfield_zheng_jian_lei_xing_li_pei_shen_qing_shu_shen_he', to='dictionaries.zheng_jian_lei_xing', verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='relatedfield_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_for_relatedfield_gender_li_pei_shen_qing_shu_shen_he', to='dictionaries.gender', verbose_name='性别'),
        ),
        migrations.DeleteModel(
            name='Li_pei_dui_zhang_dan_shen_he',
        ),
        migrations.DeleteModel(
            name='Li_pei_fei_yong_hui_zong_dan_shen_he',
        ),
        migrations.DeleteModel(
            name='Li_pei_men_zhen_ji_lu_shen_he',
        ),
    ]
