# Generated by Django 3.2.6 on 2023-04-02 05:39

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('service', '0002_alter_customerschedule_reference_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 3, 26, 13, 39, 20, 256091)), ('customer', django.db.models.expressions.F('customer'))), to='core.OperationProc', verbose_name='引用表单'),
        ),
    ]
