# Generated by Django 3.2.6 on 2023-08-23 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicepackagedetail_default_beginning_time'),
        ('service', '0002_auto_20230823_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerschedulepackage',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='priority_operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_workgroup': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.virtualstaff', verbose_name='优先操作员'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 8, 16, 22, 37, 23, 730848)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.AlterField(
            model_name='customerscheduledraft',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '指定开始时间'), (1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=0, verbose_name='执行时间基准'),
        ),
    ]
