# Generated by Django 3.2.6 on 2022-06-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('core', '0001_initial'),
        ('service', '0002_auto_20220607_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men_zhen_ji_lu_hui_zong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('characterfield_gender', models.CharField(max_length=255, null=True, verbose_name='被保人性别')),
                ('characterfield_name', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('boolfield_chang_zhu_di_zhi', models.CharField(max_length=255, null=True, verbose_name='常住地址')),
                ('datetimefield_date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('boolfield_fei_yong_he_ji', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='费用合计')),
                ('boolfield_men_zhen_bing_li_fu_jian', models.ImageField(null=True, upload_to='uploads/', verbose_name='门诊病历附件')),
                ('boolfield_jian_cha_xiang_mu', models.ManyToManyField(blank=True, related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_men_zhen_ji_lu_hui_zong', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目')),
                ('boolfield_qi_ta_fu_wu_xiang_mu', models.ManyToManyField(blank=True, related_name='icpc8_other_health_interventions_for_boolfield_qi_ta_fu_wu_xiang_mu_men_zhen_ji_lu_hui_zong', to='icpc.Icpc8_other_health_interventions', verbose_name='其他健康干预服务')),
                ('boolfield_zhen_duan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_zhen_duan_men_zhen_ji_lu_hui_zong', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='诊断')),
                ('boolfield_zhi_liao_xiang_mu', models.ManyToManyField(related_name='icpc7_treatments_for_boolfield_zhi_liao_xiang_mu_men_zhen_ji_lu_hui_zong', to='icpc.Icpc7_treatments', verbose_name='治疗项目')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men_zhen_ji_lu_hui_zong_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_zhen_ji_lu_hui_zong_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_zhen_ji_lu_hui_zong_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_zhen_ji_lu_hui_zong_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men_zhen_ji_lu_hui_zong_pid', to='core.operationproc', verbose_name='作业进程id')),
                ('relatedfield_symptom_list', models.ManyToManyField(blank=True, related_name='icpc3_symptoms_and_problems_for_relatedfield_symptom_list_men_zhen_ji_lu_hui_zong', to='icpc.Icpc3_symptoms_and_problems', verbose_name='症状')),
            ],
            options={
                'verbose_name': '门诊记录汇总',
                'verbose_name_plural': '门诊记录汇总',
            },
        ),
        migrations.AlterModelOptions(
            name='ju_min_ji_ben_xin_xi_diao_cha',
            options={'verbose_name': '基本信息调查', 'verbose_name_plural': '基本信息调查'},
        ),
        migrations.AlterModelOptions(
            name='yu_yue_zi_xun',
            options={'verbose_name': '咨询预约', 'verbose_name_plural': '咨询预约'},
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='boolfield_bao_dan_hao',
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='boolfield_bao_xian_you_xiao_qi',
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='boolfield_bao_xian_ze_ren',
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='boolfield_lian_xi_dian_hua',
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='boolfield_xu_hao',
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='boolfield_zheng_jian_lei_xing',
        ),
        migrations.RemoveField(
            model_name='men_zhen_ji_lu',
            name='characterhssc_identification_number',
        ),
        migrations.AddField(
            model_name='chong_xin_yu_yue_an_pai',
            name='boolfield_ju_jue_jie_dan_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拒绝接单原因'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_bei_bao_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='被保人证件附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_shen_qing_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='申请人证件附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_bei_bao_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='被保人证件附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_shen_qing_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='申请人证件附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_bei_bao_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='被保人证件附件'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_shen_qing_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='申请人证件附件'),
        ),
        migrations.AddField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_bei_bao_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='被保人证件附件'),
        ),
        migrations.AddField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_shen_qing_ren_zheng_jian_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='申请人证件附件'),
        ),
        migrations.AddField(
            model_name='yu_yue_que_ren',
            name='boolfield_ju_jue_jie_dan_yuan_yin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拒绝接单原因'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_fei_yong_qing_dan_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='汇总费用清单附件'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_jian_cha_xiang_mu',
            field=models.ManyToManyField(blank=True, related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_li_pei_shen_qing_chong_shen', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_fei_yong_qing_dan_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='汇总费用清单附件'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_jian_cha_xiang_mu',
            field=models.ManyToManyField(blank=True, related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_li_pei_shen_qing_fu_wu', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_fei_yong_qing_dan_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='汇总费用清单附件'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_jian_cha_xiang_mu',
            field=models.ManyToManyField(blank=True, related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_li_pei_shen_qing_shu_shen_he', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目'),
        ),
        migrations.AlterField(
            model_name='men_zhen_ji_lu',
            name='boolfield_jian_cha_xiang_mu',
            field=models.ManyToManyField(blank=True, related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_men_zhen_ji_lu', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_fei_yong_qing_dan_fu_jian',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='汇总费用清单附件'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_jian_cha_xiang_mu',
            field=models.ManyToManyField(blank=True, related_name='icpc4_physical_examination_and_tests_for_boolfield_jian_cha_xiang_mu_ti_jiao_he_bao_zi_liao', to='icpc.Icpc4_physical_examination_and_tests', verbose_name='检查项目'),
        ),
        migrations.AlterField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_deng_hou_qing_kuang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deng_hou_shi_jian_for_boolfield_deng_hou_qing_kuang_zhen_hou_sui_fang', to='dictionaries.deng_hou_shi_jian', verbose_name='等候情况'),
        ),
        migrations.AlterField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_fu_wu_xiao_guo_ping_jia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fu_wu_xiao_guo_ping_jia_for_boolfield_fu_wu_xiao_guo_ping_jia_zhen_hou_sui_fang', to='dictionaries.fu_wu_xiao_guo_ping_jia', verbose_name='治疗感受/效果评价'),
        ),
        migrations.DeleteModel(
            name='Bei_bao_ren_ji_ben_xin_xi_que_ren',
        ),
    ]
