# Generated by Django 3.2.6 on 2023-04-05 09:08

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_service_type'),
        ('service', '0003_alter_customerschedule_reference_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='a3101',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 3, 29, 17, 8, 43, 346018)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
    ]
