# Generated by Django 3.2.6 on 2023-08-23 14:42

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicepackagedetail_default_beginning_time'),
        ('service', '0003_auto_20230823_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 8, 16, 22, 42, 0, 608152)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.AlterField(
            model_name='customerschedulepackage',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 14, 42, 0, 605152, tzinfo=utc), null=True, verbose_name='开始时间'),
        ),
    ]
