# Generated by Django 3.2.6 on 2023-06-11 04:03

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('service', '0003_alter_customerschedule_reference_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='cpid',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='hssc_id',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='label',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='chu_fang_ming_xi',
            name='updated_time',
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 6, 4, 12, 3, 5, 995269)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
    ]
