# Generated by Django 3.2.6 on 2022-10-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_customerschedule_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerschedule',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='是否已安排'),
        ),
    ]
