# Generated by Django 3.2.6 on 2022-05-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220528_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a6501',
            name='boolfield_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_boolfield_ze_ren_ren_A6501', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='boolfield_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_boolfield_ze_ren_ren_A6502', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='ju_min_ji_ben_xin_xi_diao_cha',
            name='relatedfield_signed_family_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_relatedfield_signed_family_doctor_ju_min_ji_ben_xin_xi_diao_cha', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='签约家庭医生'),
        ),
        migrations.AlterField(
            model_name='qian_yue_fu_wu',
            name='boolfield_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_boolfield_ze_ren_ren_qian_yue_fu_wu', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='shen_qing_kong_fu_xue_tang_jian_cha_fu_wu',
            name='boolfield_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhi_yuan_ji_ben_xin_xi_biao_for_boolfield_ze_ren_ren_shen_qing_kong_fu_xue_tang_jian_cha_fu_wu', to='service.zhi_yuan_ji_ben_xin_xi_biao', verbose_name='责任人'),
        ),
    ]
