# Generated by Django 3.2.6 on 2022-06-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220623_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerschedule',
            old_name='scheduled_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='customerscheduledraft',
            old_name='scheduled_service',
            new_name='service',
        ),
    ]
