# Generated by Django 3.2.6 on 2022-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_customerschedule_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='已安排'),
        ),
    ]
