# Generated by Django 3.2.6 on 2023-05-12 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
        ('dictionaries', '0002_ping_fen'),
        ('core', '0004_systemoperand_operand_type'),
        ('service', '0004_alter_customerschedule_reference_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='a6501',
            name='boolfield_ze_ren_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualstaff_for_boolfield_ze_ren_ren_A6501', to='core.virtualstaff', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='yao_pin_ji_ben_xin_xi_biao',
            name='boolfield_bu_shi_ying_zheng',
            field=models.ManyToManyField(blank=True, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_bu_shi_ying_zheng_yao_pin_ji_ben_xin_xi_biao', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='不适应症'),
        ),
        migrations.AddField(
            model_name='yao_pin_ji_ben_xin_xi_biao',
            name='boolfield_shi_ying_zheng',
            field=models.ManyToManyField(blank=True, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_shi_ying_zheng_yao_pin_ji_ben_xin_xi_biao', to='icpc.Icpc5_evaluation_and_diagnoses', verbose_name='适应症'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 5, 5, 20, 45, 52, 306172)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.CreateModel(
            name='Man_yi_du_diao_cha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_xi_wang_zeng_jia_de_fu_wu_xiang_mu', models.CharField(blank=True, max_length=255, null=True, verbose_name='希望增加的服务项目')),
                ('boolfield_you_dai_gai_jin_de_fu_wu', models.CharField(blank=True, max_length=255, null=True, verbose_name='有待改进的服务')),
                ('boolfield_fu_wu_liu_cheng_ping_fen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ping_fen_for_boolfield_fu_wu_liu_cheng_ping_fen_man_yi_du_diao_cha', to='dictionaries.ping_fen', verbose_name='服务流程评分')),
                ('boolfield_fu_wu_xiao_lv_ping_fen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ping_fen_for_boolfield_fu_wu_xiao_lv_ping_fen_man_yi_du_diao_cha', to='dictionaries.ping_fen', verbose_name='服务效率评分')),
                ('boolfield_ping_tai_fu_wu_xiang_mu_ping_fen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ping_fen_for_boolfield_ping_tai_fu_wu_xiang_mu_ping_fen_man_yi_du_diao_cha', to='dictionaries.ping_fen', verbose_name='平台服务项目评分')),
                ('boolfield_yi_liao_fu_wu_ji_neng_xiang_mu_ping_fen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ping_fen_for_boolfield_yi_liao_fu_wu_ji_neng_xiang_mu_ping_fen_man_yi_du_diao_cha', to='dictionaries.ping_fen', verbose_name='医疗服务技能项目评分')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man_yi_du_diao_cha_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man_yi_du_diao_cha_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man_yi_du_diao_cha_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man_yi_du_diao_cha_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man_yi_du_diao_cha_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '满意度调查',
                'verbose_name_plural': '满意度调查',
            },
        ),
    ]
