# Generated by Django 3.2.6 on 2022-06-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20220608_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fen_zhen_que_ren',
            name='boolfield_shen_fen_xin_xi_yan_zheng',
        ),
        migrations.AddField(
            model_name='fen_zhen_que_ren',
            name='boolfield_dao_dian_shen_fen_yan_zheng',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='到店身份验证'),
        ),
    ]
