# Generated by Django 3.2.6 on 2023-06-11 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('service', '0004_auto_20230611_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chu_fang_ming_xi',
            name='ji_bing_ming_cheng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.men_zhen_chu_fang_biao', verbose_name='疾病名称'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 6, 4, 20, 50, 17, 15311)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
    ]
