# Generated by Django 3.2.6 on 2022-06-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicepackagedetail_options'),
        ('service', '0004_auto_20220623_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='servicepackage',
        ),
        migrations.CreateModel(
            name='CustomerSchedulePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedulepackage_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerschedulepackage_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerschedulepackage_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerschedulepackage_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedulepackage_pid', to='core.operationproc', verbose_name='作业进程id')),
                ('servicepackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicepackage', verbose_name='服务包')),
            ],
            options={
                'verbose_name': '安排服务计划',
                'verbose_name_plural': '安排服务计划',
            },
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='scheduled_Package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customerschedulepackage', verbose_name='日程草案'),
        ),
    ]
