# Generated by Django 3.2.6 on 2022-06-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_alter_shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu_options'),
        ('service', '0004_alter_zhen_hou_sui_fang_boolfield_nin_shi_fou_yuan_yi_xiang_qin_peng_hao_you_tui_jian_wo_men_de_fu_w'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_nin_shi_fou_yuan_yi_xiang_qin_peng_hao_you_tui_jian_wo_men_de_fu_wu',
        ),
        migrations.AddField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_nin_shi_fou_yuan_yi_xiang_ta_ren_tui_jian_wo_men',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu_for_boolfield_nin_shi_fou_yuan_yi_xiang_ta_ren_tui_jian_wo_men_zhen_hou_sui_fang', to='dictionaries.shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu', verbose_name='您是否愿意向他人推荐我们'),
        ),
    ]
