# Generated by Django 3.2.6 on 2023-08-23 14:43

import datetime
from django.db import migrations, models
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicepackagedetail_default_beginning_time'),
        ('service', '0004_auto_20230823_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 8, 16, 22, 43, 33, 505151)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.AlterField(
            model_name='customerschedulepackage',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='开始时间'),
        ),
    ]
