# Generated by Django 3.2.6 on 2022-06-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_alter_shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu_options'),
        ('service', '0005_auto_20220609_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_li_pei_jin_e_bao_xiao_jian_mian_jin_e',
        ),
        migrations.RemoveField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_li_pei_jin_e_bao_xiao_jian_mian_jin_e',
        ),
        migrations.RemoveField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_jin_e_bao_xiao_jian_mian_jin_e',
        ),
        migrations.RemoveField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_li_pei_jin_e_bao_xiao_jian_mian_jin_e',
        ),
        migrations.RemoveField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_fu_wu_xiao_guo_ping_jia',
        ),
        migrations.RemoveField(
            model_name='zhen_jian_sui_fang',
            name='boolfield_fu_wu_xiao_guo_ping_jia',
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_li_pei_jin_e',
            field=models.CharField(max_length=255, null=True, verbose_name='理赔金额'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_li_pei_jin_e',
            field=models.CharField(max_length=255, null=True, verbose_name='理赔金额'),
        ),
        migrations.AddField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_li_pei_jin_e',
            field=models.CharField(max_length=255, null=True, verbose_name='理赔金额'),
        ),
        migrations.AddField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_li_pei_jin_e',
            field=models.CharField(max_length=255, null=True, verbose_name='理赔金额'),
        ),
        migrations.AddField(
            model_name='zhen_hou_sui_fang',
            name='boolfield_zhi_liao_gan_shou_he_xiao_guo_ping_jia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fu_wu_xiao_guo_ping_jia_for_boolfield_zhi_liao_gan_shou_he_xiao_guo_ping_jia_zhen_hou_sui_fang', to='dictionaries.fu_wu_xiao_guo_ping_jia', verbose_name='治疗感受和效果评价'),
        ),
        migrations.AddField(
            model_name='zhen_jian_sui_fang',
            name='boolfield_zhi_liao_gan_shou_he_xiao_guo_ping_jia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fu_wu_xiao_guo_ping_jia_for_boolfield_zhi_liao_gan_shou_he_xiao_guo_ping_jia_zhen_jian_sui_fang', to='dictionaries.fu_wu_xiao_guo_ping_jia', verbose_name='治疗感受和效果评价'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_chu_xian_di_dian_sheng_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点省级别'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_chu_xian_di_dian_shi_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点市级别'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_chong_shen',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍地区'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_chu_xian_di_dian_sheng_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点省级别'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_chu_xian_di_dian_shi_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点市级别'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_fu_wu',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍地区'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_di_dian_sheng_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点省级别'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_chu_xian_di_dian_shi_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点市级别'),
        ),
        migrations.AlterField(
            model_name='li_pei_shen_qing_shu_shen_he',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍地区'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_chu_xian_di_dian_sheng_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点省级别'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_chu_xian_di_dian_shi_ji_bie',
            field=models.CharField(max_length=255, null=True, verbose_name='出险地点市级别'),
        ),
        migrations.AlterField(
            model_name='ti_jiao_he_bao_zi_liao',
            name='boolfield_guo_ji_di_qu',
            field=models.CharField(max_length=255, null=True, verbose_name='国籍地区'),
        ),
        migrations.DeleteModel(
            name='Bao_xian_yong_hu_zhu_ce',
        ),
    ]
