# Generated by Django 3.2.6 on 2022-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20220601_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ju_min_ji_ben_xin_xi_diao_cha',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='测试'),
        ),
    ]
