# Generated by Django 3.2.6 on 2022-06-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicepackagedetail_options'),
        ('service', '0005_auto_20220623_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerscheduledraft',
            options={'verbose_name': '服务项目安排', 'verbose_name_plural': '服务项目安排'},
        ),
        migrations.AlterModelOptions(
            name='customerschedulepackage',
            options={'verbose_name': '安排服务包', 'verbose_name_plural': '安排服务包'},
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='scheduled_Package',
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='schedule_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customerschedulepackage', verbose_name='服务包'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='scheduled_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='服务人员'),
        ),
        migrations.AlterField(
            model_name='customerscheduledraft',
            name='scheduled_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='服务人员'),
        ),
    ]
