# Generated by Django 3.2.6 on 2023-05-14 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemoperand_operand_type'),
        ('icpc', '0001_initial'),
        ('service', '0005_auto_20230512_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_chang_yong_chu_fang_liang',
        ),
        migrations.RemoveField(
            model_name='shu_ye_zhu_she',
            name='boolfield_chang_yong_chu_fang_liang',
        ),
        migrations.RemoveField(
            model_name='yao_pin_ji_ben_xin_xi_biao',
            name='boolfield_chang_yong_chu_fang_liang',
        ),
        migrations.RemoveField(
            model_name='zhu_she_fu_wu',
            name='boolfield_chang_yong_chu_fang_liang',
        ),
        migrations.AddField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_dan_ci_yong_yao_liang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单次用药量'),
        ),
        migrations.AddField(
            model_name='men_zhen_chu_fang_biao',
            name='boolfield_ji_bing_ming_cheng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_ji_bing_ming_cheng_men_zhen_chu_fang_biao', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称'),
        ),
        migrations.AddField(
            model_name='shu_ye_zhu_she',
            name='boolfield_dan_ci_yong_yao_liang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单次用药量'),
        ),
        migrations.AddField(
            model_name='yao_pin_ji_ben_xin_xi_biao',
            name='boolfield_dan_ci_yong_yao_liang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单次用药量'),
        ),
        migrations.AddField(
            model_name='ying_yang_chu_fang',
            name='boolfield_ji_bing_ming_cheng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_ji_bing_ming_cheng_ying_yang_chu_fang', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称'),
        ),
        migrations.AddField(
            model_name='yun_dong_chu_fang',
            name='boolfield_ji_bing_ming_cheng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icpc5_evaluation_and_diagnoses_for_boolfield_ji_bing_ming_cheng_yun_dong_chu_fang', to='icpc.icpc5_evaluation_and_diagnoses', verbose_name='疾病名称'),
        ),
        migrations.AddField(
            model_name='zhu_she_fu_wu',
            name='boolfield_dan_ci_yong_yao_liang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单次用药量'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 5, 7, 21, 52, 19, 787948)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
    ]
