# Generated by Django 3.2.6 on 2022-10-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hsscbaseformmodel_pid'),
        ('service', '0005_alter_customerschedule_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a3101',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3101_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a3502',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3502_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6201',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6201_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6202',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6202_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6217',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6217_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6218',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6218_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6220',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6220_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6299',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6299_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6501',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6501_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='a6502',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a6502_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='can_hou_2_xiao_shi_xue_tang',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_hou_2_xiao_shi_xue_tang_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='已生成任务'),
        ),
        migrations.AlterField(
            model_name='customerschedule',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedule_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='customerschedulelist',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedulelist_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='customerschedulepackage',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerschedulepackage_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='fu_wu_fen_gong_ji_gou_ji_ben_xin_xi_diao_cha',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fu_wu_fen_gong_ji_gou_ji_ben_xin_xi_diao_cha_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='kong_fu_xue_tang_jian_cha',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kong_fu_xue_tang_jian_cha_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='men_zhen_chu_fang_biao',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men_zhen_chu_fang_biao_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='qian_yue_fu_wu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qian_yue_fu_wu_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='shen_qing_kong_fu_xue_tang_jian_cha_fu_wu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shen_qing_kong_fu_xue_tang_jian_cha_fu_wu_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='shu_ye_zhu_she',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shu_ye_zhu_she_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t6301',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t6301_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t8901',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t8901_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='t9001',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t9001_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='tang_hua_xue_hong_dan_bai_jian_cha_biao',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tang_hua_xue_hong_dan_bai_jian_cha_biao_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='tang_niao_bing_cha_ti',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tang_niao_bing_cha_ti_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='tang_niao_bing_zhuan_yong_wen_zhen',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tang_niao_bing_zhuan_yong_wen_zhen_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='tang_niao_bing_zi_wo_jian_ce',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tang_niao_bing_zi_wo_jian_ce_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='xue_ya_jian_ce',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xue_ya_jian_ce_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='xue_ya_jian_ce_ping_gu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xue_ya_jian_ce_ping_gu_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
        migrations.AlterField(
            model_name='yao_shi_fu_wu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yao_shi_fu_wu_pid', to='core.operationproc', verbose_name='作业进程id'),
        ),
    ]
