# Generated by Django 3.2.6 on 2022-06-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20220623_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerschedule',
            name='cpid',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='hssc_id',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='label',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customerschedule',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='cpid',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='hssc_id',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='label',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='updated_time',
        ),
    ]
