# Generated by Django 3.2.6 on 2023-06-14 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('core', '0001_initial'),
        ('service', '0007_auto_20230614_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 6, 7, 21, 46, 32, 882418)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.CreateModel(
            name='Men_zhen_chu_fang_biao_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolfield_yong_yao_liao_cheng', models.CharField(blank=True, max_length=255, null=True, verbose_name='用药疗程')),
                ('boolfield_dan_ci_yong_yao_liang', models.CharField(blank=True, max_length=255, null=True, verbose_name='单次用药量')),
                ('boolfield_yong_yao_pin_ci', models.CharField(blank=True, max_length=255, null=True, verbose_name='用药频次')),
                ('boolfield_yao_pin_ming', models.ManyToManyField(blank=True, related_name='medicine_for_boolfield_yao_pin_ming_chu_fang_ming_xi', to='core.Medicine', verbose_name='药品名')),
                ('boolfield_yong_yao_tu_jing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yong_yao_tu_jing_for_boolfield_yong_yao_tu_jing_chu_fang_ming_xi', to='dictionaries.yong_yao_tu_jing', verbose_name='用药途径')),
                ('men_zhen_chu_fang_biao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.men_zhen_chu_fang_biao', verbose_name='药品处方')),
            ],
            options={
                'verbose_name': '药品处方明细',
                'verbose_name_plural': '药品处方明细',
            },
        ),
    ]
