# Generated by Django 3.2.6 on 2022-06-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicepackagedetail_options'),
        ('service', '0008_auto_20220625_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='scheduled_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='服务人员'),
        ),
        migrations.AlterField(
            model_name='customerscheduledraft',
            name='scheduled_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='服务人员'),
        ),
    ]
