# Generated by Django 3.2.6 on 2023-06-15 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('core', '0001_initial'),
        ('service', '0008_auto_20230614_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerschedule',
            name='reference_operation',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('created_time__gte', datetime.datetime(2023, 6, 8, 16, 45, 26, 37273)), ('customer', django.db.models.expressions.F('customer')), ('service__service_type', 2)), to='core.OperationProc', verbose_name='引用表单'),
        ),
        migrations.AlterField(
            model_name='men_zhen_chu_fang_biao_list',
            name='boolfield_yao_pin_ming',
            field=models.ManyToManyField(blank=True, related_name='medicine_for_boolfield_yao_pin_ming_men_zhen_chu_fang_biao', to='core.Medicine', verbose_name='药品名'),
        ),
        migrations.AlterField(
            model_name='men_zhen_chu_fang_biao_list',
            name='boolfield_yong_yao_tu_jing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yong_yao_tu_jing_for_boolfield_yong_yao_tu_jing_men_zhen_chu_fang_biao', to='dictionaries.yong_yao_tu_jing', verbose_name='用药途径'),
        ),
    ]
