# Generated by Django 3.2.6 on 2022-06-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220626_1637'),
        ('service', '0009_auto_20220626_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='cycle_option',
        ),
        migrations.RemoveField(
            model_name='customerscheduledraft',
            name='duration',
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='customerschedule',
            name='schedule_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customerschedulepackage', verbose_name='服务包'),
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='cycle_frequency',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='每周期频次'),
        ),
        migrations.AddField(
            model_name='customerscheduledraft',
            name='cycle_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '总共'), (1, '每天'), (2, '每周'), (3, '每月'), (4, '每季'), (5, '每年')], default=0, null=True, verbose_name='周期单位'),
        ),
        migrations.AlterField(
            model_name='customerscheduledraft',
            name='cycle_times',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='周期总数'),
        ),
    ]
