# Generated by Django 3.2.6 on 2022-08-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_chengbaorenyuanqingdan_options'),
        ('dictionaries', '0002_shi_fou_an_pai_zhi_liao_ji_hua'),
        ('service', '0013_alter_customerscheduledraft_default_beginning_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fen_zhen_que_ren',
            options={'verbose_name': '诊所到店确认', 'verbose_name_plural': '诊所到店确认'},
        ),
        migrations.AlterModelOptions(
            name='men_zhen_ji_lu',
            options={'verbose_name': '门诊病例记录服务', 'verbose_name_plural': '门诊病例记录服务'},
        ),
        migrations.AlterModelOptions(
            name='yu_yue_que_ren',
            options={'verbose_name': '诊所预约确认', 'verbose_name_plural': '诊所预约确认'},
        ),
        migrations.AlterModelOptions(
            name='yu_yue_tong_zhi',
            options={'verbose_name': '发送预约通知', 'verbose_name_plural': '发送预约通知'},
        ),
        migrations.AlterModelOptions(
            name='zhen_suo_yu_yue',
            options={'verbose_name': '诊所安排复诊', 'verbose_name_plural': '诊所安排复诊'},
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_fu_jia_fu_wu_yao_qiu',
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_jiu_zhen_ji_gou_ze_ren_ren',
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_jiu_zhen_wen_ti',
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_shi_yong_fu_wu_chan_pin',
        ),
        migrations.RemoveField(
            model_name='yu_yue_tong_zhi',
            name='boolfield_yu_yue_shi_jian',
        ),
        migrations.AlterField(
            model_name='customerscheduledraft',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=0, verbose_name='执行时间基准'),
        ),
        migrations.CreateModel(
            name='Tui_bao_shen_qing_fu_wu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_shen_qing_ren_xing_ming', models.CharField(max_length=255, null=True, verbose_name='申请人姓名')),
                ('boolfield_lian_xi_dian_hua', models.CharField(max_length=255, null=True, verbose_name='联系电话')),
                ('boolfield_bei_bao_ren_xing_ming', models.CharField(max_length=255, null=True, verbose_name='被保人姓名')),
                ('boolfield_bei_bao_xian_ren_zheng_jian_hao_ma', models.CharField(max_length=255, null=True, verbose_name='被保险人证件号码')),
                ('boolfield_shen_qing_tui_bao_yuan_yin', models.TextField(max_length=255, null=True, verbose_name='申请退保原因')),
                ('boolfield_shen_fen_zheng_jian_fu_jian', models.ImageField(null=True, upload_to='uploads/', verbose_name='身份证件附件')),
                ('boolfield_kou_qiang_jian_cha_ji_zhen_duan', models.ImageField(null=True, upload_to='uploads/', verbose_name='口腔检查及诊断')),
                ('boolfield_shi_yong_fu_wu_chan_pin', models.ManyToManyField(related_name='bao_xian_chan_pin_for_boolfield_shi_yong_fu_wu_chan_pin_tui_bao_shen_qing_fu_wu', to='dictionaries.Bao_xian_chan_pin', verbose_name='使用服务产品')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_bao_shen_qing_fu_wu_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tui_bao_shen_qing_fu_wu_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tui_bao_shen_qing_fu_wu_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tui_bao_shen_qing_fu_wu_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_bao_shen_qing_fu_wu_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '退保申请服务',
                'verbose_name_plural': '退保申请服务',
            },
        ),
        migrations.CreateModel(
            name='Tui_bao_que_ren_fu_wu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_ke_hu_tui_bao_shen_qing_shi_fou_tong_guo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_shu_que_ren_for_boolfield_ke_hu_tui_bao_shen_qing_shi_fou_tong_guo_tui_bao_que_ren_fu_wu', to='dictionaries.qian_shu_que_ren', verbose_name='客户退保申请是否通过')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_bao_que_ren_fu_wu_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tui_bao_que_ren_fu_wu_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tui_bao_que_ren_fu_wu_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tui_bao_que_ren_fu_wu_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_bao_que_ren_fu_wu_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '退保确认服务',
                'verbose_name_plural': '退保确认服务',
            },
        ),
        migrations.CreateModel(
            name='Shou_ci_dao_dian_que_ren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_dao_dian_shen_fen_yan_zheng', models.ImageField(null=True, upload_to='uploads/', verbose_name='到店身份验证')),
                ('boolfield_yu_yue_shi_jian', models.DateTimeField(null=True, verbose_name='预约时间')),
                ('boolfield_jiu_zhen_wen_ti', models.CharField(max_length=255, null=True, verbose_name='就诊问题')),
                ('boolfield_fu_jia_fu_wu_yao_qiu', models.CharField(blank=True, max_length=255, null=True, verbose_name='附加服务要求')),
                ('boolfield_dao_da_que_ren', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qian_dao_que_ren_for_boolfield_dao_da_que_ren_shou_ci_dao_dian_que_ren', to='dictionaries.qian_dao_que_ren', verbose_name='到达确认')),
                ('boolfield_jiu_zhen_ji_gou_ze_ren_ren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_boolfield_jiu_zhen_ji_gou_ze_ren_ren_shou_ci_dao_dian_que_ren', to='core.staff', verbose_name='就诊机构责任人')),
                ('boolfield_shi_yong_fu_wu_chan_pin', models.ManyToManyField(blank=True, related_name='bao_xian_chan_pin_for_boolfield_shi_yong_fu_wu_chan_pin_shou_ci_dao_dian_que_ren', to='dictionaries.Bao_xian_chan_pin', verbose_name='使用服务产品')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shou_ci_dao_dian_que_ren_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shou_ci_dao_dian_que_ren_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shou_ci_dao_dian_que_ren_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shou_ci_dao_dian_que_ren_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shou_ci_dao_dian_que_ren_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '首次到店确认',
                'verbose_name_plural': '首次到店确认',
            },
        ),
        migrations.CreateModel(
            name='Kou_qiang_jian_cha_ji_zhen_duan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_kou_qiang_jian_cha_ji_zhen_duan', models.ImageField(null=True, upload_to='uploads/', verbose_name='口腔检查及诊断')),
                ('boolfield_shi_fou_an_pai_zhi_liao_ji_hua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shi_fou_an_pai_zhi_liao_ji_hua_for_boolfield_shi_fou_an_pai_zhi_liao_ji_hua_kou_qiang_jian_cha_ji_zhen_duan', to='dictionaries.shi_fou_an_pai_zhi_liao_ji_hua', verbose_name='是否安排治疗计划')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kou_qiang_jian_cha_ji_zhen_duan_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kou_qiang_jian_cha_ji_zhen_duan_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kou_qiang_jian_cha_ji_zhen_duan_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kou_qiang_jian_cha_ji_zhen_duan_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kou_qiang_jian_cha_ji_zhen_duan_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '口腔检查及诊断',
                'verbose_name_plural': '口腔检查及诊断',
            },
        ),
        migrations.CreateModel(
            name='An_pai_zhi_liao_ji_hua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('created_time', models.DateTimeField(editable=False, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(editable=False, null=True, verbose_name='更新时间')),
                ('boolfield_zhi_liao_ji_hua', models.ImageField(null=True, upload_to='uploads/', verbose_name='治疗计划')),
                ('cpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='an_pai_zhi_liao_ji_hua_sid', to='core.contractserviceproc', verbose_name='服务进程id')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='an_pai_zhi_liao_ji_hua_creater', to='core.customer', verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='an_pai_zhi_liao_ji_hua_customer', to='core.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='an_pai_zhi_liao_ji_hua_operator', to='core.customer', verbose_name='操作员')),
                ('pid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='an_pai_zhi_liao_ji_hua_pid', to='core.operationproc', verbose_name='作业进程id')),
            ],
            options={
                'verbose_name': '安排治疗计划',
                'verbose_name_plural': '安排治疗计划',
            },
        ),
    ]
