# Generated by Django 3.2.6 on 2022-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icpc',
        ),
    ]
