# Generated by Django 3.2.6 on 2022-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpc', '0002_delete_icpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpc10_test_results_and_statistics',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc10_test_results_and_statistics',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc10_test_results_and_statistics',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc10_test_results_and_statistics',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc10_test_results_and_statistics',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc10_test_results_and_statistics',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc1_register_logins',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc1_register_logins',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc1_register_logins',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc1_register_logins',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc1_register_logins',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc1_register_logins',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc2_reservation_investigations',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc2_reservation_investigations',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc2_reservation_investigations',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc2_reservation_investigations',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc2_reservation_investigations',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc2_reservation_investigations',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc4_physical_examination_and_tests',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc4_physical_examination_and_tests',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc4_physical_examination_and_tests',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc4_physical_examination_and_tests',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc4_physical_examination_and_tests',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc4_physical_examination_and_tests',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc5_evaluation_and_diagnoses',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc5_evaluation_and_diagnoses',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc5_evaluation_and_diagnoses',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc5_evaluation_and_diagnoses',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc5_evaluation_and_diagnoses',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc5_evaluation_and_diagnoses',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc6_prescribe_medicines',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc6_prescribe_medicines',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc6_prescribe_medicines',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc6_prescribe_medicines',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc6_prescribe_medicines',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc6_prescribe_medicines',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc7_treatments',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc7_treatments',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc7_treatments',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc7_treatments',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc7_treatments',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc7_treatments',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc8_other_health_interventions',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc8_other_health_interventions',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc8_other_health_interventions',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc8_other_health_interventions',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc8_other_health_interventions',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc8_other_health_interventions',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='icpc9_referral_consultations',
            name='consider',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc9_referral_consultations',
            name='criteria',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc9_referral_consultations',
            name='exclude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc9_referral_consultations',
            name='include',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc9_referral_consultations',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='icpc9_referral_consultations',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
    ]
