# Generated by Django 3.2.6 on 2022-01-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '血型',
                'verbose_name_plural': '血型',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '性格',
                'verbose_name_plural': '性格',
            },
        ),
        migrations.CreateModel(
            name='Comparative_expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '比较表达',
                'verbose_name_plural': '比较表达',
            },
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '便捷程度',
                'verbose_name_plural': '便捷程度',
            },
        ),
        migrations.CreateModel(
            name='Dentition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '齿列',
                'verbose_name_plural': '齿列',
            },
        ),
        migrations.CreateModel(
            name='Dorsal_artery_pulsation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '足背动脉搏动情况',
                'verbose_name_plural': '足背动脉搏动情况',
            },
        ),
        migrations.CreateModel(
            name='Drug_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '药品清单',
                'verbose_name_plural': '药品清单',
            },
        ),
        migrations.CreateModel(
            name='Edema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '水肿情况',
                'verbose_name_plural': '水肿情况',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '文化程度',
                'verbose_name_plural': '文化程度',
            },
        ),
        migrations.CreateModel(
            name='Employee_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '职员表',
                'verbose_name_plural': '职员表',
            },
        ),
        migrations.CreateModel(
            name='Exercise_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '运动时长',
                'verbose_name_plural': '运动时长',
            },
        ),
        migrations.CreateModel(
            name='Family_relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '家庭成员关系',
                'verbose_name_plural': '家庭成员关系',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '频次',
                'verbose_name_plural': '频次',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '性别',
                'verbose_name_plural': '性别',
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '听力',
                'verbose_name_plural': '听力',
            },
        ),
        migrations.CreateModel(
            name='Institutions_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '机构清单',
                'verbose_name_plural': '机构清单',
            },
        ),
        migrations.CreateModel(
            name='Life_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '生活事件',
                'verbose_name_plural': '生活事件',
            },
        ),
        migrations.CreateModel(
            name='Lips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '口唇',
                'verbose_name_plural': '口唇',
            },
        ),
        migrations.CreateModel(
            name='Marital_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '婚姻状况',
                'verbose_name_plural': '婚姻状况',
            },
        ),
        migrations.CreateModel(
            name='Medical_expenses_burden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '医疗费用负担',
                'verbose_name_plural': '医疗费用负担',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '民族',
                'verbose_name_plural': '民族',
            },
        ),
        migrations.CreateModel(
            name='Normality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '正常性判断',
                'verbose_name_plural': '正常性判断',
            },
        ),
        migrations.CreateModel(
            name='Occupational_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '职业状况',
                'verbose_name_plural': '职业状况',
            },
        ),
        migrations.CreateModel(
            name='Pharynx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '咽部',
                'verbose_name_plural': '咽部',
            },
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '满意度',
                'verbose_name_plural': '满意度',
            },
        ),
        migrations.CreateModel(
            name='Service_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '服务角色',
                'verbose_name_plural': '服务角色',
            },
        ),
        migrations.CreateModel(
            name='Sports_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '运动类型',
                'verbose_name_plural': '运动类型',
            },
        ),
        migrations.CreateModel(
            name='State_degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '状态程度',
                'verbose_name_plural': '状态程度',
            },
        ),
        migrations.CreateModel(
            name='Type_of_residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '居住类型',
                'verbose_name_plural': '居住类型',
            },
        ),
    ]
