# Generated by Django 3.2.6 on 2022-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shi_fou_an_pai_zhi_liao_ji_hua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='值')),
                ('icpc', models.CharField(blank=True, max_length=5, null=True, verbose_name='ICPC编码')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
            ],
            options={
                'verbose_name': '是否安排治疗计划',
                'verbose_name_plural': '是否安排治疗计划',
            },
        ),
    ]
