# Generated by Django 3.2.6 on 2022-02-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20220119_1553'),
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug_list',
        ),
    ]
