# Generated by Django 3.2.6 on 2022-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xin_xi_que_ren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='值')),
                ('icpc', models.CharField(blank=True, max_length=5, null=True, verbose_name='ICPC编码')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
            ],
            options={
                'verbose_name': '绑定确认',
                'verbose_name_plural': '绑定确认',
            },
        ),
    ]
