# Generated by Django 3.2.6 on 2021-12-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '性格',
                'verbose_name_plural': '性格',
            },
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '便捷程度',
                'verbose_name_plural': '便捷程度',
            },
        ),
        migrations.CreateModel(
            name='Exercise_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '运动时长',
                'verbose_name_plural': '运动时长',
            },
        ),
        migrations.CreateModel(
            name='Sports_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '运动类型',
                'verbose_name_plural': '运动类型',
            },
        ),
        migrations.CreateModel(
            name='State_degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '状态程度',
                'verbose_name_plural': '状态程度',
            },
        ),
        migrations.DeleteModel(
            name='Athletic_ability',
        ),
        migrations.DeleteModel(
            name='Choose',
        ),
        migrations.DeleteModel(
            name='Contract_signatory',
        ),
        migrations.DeleteModel(
            name='Degree_expression',
        ),
        migrations.DeleteModel(
            name='Genetic_disease',
        ),
        migrations.DeleteModel(
            name='Time_period_expression',
        ),
        migrations.AlterModelOptions(
            name='dorsal_artery_pulsation',
            options={'verbose_name': '足背动脉搏动情况', 'verbose_name_plural': '足背动脉搏动情况'},
        ),
        migrations.RemoveField(
            model_name='blood_type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blood_type',
            name='score',
        ),
        migrations.RemoveField(
            model_name='comparative_expression',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comparative_expression',
            name='score',
        ),
        migrations.RemoveField(
            model_name='dentition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dentition',
            name='score',
        ),
        migrations.RemoveField(
            model_name='dorsal_artery_pulsation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dorsal_artery_pulsation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='drug_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug_list',
            name='score',
        ),
        migrations.RemoveField(
            model_name='edema',
            name='name',
        ),
        migrations.RemoveField(
            model_name='edema',
            name='score',
        ),
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='score',
        ),
        migrations.RemoveField(
            model_name='employee_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee_list',
            name='score',
        ),
        migrations.RemoveField(
            model_name='family_relationship',
            name='name',
        ),
        migrations.RemoveField(
            model_name='family_relationship',
            name='score',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='score',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='score',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='score',
        ),
        migrations.RemoveField(
            model_name='institutions_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='institutions_list',
            name='score',
        ),
        migrations.RemoveField(
            model_name='life_event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='life_event',
            name='score',
        ),
        migrations.RemoveField(
            model_name='lips',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lips',
            name='score',
        ),
        migrations.RemoveField(
            model_name='marital_status',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marital_status',
            name='score',
        ),
        migrations.RemoveField(
            model_name='medical_expenses_burden',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medical_expenses_burden',
            name='score',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='score',
        ),
        migrations.RemoveField(
            model_name='normality',
            name='name',
        ),
        migrations.RemoveField(
            model_name='normality',
            name='score',
        ),
        migrations.RemoveField(
            model_name='occupational_status',
            name='name',
        ),
        migrations.RemoveField(
            model_name='occupational_status',
            name='score',
        ),
        migrations.RemoveField(
            model_name='pharynx',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pharynx',
            name='score',
        ),
        migrations.RemoveField(
            model_name='satisfaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='satisfaction',
            name='score',
        ),
        migrations.RemoveField(
            model_name='service_role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service_role',
            name='score',
        ),
        migrations.RemoveField(
            model_name='type_of_residence',
            name='name',
        ),
        migrations.RemoveField(
            model_name='type_of_residence',
            name='score',
        ),
        migrations.AddField(
            model_name='blood_type',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='comparative_expression',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='dentition',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='dorsal_artery_pulsation',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='drug_list',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='edema',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='education',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='employee_list',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='family_relationship',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='frequency',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='gender',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='institutions_list',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='life_event',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='lips',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='marital_status',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='medical_expenses_burden',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='normality',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='occupational_status',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='pharynx',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='satisfaction',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='service_role',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
        migrations.AddField(
            model_name='type_of_residence',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='值'),
        ),
    ]
