# Generated by Django 3.2.6 on 2022-11-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Da_bian_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Jian_kang_zi_wo_ping_jia',
        ),
        migrations.DeleteModel(
            name='Kong_qi_wu_ran_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Life_event',
        ),
        migrations.DeleteModel(
            name='Man_bing_diao_cha',
        ),
        migrations.DeleteModel(
            name='Qi_ta_huan_jing_wu_ran_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Qian_yue_qing_kuang',
        ),
        migrations.DeleteModel(
            name='She_bei_shi_yong_fu_wu_gong_neng',
        ),
        migrations.DeleteModel(
            name='Shi_pin_he_yin_shui_an_quan_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Xi_yan_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Yin_jiu_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Yin_shi_gui_lv_qing_kuang',
        ),
        migrations.DeleteModel(
            name='Zao_sheng_wu_ran_qing_kuang',
        ),
    ]
