# Generated by Django 3.2.6 on 2022-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nin_cong_he_chu_zhi_dao_wo_men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='值')),
                ('icpc', models.CharField(blank=True, max_length=5, null=True, verbose_name='ICPC编码')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
            ],
            options={
                'verbose_name': '您从何处知道我们的服务',
                'verbose_name_plural': '您从何处知道我们的服务',
            },
        ),
        migrations.CreateModel(
            name='Shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='值')),
                ('icpc', models.CharField(blank=True, max_length=5, null=True, verbose_name='ICPC编码')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
            ],
            options={
                'verbose_name': '是否愿意向家人朋友推荐我们的服务',
                'verbose_name_plural': '是否愿意向家人朋友推荐我们的服务',
            },
        ),
    ]
