# Generated by Django 3.2.6 on 2022-06-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_nin_cong_he_chu_zhi_dao_wo_men_shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shi_fou_yuan_yi_xiang_jia_ren_peng_you_tui_jian_wo_men_de_fu_wu',
            options={'verbose_name': '是否愿意向他人推荐我们', 'verbose_name_plural': '是否愿意向他人推荐我们'},
        ),
    ]
