# Generated by Django 3.2.6 on 2021-08-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20210830_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood_type',
        ),
        migrations.DeleteModel(
            name='Contract_signatory',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Marital_status',
        ),
        migrations.DeleteModel(
            name='Medical_expenses_burden',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Occupational_status',
        ),
        migrations.DeleteModel(
            name='Relationship_with_the_head_of_household',
        ),
        migrations.DeleteModel(
            name='Service_role',
        ),
        migrations.DeleteModel(
            name='Type_of_residence',
        ),
    ]
