# Generated by Django 3.2.6 on 2022-02-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_delete_drug_list'),
        ('forms', '0008_auto_20220223_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_list',
        ),
        migrations.DeleteModel(
            name='Institutions_list',
        ),
        migrations.DeleteModel(
            name='Service_role',
        ),
    ]
