# Generated by Django 3.2.6 on 2021-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0008_athletic_ability_dentition_dorsal_artery_pulsation_hearing_lips_pharynx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='名称')),
                ('score', models.SmallIntegerField(blank=True, null=True, verbose_name='分值')),
            ],
            options={
                'verbose_name': '水肿情况',
                'verbose_name_plural': '水肿情况',
            },
        ),
        migrations.CreateModel(
            name='Normality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='名称')),
                ('score', models.SmallIntegerField(blank=True, null=True, verbose_name='分值')),
            ],
            options={
                'verbose_name': '正常性判断',
                'verbose_name_plural': '正常性判断',
            },
        ),
    ]
