# Generated by Django 3.2.6 on 2022-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='机构名称')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='药品名称')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
                'ordering': ['id'],
            },
        ),
    ]
