from django.urls import path
from django.urls.resolvers import URLPattern
from .views import *

urlpatterns = [
	path('', index_view, name='index'),
	path('index/', index_view, name='index'),
	path("user_registrys/", User_registry_ListView.as_view(), name="user_registry_list_url"),
	path("user_registry/create/", User_registry_CreateView.as_view(), name="user_registry_create_url"),
	path("user_registry/<str:slug>/", User_registry_DetailView.as_view(), name="user_registry_detail_url"),
	path("user_registry/<str:slug>/update/", User_registry_UpdateView.as_view(), name="user_registry_update_url"),
	path("user_registry/<str:slug>/delete/", User_registry_DeleteView.as_view(), name="user_registry_delete_url"),
	path("doctor_logins/", Doctor_login_ListView.as_view(), name="doctor_login_list_url"),
	path("doctor_login/create/", Doctor_login_CreateView.as_view(), name="doctor_login_create_url"),
	path("doctor_login/<str:slug>/", Doctor_login_DetailView.as_view(), name="doctor_login_detail_url"),
	path("doctor_login/<str:slug>/update/", Doctor_login_UpdateView.as_view(), name="doctor_login_update_url"),
	path("doctor_login/<str:slug>/delete/", Doctor_login_DeleteView.as_view(), name="doctor_login_delete_url"),
	path("user_logins/", User_login_ListView.as_view(), name="user_login_list_url"),
	path("user_login/create/", User_login_CreateView.as_view(), name="user_login_create_url"),
	path("user_login/<str:slug>/", User_login_DetailView.as_view(), name="user_login_detail_url"),
	path("user_login/<str:slug>/update/", User_login_UpdateView.as_view(), name="user_login_update_url"),
	path("user_login/<str:slug>/delete/", User_login_DeleteView.as_view(), name="user_login_delete_url"),
	path("doctor_registrys/", Doctor_registry_ListView.as_view(), name="doctor_registry_list_url"),
	path("doctor_registry/create/", Doctor_registry_CreateView.as_view(), name="doctor_registry_create_url"),
	path("doctor_registry/<str:slug>/", Doctor_registry_DetailView.as_view(), name="doctor_registry_detail_url"),
	path("doctor_registry/<str:slug>/update/", Doctor_registry_UpdateView.as_view(), name="doctor_registry_update_url"),
	path("doctor_registry/<str:slug>/delete/", Doctor_registry_DeleteView.as_view(), name="doctor_registry_delete_url"),
	path("basic_personal_informations/", Basic_personal_information_ListView.as_view(), name="basic_personal_information_list_url"),
	path("basic_personal_information/create/", Basic_personal_information_CreateView.as_view(), name="basic_personal_information_create_url"),
	path("basic_personal_information/<str:slug>/", Basic_personal_information_DetailView.as_view(), name="basic_personal_information_detail_url"),
	path("basic_personal_information/<str:slug>/update/", Basic_personal_information_UpdateView.as_view(), name="basic_personal_information_update_url"),
	path("basic_personal_information/<str:slug>/delete/", Basic_personal_information_DeleteView.as_view(), name="basic_personal_information_delete_url"),
	path("family_historys/", Family_history_ListView.as_view(), name="family_history_list_url"),
	path("family_history/create/", Family_history_CreateView.as_view(), name="family_history_create_url"),
	path("family_history/<str:slug>/", Family_history_DetailView.as_view(), name="family_history_detail_url"),
	path("family_history/<str:slug>/update/", Family_history_UpdateView.as_view(), name="family_history_update_url"),
	path("family_history/<str:slug>/delete/", Family_history_DeleteView.as_view(), name="family_history_delete_url"),
	path("history_of_infectious_diseasess/", History_of_infectious_diseases_ListView.as_view(), name="history_of_infectious_diseases_list_url"),
	path("history_of_infectious_diseases/create/", History_of_infectious_diseases_CreateView.as_view(), name="history_of_infectious_diseases_create_url"),
	path("history_of_infectious_diseases/<str:slug>/", History_of_infectious_diseases_DetailView.as_view(), name="history_of_infectious_diseases_detail_url"),
	path("history_of_infectious_diseases/<str:slug>/update/", History_of_infectious_diseases_UpdateView.as_view(), name="history_of_infectious_diseases_update_url"),
	path("history_of_infectious_diseases/<str:slug>/delete/", History_of_infectious_diseases_DeleteView.as_view(), name="history_of_infectious_diseases_delete_url"),
]